// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Cdn.Outputs
{

    [OutputType]
    public sealed class DomainOriginCertCheck
    {
        /// <summary>
        /// Indicates the list of certificates used for origin certificate validation. The list can contain up to 20 certificates.
        /// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        /// </summary>
        public readonly ImmutableArray<Outputs.DomainOriginCertCheckCertInfoList> CertInfoLists;
        /// <summary>
        /// Switch
        /// </summary>
        public readonly bool? Switch;

        [OutputConstructor]
        private DomainOriginCertCheck(
            ImmutableArray<Outputs.DomainOriginCertCheckCertInfoList> certInfoLists,

            bool? @switch)
        {
            CertInfoLists = certInfoLists;
            Switch = @switch;
        }
    }
}
