// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.privatezone;

import com.byteplus.bytepluscc.Utilities;
import com.byteplus.bytepluscc.privatezone.inputs.GetRecordArgs;
import com.byteplus.bytepluscc.privatezone.inputs.GetRecordPlainArgs;
import com.byteplus.bytepluscc.privatezone.inputs.GetResolverEndpointArgs;
import com.byteplus.bytepluscc.privatezone.inputs.GetResolverEndpointPlainArgs;
import com.byteplus.bytepluscc.privatezone.inputs.GetResolverRuleArgs;
import com.byteplus.bytepluscc.privatezone.inputs.GetResolverRulePlainArgs;
import com.byteplus.bytepluscc.privatezone.inputs.GetUserVpcAuthorizationArgs;
import com.byteplus.bytepluscc.privatezone.inputs.GetUserVpcAuthorizationPlainArgs;
import com.byteplus.bytepluscc.privatezone.outputs.GetRecordResult;
import com.byteplus.bytepluscc.privatezone.outputs.GetRecordsResult;
import com.byteplus.bytepluscc.privatezone.outputs.GetResolverEndpointResult;
import com.byteplus.bytepluscc.privatezone.outputs.GetResolverEndpointsResult;
import com.byteplus.bytepluscc.privatezone.outputs.GetResolverRuleResult;
import com.byteplus.bytepluscc.privatezone.outputs.GetResolverRulesResult;
import com.byteplus.bytepluscc.privatezone.outputs.GetUserVpcAuthorizationResult;
import com.byteplus.bytepluscc.privatezone.outputs.GetUserVpcAuthorizationsResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.resources.InvokeArgs;
import java.util.concurrent.CompletableFuture;

public final class PrivatezoneFunctions {
    /**
     * Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static Output<GetRecordResult> getRecord(GetRecordArgs args) {
        return getRecord(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static CompletableFuture<GetRecordResult> getRecordPlain(GetRecordPlainArgs args) {
        return getRecordPlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static Output<GetRecordResult> getRecord(GetRecordArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getRecord:getRecord", TypeShape.of(GetRecordResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static Output<GetRecordResult> getRecord(GetRecordArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getRecord:getRecord", TypeShape.of(GetRecordResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static CompletableFuture<GetRecordResult> getRecordPlain(GetRecordPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getRecord:getRecord", TypeShape.of(GetRecordResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static Output<GetRecordsResult> getRecords() {
        return getRecords(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static CompletableFuture<GetRecordsResult> getRecordsPlain() {
        return getRecordsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static Output<GetRecordsResult> getRecords(InvokeArgs args) {
        return getRecords(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static CompletableFuture<GetRecordsResult> getRecordsPlain(InvokeArgs args) {
        return getRecordsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static Output<GetRecordsResult> getRecords(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getRecords:getRecords", TypeShape.of(GetRecordsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static Output<GetRecordsResult> getRecords(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getRecords:getRecords", TypeShape.of(GetRecordsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::Record
     * 
     */
    public static CompletableFuture<GetRecordsResult> getRecordsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getRecords:getRecords", TypeShape.of(GetRecordsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static Output<GetResolverEndpointResult> getResolverEndpoint(GetResolverEndpointArgs args) {
        return getResolverEndpoint(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static CompletableFuture<GetResolverEndpointResult> getResolverEndpointPlain(GetResolverEndpointPlainArgs args) {
        return getResolverEndpointPlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static Output<GetResolverEndpointResult> getResolverEndpoint(GetResolverEndpointArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverEndpoint:getResolverEndpoint", TypeShape.of(GetResolverEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static Output<GetResolverEndpointResult> getResolverEndpoint(GetResolverEndpointArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverEndpoint:getResolverEndpoint", TypeShape.of(GetResolverEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static CompletableFuture<GetResolverEndpointResult> getResolverEndpointPlain(GetResolverEndpointPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getResolverEndpoint:getResolverEndpoint", TypeShape.of(GetResolverEndpointResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static Output<GetResolverEndpointsResult> getResolverEndpoints() {
        return getResolverEndpoints(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static CompletableFuture<GetResolverEndpointsResult> getResolverEndpointsPlain() {
        return getResolverEndpointsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static Output<GetResolverEndpointsResult> getResolverEndpoints(InvokeArgs args) {
        return getResolverEndpoints(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static CompletableFuture<GetResolverEndpointsResult> getResolverEndpointsPlain(InvokeArgs args) {
        return getResolverEndpointsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static Output<GetResolverEndpointsResult> getResolverEndpoints(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverEndpoints:getResolverEndpoints", TypeShape.of(GetResolverEndpointsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static Output<GetResolverEndpointsResult> getResolverEndpoints(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverEndpoints:getResolverEndpoints", TypeShape.of(GetResolverEndpointsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverEndpoint
     * 
     */
    public static CompletableFuture<GetResolverEndpointsResult> getResolverEndpointsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getResolverEndpoints:getResolverEndpoints", TypeShape.of(GetResolverEndpointsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static Output<GetResolverRuleResult> getResolverRule(GetResolverRuleArgs args) {
        return getResolverRule(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static CompletableFuture<GetResolverRuleResult> getResolverRulePlain(GetResolverRulePlainArgs args) {
        return getResolverRulePlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static Output<GetResolverRuleResult> getResolverRule(GetResolverRuleArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverRule:getResolverRule", TypeShape.of(GetResolverRuleResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static Output<GetResolverRuleResult> getResolverRule(GetResolverRuleArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverRule:getResolverRule", TypeShape.of(GetResolverRuleResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static CompletableFuture<GetResolverRuleResult> getResolverRulePlain(GetResolverRulePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getResolverRule:getResolverRule", TypeShape.of(GetResolverRuleResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static Output<GetResolverRulesResult> getResolverRules() {
        return getResolverRules(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static CompletableFuture<GetResolverRulesResult> getResolverRulesPlain() {
        return getResolverRulesPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static Output<GetResolverRulesResult> getResolverRules(InvokeArgs args) {
        return getResolverRules(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static CompletableFuture<GetResolverRulesResult> getResolverRulesPlain(InvokeArgs args) {
        return getResolverRulesPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static Output<GetResolverRulesResult> getResolverRules(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverRules:getResolverRules", TypeShape.of(GetResolverRulesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static Output<GetResolverRulesResult> getResolverRules(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getResolverRules:getResolverRules", TypeShape.of(GetResolverRulesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::ResolverRule
     * 
     */
    public static CompletableFuture<GetResolverRulesResult> getResolverRulesPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getResolverRules:getResolverRules", TypeShape.of(GetResolverRulesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static Output<GetUserVpcAuthorizationResult> getUserVpcAuthorization(GetUserVpcAuthorizationArgs args) {
        return getUserVpcAuthorization(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static CompletableFuture<GetUserVpcAuthorizationResult> getUserVpcAuthorizationPlain(GetUserVpcAuthorizationPlainArgs args) {
        return getUserVpcAuthorizationPlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static Output<GetUserVpcAuthorizationResult> getUserVpcAuthorization(GetUserVpcAuthorizationArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getUserVpcAuthorization:getUserVpcAuthorization", TypeShape.of(GetUserVpcAuthorizationResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static Output<GetUserVpcAuthorizationResult> getUserVpcAuthorization(GetUserVpcAuthorizationArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getUserVpcAuthorization:getUserVpcAuthorization", TypeShape.of(GetUserVpcAuthorizationResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static CompletableFuture<GetUserVpcAuthorizationResult> getUserVpcAuthorizationPlain(GetUserVpcAuthorizationPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getUserVpcAuthorization:getUserVpcAuthorization", TypeShape.of(GetUserVpcAuthorizationResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static Output<GetUserVpcAuthorizationsResult> getUserVpcAuthorizations() {
        return getUserVpcAuthorizations(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static CompletableFuture<GetUserVpcAuthorizationsResult> getUserVpcAuthorizationsPlain() {
        return getUserVpcAuthorizationsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static Output<GetUserVpcAuthorizationsResult> getUserVpcAuthorizations(InvokeArgs args) {
        return getUserVpcAuthorizations(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static CompletableFuture<GetUserVpcAuthorizationsResult> getUserVpcAuthorizationsPlain(InvokeArgs args) {
        return getUserVpcAuthorizationsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static Output<GetUserVpcAuthorizationsResult> getUserVpcAuthorizations(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getUserVpcAuthorizations:getUserVpcAuthorizations", TypeShape.of(GetUserVpcAuthorizationsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static Output<GetUserVpcAuthorizationsResult> getUserVpcAuthorizations(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatezone/getUserVpcAuthorizations:getUserVpcAuthorizations", TypeShape.of(GetUserVpcAuthorizationsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateZone::UserVPCAuthorization
     * 
     */
    public static CompletableFuture<GetUserVpcAuthorizationsResult> getUserVpcAuthorizationsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatezone/getUserVpcAuthorizations:getUserVpcAuthorizations", TypeShape.of(GetUserVpcAuthorizationsResult.class), args, Utilities.withVersion(options));
    }
}
