// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Cdn
{
    public static class GetShareConfigs
    {
        /// <summary>
        /// Plural Data Source schema for Byteplus::CDN::ShareConfig
        /// </summary>
        public static Task<GetShareConfigsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetShareConfigsResult>("bytepluscc:cdn/getShareConfigs:getShareConfigs", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::CDN::ShareConfig
        /// </summary>
        public static Output<GetShareConfigsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetShareConfigsResult>("bytepluscc:cdn/getShareConfigs:getShareConfigs", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::CDN::ShareConfig
        /// </summary>
        public static Output<GetShareConfigsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetShareConfigsResult>("bytepluscc:cdn/getShareConfigs:getShareConfigs", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetShareConfigsResult
    {
        /// <summary>
        /// Uniquely identifies the data source.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of Resource Identifiers.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetShareConfigsResult(
            string id,

            ImmutableArray<string> ids)
        {
            Id = id;
            Ids = ids;
        }
    }
}
