// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package transitrouter

import (
	"context"
	"reflect"

	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Plural Data Source schema for Byteplus::TransitRouter::TransitRouterForwardPolicyTable
func GetTransitRouterForwardPolicyTables(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetTransitRouterForwardPolicyTablesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTransitRouterForwardPolicyTablesResult
	err := ctx.Invoke("bytepluscc:transitrouter/getTransitRouterForwardPolicyTables:getTransitRouterForwardPolicyTables", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getTransitRouterForwardPolicyTables.
type GetTransitRouterForwardPolicyTablesResult struct {
	// Uniquely identifies the data source.
	Id string `pulumi:"id"`
	// Set of Resource Identifiers.
	Ids []string `pulumi:"ids"`
}

func GetTransitRouterForwardPolicyTablesOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetTransitRouterForwardPolicyTablesResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetTransitRouterForwardPolicyTablesResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("bytepluscc:transitrouter/getTransitRouterForwardPolicyTables:getTransitRouterForwardPolicyTables", nil, GetTransitRouterForwardPolicyTablesResultOutput{}, options).(GetTransitRouterForwardPolicyTablesResultOutput), nil
	}).(GetTransitRouterForwardPolicyTablesResultOutput)
}

// A collection of values returned by getTransitRouterForwardPolicyTables.
type GetTransitRouterForwardPolicyTablesResultOutput struct{ *pulumi.OutputState }

func (GetTransitRouterForwardPolicyTablesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTransitRouterForwardPolicyTablesResult)(nil)).Elem()
}

func (o GetTransitRouterForwardPolicyTablesResultOutput) ToGetTransitRouterForwardPolicyTablesResultOutput() GetTransitRouterForwardPolicyTablesResultOutput {
	return o
}

func (o GetTransitRouterForwardPolicyTablesResultOutput) ToGetTransitRouterForwardPolicyTablesResultOutputWithContext(ctx context.Context) GetTransitRouterForwardPolicyTablesResultOutput {
	return o
}

// Uniquely identifies the data source.
func (o GetTransitRouterForwardPolicyTablesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTransitRouterForwardPolicyTablesResult) string { return v.Id }).(pulumi.StringOutput)
}

// Set of Resource Identifiers.
func (o GetTransitRouterForwardPolicyTablesResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTransitRouterForwardPolicyTablesResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTransitRouterForwardPolicyTablesResultOutput{})
}
