// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Data Source schema for Byteplus::WAF::CustomPage
 */
export function getCustomPage(args: GetCustomPageArgs, opts?: pulumi.InvokeOptions): Promise<GetCustomPageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytepluscc:waf/getCustomPage:getCustomPage", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCustomPage.
 */
export interface GetCustomPageArgs {
    /**
     * Uniquely identifies the resource.
     */
    id: string;
}

/**
 * A collection of values returned by getCustomPage.
 */
export interface GetCustomPageResult {
    /**
     * Advanced condition configuration. Only takes effect when Advanced=1.
     */
    readonly accurate: outputs.waf.GetCustomPageAccurate;
    /**
     * Enable advanced conditions. 0: Off (default); 1: On. If enabled, Accurate must also be configured.
     */
    readonly advanced: number;
    /**
     * Custom response page content. Maximum length: 4096 bytes. Only effective when PageMode=0.
     */
    readonly body: string;
    /**
     * Client IP. Value is fixed as ALL, meaning it applies to all source IPs.
     */
    readonly clientIp: string;
    /**
     * Custom response status code, such as 403, 405, 503. Only effective when PageMode=0.
     */
    readonly code: string;
    /**
     * Custom response Content-Type response header. For example: text/html, application/json, etc. Only effective when PageMode=0.
     */
    readonly contentType: string;
    /**
     * Rule description.
     */
    readonly description: string;
    /**
     * Rule switch. 0: Off; 1: On.
     */
    readonly enable: number;
    /**
     * Domain name. The website domain name to be protected. Before calling, make sure the domain name has been added to the current WAF instance.
     */
    readonly host: string;
    /**
     * Uniquely identifies the resource.
     */
    readonly id: string;
    /**
     * Rule name. Must start with a Chinese character, letter, or number. Allows Chinese characters, letters, numbers, periods (.), underscores (_), and hyphens (-). Length: 1–128 characters.
     */
    readonly name: string;
    /**
     * Response page mode. 0: Custom response body; 2: Redirect URL.
     */
    readonly pageMode: number;
    /**
     * Associated protection policy. 1: Observe; 8: Block.
     */
    readonly policy: number;
    /**
     * Project name, which is the project associated with the current resource. Only projects with permissions under the current identity can be associated. Default is default.
     */
    readonly projectName: string;
    /**
     * Redirect target URL. Only effective when PageMode=2.
     */
    readonly redirectUrl: string;
    /**
     * Custom block response rule ID.
     */
    readonly ruleId: string;
    /**
     * Rule display ID. The RuleTag prefix for custom interception response rules is always B, consisting of the prefix B and a 12-digit RuleId (zero-padded in the middle if fewer than 12 digits). For example, RuleId=116869 corresponds to RuleTag=B000000116869.
     */
    readonly ruleTag: string;
    /**
     * Last updated time of the rule.
     */
    readonly updateTime: string;
    /**
     * URL path where the rule takes effect.
     */
    readonly url: string;
}
/**
 * Data Source schema for Byteplus::WAF::CustomPage
 */
export function getCustomPageOutput(args: GetCustomPageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCustomPageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytepluscc:waf/getCustomPage:getCustomPage", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCustomPage.
 */
export interface GetCustomPageOutputArgs {
    /**
     * Uniquely identifies the resource.
     */
    id: pulumi.Input<string>;
}
