// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Plural Data Source schema for Byteplus::WAF::SystemBot
 */
export function getSystemBots(opts?: pulumi.InvokeOptions): Promise<GetSystemBotsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytepluscc:waf/getSystemBots:getSystemBots", {
    }, opts);
}

/**
 * A collection of values returned by getSystemBots.
 */
export interface GetSystemBotsResult {
    /**
     * Uniquely identifies the data source.
     */
    readonly id: string;
    /**
     * Set of Resource Identifiers.
     */
    readonly ids: string[];
}
/**
 * Plural Data Source schema for Byteplus::WAF::SystemBot
 */
export function getSystemBotsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSystemBotsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytepluscc:waf/getSystemBots:getSystemBots", {
    }, opts);
}
