# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetTransitRouterMulticastDomainResult',
    'AwaitableGetTransitRouterMulticastDomainResult',
    'get_transit_router_multicast_domain',
    'get_transit_router_multicast_domain_output',
]

@pulumi.output_type
class GetTransitRouterMulticastDomainResult:
    """
    A collection of values returned by getTransitRouterMulticastDomain.
    """
    def __init__(__self__, creation_time=None, description=None, id=None, status=None, tags=None, transit_router_id=None, transit_router_multicast_domain_id=None, transit_router_multicast_domain_name=None, update_time=None):
        if creation_time and not isinstance(creation_time, str):
            raise TypeError("Expected argument 'creation_time' to be a str")
        pulumi.set(__self__, "creation_time", creation_time)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if transit_router_id and not isinstance(transit_router_id, str):
            raise TypeError("Expected argument 'transit_router_id' to be a str")
        pulumi.set(__self__, "transit_router_id", transit_router_id)
        if transit_router_multicast_domain_id and not isinstance(transit_router_multicast_domain_id, str):
            raise TypeError("Expected argument 'transit_router_multicast_domain_id' to be a str")
        pulumi.set(__self__, "transit_router_multicast_domain_id", transit_router_multicast_domain_id)
        if transit_router_multicast_domain_name and not isinstance(transit_router_multicast_domain_name, str):
            raise TypeError("Expected argument 'transit_router_multicast_domain_name' to be a str")
        pulumi.set(__self__, "transit_router_multicast_domain_name", transit_router_multicast_domain_name)
        if update_time and not isinstance(update_time, str):
            raise TypeError("Expected argument 'update_time' to be a str")
        pulumi.set(__self__, "update_time", update_time)

    @_builtins.property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> _builtins.str:
        """
        Creation time of the multicast domain.
        """
        return pulumi.get(self, "creation_time")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Description of the multicast domain. Length limit: 0–255 characters.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Uniquely identifies the resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Status of the multicast domain. Creating: being created. Available: available. Deleting: being deleted.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence['outputs.GetTransitRouterMulticastDomainTagResult']:
        """
        Tag set for the multicast domain.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="transitRouterId")
    def transit_router_id(self) -> _builtins.str:
        """
        Transit router instance ID.
        """
        return pulumi.get(self, "transit_router_id")

    @_builtins.property
    @pulumi.getter(name="transitRouterMulticastDomainId")
    def transit_router_multicast_domain_id(self) -> _builtins.str:
        """
        Multicast domain ID.
        """
        return pulumi.get(self, "transit_router_multicast_domain_id")

    @_builtins.property
    @pulumi.getter(name="transitRouterMulticastDomainName")
    def transit_router_multicast_domain_name(self) -> _builtins.str:
        """
        Name of the multicast domain. Length limit: 1–128 characters.
        """
        return pulumi.get(self, "transit_router_multicast_domain_name")

    @_builtins.property
    @pulumi.getter(name="updateTime")
    def update_time(self) -> _builtins.str:
        """
        Last updated time of the multicast domain.
        """
        return pulumi.get(self, "update_time")


class AwaitableGetTransitRouterMulticastDomainResult(GetTransitRouterMulticastDomainResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTransitRouterMulticastDomainResult(
            creation_time=self.creation_time,
            description=self.description,
            id=self.id,
            status=self.status,
            tags=self.tags,
            transit_router_id=self.transit_router_id,
            transit_router_multicast_domain_id=self.transit_router_multicast_domain_id,
            transit_router_multicast_domain_name=self.transit_router_multicast_domain_name,
            update_time=self.update_time)


def get_transit_router_multicast_domain(id: Optional[_builtins.str] = None,
                                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTransitRouterMulticastDomainResult:
    """
    Data Source schema for Byteplus::TransitRouter::TransitRouterMulticastDomain


    :param _builtins.str id: Uniquely identifies the resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('bytepluscc:transitrouter/getTransitRouterMulticastDomain:getTransitRouterMulticastDomain', __args__, opts=opts, typ=GetTransitRouterMulticastDomainResult).value

    return AwaitableGetTransitRouterMulticastDomainResult(
        creation_time=pulumi.get(__ret__, 'creation_time'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        status=pulumi.get(__ret__, 'status'),
        tags=pulumi.get(__ret__, 'tags'),
        transit_router_id=pulumi.get(__ret__, 'transit_router_id'),
        transit_router_multicast_domain_id=pulumi.get(__ret__, 'transit_router_multicast_domain_id'),
        transit_router_multicast_domain_name=pulumi.get(__ret__, 'transit_router_multicast_domain_name'),
        update_time=pulumi.get(__ret__, 'update_time'))
def get_transit_router_multicast_domain_output(id: pulumi.Input[Optional[_builtins.str]] = None,
                                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTransitRouterMulticastDomainResult]:
    """
    Data Source schema for Byteplus::TransitRouter::TransitRouterMulticastDomain


    :param _builtins.str id: Uniquely identifies the resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('bytepluscc:transitrouter/getTransitRouterMulticastDomain:getTransitRouterMulticastDomain', __args__, opts=opts, typ=GetTransitRouterMulticastDomainResult)
    return __ret__.apply(lambda __response__: GetTransitRouterMulticastDomainResult(
        creation_time=pulumi.get(__response__, 'creation_time'),
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        status=pulumi.get(__response__, 'status'),
        tags=pulumi.get(__response__, 'tags'),
        transit_router_id=pulumi.get(__response__, 'transit_router_id'),
        transit_router_multicast_domain_id=pulumi.get(__response__, 'transit_router_multicast_domain_id'),
        transit_router_multicast_domain_name=pulumi.get(__response__, 'transit_router_multicast_domain_name'),
        update_time=pulumi.get(__response__, 'update_time')))
