# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetTransitRouterTrafficQosQueuePoliciesResult',
    'AwaitableGetTransitRouterTrafficQosQueuePoliciesResult',
    'get_transit_router_traffic_qos_queue_policies',
    'get_transit_router_traffic_qos_queue_policies_output',
]

@pulumi.output_type
class GetTransitRouterTrafficQosQueuePoliciesResult:
    """
    A collection of values returned by getTransitRouterTrafficQosQueuePolicies.
    """
    def __init__(__self__, id=None, ids=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ids and not isinstance(ids, list):
            raise TypeError("Expected argument 'ids' to be a list")
        pulumi.set(__self__, "ids", ids)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Uniquely identifies the data source.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ids(self) -> Sequence[_builtins.str]:
        """
        Set of Resource Identifiers.
        """
        return pulumi.get(self, "ids")


class AwaitableGetTransitRouterTrafficQosQueuePoliciesResult(GetTransitRouterTrafficQosQueuePoliciesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTransitRouterTrafficQosQueuePoliciesResult(
            id=self.id,
            ids=self.ids)


def get_transit_router_traffic_qos_queue_policies(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTransitRouterTrafficQosQueuePoliciesResult:
    """
    Plural Data Source schema for Byteplus::TransitRouter::TransitRouterTrafficQosQueuePolicy
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('bytepluscc:transitrouter/getTransitRouterTrafficQosQueuePolicies:getTransitRouterTrafficQosQueuePolicies', __args__, opts=opts, typ=GetTransitRouterTrafficQosQueuePoliciesResult).value

    return AwaitableGetTransitRouterTrafficQosQueuePoliciesResult(
        id=pulumi.get(__ret__, 'id'),
        ids=pulumi.get(__ret__, 'ids'))
def get_transit_router_traffic_qos_queue_policies_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTransitRouterTrafficQosQueuePoliciesResult]:
    """
    Plural Data Source schema for Byteplus::TransitRouter::TransitRouterTrafficQosQueuePolicy
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('bytepluscc:transitrouter/getTransitRouterTrafficQosQueuePolicies:getTransitRouterTrafficQosQueuePolicies', __args__, opts=opts, typ=GetTransitRouterTrafficQosQueuePoliciesResult)
    return __ret__.apply(lambda __response__: GetTransitRouterTrafficQosQueuePoliciesResult(
        id=pulumi.get(__response__, 'id'),
        ids=pulumi.get(__response__, 'ids')))
