// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Vepfs.Inputs
{

    public sealed class DataFlowTaskEntryListFileInfoGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// TOS bucket containing the list file for task execution. Required when using a list file from the user's TOS bucket for preheating or settling.
        /// </summary>
        [Input("fileBucket")]
        public Input<string>? FileBucket { get; set; }

        /// <summary>
        /// Identifier for the list file used in task execution. For local list files, this is the identifier returned by CreatePreSignedUrl; for list files in the user's TOS bucket, this is the object path of the list file.
        /// </summary>
        [Input("fileKey")]
        public Input<string>? FileKey { get; set; }

        /// <summary>
        /// Name of the list file for task execution. Required when using either a local list file or a list file from the user's TOS bucket for preheating or settling.
        /// </summary>
        [Input("fileName")]
        public Input<string>? FileName { get; set; }

        public DataFlowTaskEntryListFileInfoGetArgs()
        {
        }
        public static new DataFlowTaskEntryListFileInfoGetArgs Empty => new DataFlowTaskEntryListFileInfoGetArgs();
    }
}
