# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'DbAccountAccountPrivilege',
    'DbAccountTableColumnPrivilege',
    'DbAccountTableColumnPrivilegeColumnPrivilege',
    'DbAccountTableColumnPrivilegeTablePrivilege',
    'GetDbAccountAccountPrivilegeResult',
    'GetDbAccountTableColumnPrivilegeResult',
    'GetDbAccountTableColumnPrivilegeColumnPrivilegeResult',
    'GetDbAccountTableColumnPrivilegeTablePrivilegeResult',
]

@pulumi.output_type
class DbAccountAccountPrivilege(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "accountPrivilege":
            suggest = "account_privilege"
        elif key == "accountPrivilegeDetails":
            suggest = "account_privilege_details"
        elif key == "dbName":
            suggest = "db_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in DbAccountAccountPrivilege. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        DbAccountAccountPrivilege.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        DbAccountAccountPrivilege.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 account_privilege: Optional[builtins.str] = None,
                 account_privilege_details: Optional[Sequence[builtins.str]] = None,
                 db_name: Optional[builtins.str] = None):
        """
        :param builtins.str account_privilege: 数据库权限的类型。取值范围：ReadWrite：读写权限。ReadOnly：只读权限。DDLOnly：仅 DDL 权限。DMLOnly：仅 DML 权限。Custom：自定义权限。Global：全局权限。None：清除账号权限。说明该参数作为请求参数时，有以下注意事项：仅支持在作为请求参数时允许取值为 Global 和 None。权限类型为单选，传多个时会报错。仅 GrantDBAccountPrivilege 接口支持为 AccountPrivilege 取值 None。当 AccountPrivilege 取值 None 时，如果 DBName 的取值为空字符串，则清除账号的所有全局权限。如果 DBName 的取值为指定数据库，则清除账号在该数据库的所有权限。
        :param Sequence[builtins.str] account_privilege_details: 账号的权限信息。当 AccountPrivilege 取值为 Custom 时，该字段的取值范围如下：SELECT INSERT UPDATE DELETE CREATE DROP REFERENCES INDEX ALTER CREATE TEMPORARY TABLES LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW EVENT TRIGGER CREATE ROUTINE ALTER ROUTINE 当 AccountPrivilege 取值为 Global 时，该字段的取值范围如下：PROCESS REPLICATION SLAVE REPLICATION CLIENT SELECT INSERT UPDATE DELETE CREATE DROP RELOAD REFERENCES INDEX ALTER LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW CREATE ROUTINE ALTER ROUTINE CREATE USER EVENT TRIGGER SHOW DATABASES CREATE TEMPORARY TABLES 说明  作为请求参数时，在 AccountPrivilege 取值为 Custom 时必填。 在 CreateDBAccount 接口中，会自动为账号赋予 REPLICATION SLAVE、PROCESS 和 REPLICATION CLIENT 全局权限。 可取多个值。使用英文逗号（,）分隔多个权限。写入方式为覆盖方式。
        :param builtins.str db_name: 需修改账号授权的或账号已有权限的数据库名称。说明在 CreateDBAccount 和 GrantDBAccountPrivilege 接口中作为请求参数时，需确认 DBName 对应的数据库已存在。进行全局授权的修改时，应为 DBName 传空字符。
        """
        if account_privilege is not None:
            pulumi.set(__self__, "account_privilege", account_privilege)
        if account_privilege_details is not None:
            pulumi.set(__self__, "account_privilege_details", account_privilege_details)
        if db_name is not None:
            pulumi.set(__self__, "db_name", db_name)

    @property
    @pulumi.getter(name="accountPrivilege")
    def account_privilege(self) -> Optional[builtins.str]:
        """
        数据库权限的类型。取值范围：ReadWrite：读写权限。ReadOnly：只读权限。DDLOnly：仅 DDL 权限。DMLOnly：仅 DML 权限。Custom：自定义权限。Global：全局权限。None：清除账号权限。说明该参数作为请求参数时，有以下注意事项：仅支持在作为请求参数时允许取值为 Global 和 None。权限类型为单选，传多个时会报错。仅 GrantDBAccountPrivilege 接口支持为 AccountPrivilege 取值 None。当 AccountPrivilege 取值 None 时，如果 DBName 的取值为空字符串，则清除账号的所有全局权限。如果 DBName 的取值为指定数据库，则清除账号在该数据库的所有权限。
        """
        return pulumi.get(self, "account_privilege")

    @property
    @pulumi.getter(name="accountPrivilegeDetails")
    def account_privilege_details(self) -> Optional[Sequence[builtins.str]]:
        """
        账号的权限信息。当 AccountPrivilege 取值为 Custom 时，该字段的取值范围如下：SELECT INSERT UPDATE DELETE CREATE DROP REFERENCES INDEX ALTER CREATE TEMPORARY TABLES LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW EVENT TRIGGER CREATE ROUTINE ALTER ROUTINE 当 AccountPrivilege 取值为 Global 时，该字段的取值范围如下：PROCESS REPLICATION SLAVE REPLICATION CLIENT SELECT INSERT UPDATE DELETE CREATE DROP RELOAD REFERENCES INDEX ALTER LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW CREATE ROUTINE ALTER ROUTINE CREATE USER EVENT TRIGGER SHOW DATABASES CREATE TEMPORARY TABLES 说明  作为请求参数时，在 AccountPrivilege 取值为 Custom 时必填。 在 CreateDBAccount 接口中，会自动为账号赋予 REPLICATION SLAVE、PROCESS 和 REPLICATION CLIENT 全局权限。 可取多个值。使用英文逗号（,）分隔多个权限。写入方式为覆盖方式。
        """
        return pulumi.get(self, "account_privilege_details")

    @property
    @pulumi.getter(name="dbName")
    def db_name(self) -> Optional[builtins.str]:
        """
        需修改账号授权的或账号已有权限的数据库名称。说明在 CreateDBAccount 和 GrantDBAccountPrivilege 接口中作为请求参数时，需确认 DBName 对应的数据库已存在。进行全局授权的修改时，应为 DBName 传空字符。
        """
        return pulumi.get(self, "db_name")


@pulumi.output_type
class DbAccountTableColumnPrivilege(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "columnPrivileges":
            suggest = "column_privileges"
        elif key == "dbName":
            suggest = "db_name"
        elif key == "tablePrivileges":
            suggest = "table_privileges"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in DbAccountTableColumnPrivilege. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        DbAccountTableColumnPrivilege.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        DbAccountTableColumnPrivilege.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 column_privileges: Optional[Sequence['outputs.DbAccountTableColumnPrivilegeColumnPrivilege']] = None,
                 db_name: Optional[builtins.str] = None,
                 table_privileges: Optional[Sequence['outputs.DbAccountTableColumnPrivilegeTablePrivilege']] = None):
        """
        :param builtins.str db_name: 对账号进行权限设置的表所属的数据库的名称。
        """
        if column_privileges is not None:
            pulumi.set(__self__, "column_privileges", column_privileges)
        if db_name is not None:
            pulumi.set(__self__, "db_name", db_name)
        if table_privileges is not None:
            pulumi.set(__self__, "table_privileges", table_privileges)

    @property
    @pulumi.getter(name="columnPrivileges")
    def column_privileges(self) -> Optional[Sequence['outputs.DbAccountTableColumnPrivilegeColumnPrivilege']]:
        return pulumi.get(self, "column_privileges")

    @property
    @pulumi.getter(name="dbName")
    def db_name(self) -> Optional[builtins.str]:
        """
        对账号进行权限设置的表所属的数据库的名称。
        """
        return pulumi.get(self, "db_name")

    @property
    @pulumi.getter(name="tablePrivileges")
    def table_privileges(self) -> Optional[Sequence['outputs.DbAccountTableColumnPrivilegeTablePrivilege']]:
        return pulumi.get(self, "table_privileges")


@pulumi.output_type
class DbAccountTableColumnPrivilegeColumnPrivilege(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "accountPrivilegeDetails":
            suggest = "account_privilege_details"
        elif key == "columnName":
            suggest = "column_name"
        elif key == "tableName":
            suggest = "table_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in DbAccountTableColumnPrivilegeColumnPrivilege. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        DbAccountTableColumnPrivilegeColumnPrivilege.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        DbAccountTableColumnPrivilegeColumnPrivilege.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 account_privilege_details: Optional[Sequence[builtins.str]] = None,
                 column_name: Optional[builtins.str] = None,
                 table_name: Optional[builtins.str] = None):
        """
        :param Sequence[builtins.str] account_privilege_details: 对账号进行列权限设置的权限信息。取值（可多选）：INSERT REFERENCES SELECT UPDATE说明多个权限之间使用英文逗号（,）分隔。
        :param builtins.str column_name: 对账号进行列权限设置的列的名称。
        :param builtins.str table_name: 对账号进行列权限设置的表所属的数据库的名称。
        """
        if account_privilege_details is not None:
            pulumi.set(__self__, "account_privilege_details", account_privilege_details)
        if column_name is not None:
            pulumi.set(__self__, "column_name", column_name)
        if table_name is not None:
            pulumi.set(__self__, "table_name", table_name)

    @property
    @pulumi.getter(name="accountPrivilegeDetails")
    def account_privilege_details(self) -> Optional[Sequence[builtins.str]]:
        """
        对账号进行列权限设置的权限信息。取值（可多选）：INSERT REFERENCES SELECT UPDATE说明多个权限之间使用英文逗号（,）分隔。
        """
        return pulumi.get(self, "account_privilege_details")

    @property
    @pulumi.getter(name="columnName")
    def column_name(self) -> Optional[builtins.str]:
        """
        对账号进行列权限设置的列的名称。
        """
        return pulumi.get(self, "column_name")

    @property
    @pulumi.getter(name="tableName")
    def table_name(self) -> Optional[builtins.str]:
        """
        对账号进行列权限设置的表所属的数据库的名称。
        """
        return pulumi.get(self, "table_name")


@pulumi.output_type
class DbAccountTableColumnPrivilegeTablePrivilege(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "accountPrivilegeDetails":
            suggest = "account_privilege_details"
        elif key == "tableName":
            suggest = "table_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in DbAccountTableColumnPrivilegeTablePrivilege. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        DbAccountTableColumnPrivilegeTablePrivilege.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        DbAccountTableColumnPrivilegeTablePrivilege.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 account_privilege_details: Optional[Sequence[builtins.str]] = None,
                 table_name: Optional[builtins.str] = None):
        """
        :param Sequence[builtins.str] account_privilege_details: 账号的表权限。取值范围（可多选）：ALTER CREATE DELETE DROP INDEX INSERT SELECT SHOW VIEW TRIGGER UPDATE CREATE VIEW REFERENCES 说明多个权限之间使用英文逗号（,）分隔。
        :param builtins.str table_name: 对账号进行权限设置的表的名称。
        """
        if account_privilege_details is not None:
            pulumi.set(__self__, "account_privilege_details", account_privilege_details)
        if table_name is not None:
            pulumi.set(__self__, "table_name", table_name)

    @property
    @pulumi.getter(name="accountPrivilegeDetails")
    def account_privilege_details(self) -> Optional[Sequence[builtins.str]]:
        """
        账号的表权限。取值范围（可多选）：ALTER CREATE DELETE DROP INDEX INSERT SELECT SHOW VIEW TRIGGER UPDATE CREATE VIEW REFERENCES 说明多个权限之间使用英文逗号（,）分隔。
        """
        return pulumi.get(self, "account_privilege_details")

    @property
    @pulumi.getter(name="tableName")
    def table_name(self) -> Optional[builtins.str]:
        """
        对账号进行权限设置的表的名称。
        """
        return pulumi.get(self, "table_name")


@pulumi.output_type
class GetDbAccountAccountPrivilegeResult(dict):
    def __init__(__self__, *,
                 account_privilege: builtins.str,
                 account_privilege_details: Sequence[builtins.str],
                 db_name: builtins.str):
        """
        :param builtins.str account_privilege: 数据库权限的类型。取值范围：ReadWrite：读写权限。ReadOnly：只读权限。DDLOnly：仅 DDL 权限。DMLOnly：仅 DML 权限。Custom：自定义权限。Global：全局权限。None：清除账号权限。说明该参数作为请求参数时，有以下注意事项：仅支持在作为请求参数时允许取值为 Global 和 None。权限类型为单选，传多个时会报错。仅 GrantDBAccountPrivilege 接口支持为 AccountPrivilege 取值 None。当 AccountPrivilege 取值 None 时，如果 DBName 的取值为空字符串，则清除账号的所有全局权限。如果 DBName 的取值为指定数据库，则清除账号在该数据库的所有权限。
        :param Sequence[builtins.str] account_privilege_details: 账号的权限信息。当 AccountPrivilege 取值为 Custom 时，该字段的取值范围如下：SELECT INSERT UPDATE DELETE CREATE DROP REFERENCES INDEX ALTER CREATE TEMPORARY TABLES LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW EVENT TRIGGER CREATE ROUTINE ALTER ROUTINE 当 AccountPrivilege 取值为 Global 时，该字段的取值范围如下：PROCESS REPLICATION SLAVE REPLICATION CLIENT SELECT INSERT UPDATE DELETE CREATE DROP RELOAD REFERENCES INDEX ALTER LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW CREATE ROUTINE ALTER ROUTINE CREATE USER EVENT TRIGGER SHOW DATABASES CREATE TEMPORARY TABLES 说明  作为请求参数时，在 AccountPrivilege 取值为 Custom 时必填。 在 CreateDBAccount 接口中，会自动为账号赋予 REPLICATION SLAVE、PROCESS 和 REPLICATION CLIENT 全局权限。 可取多个值。使用英文逗号（,）分隔多个权限。写入方式为覆盖方式。
        :param builtins.str db_name: 需修改账号授权的或账号已有权限的数据库名称。说明在 CreateDBAccount 和 GrantDBAccountPrivilege 接口中作为请求参数时，需确认 DBName 对应的数据库已存在。进行全局授权的修改时，应为 DBName 传空字符。
        """
        pulumi.set(__self__, "account_privilege", account_privilege)
        pulumi.set(__self__, "account_privilege_details", account_privilege_details)
        pulumi.set(__self__, "db_name", db_name)

    @property
    @pulumi.getter(name="accountPrivilege")
    def account_privilege(self) -> builtins.str:
        """
        数据库权限的类型。取值范围：ReadWrite：读写权限。ReadOnly：只读权限。DDLOnly：仅 DDL 权限。DMLOnly：仅 DML 权限。Custom：自定义权限。Global：全局权限。None：清除账号权限。说明该参数作为请求参数时，有以下注意事项：仅支持在作为请求参数时允许取值为 Global 和 None。权限类型为单选，传多个时会报错。仅 GrantDBAccountPrivilege 接口支持为 AccountPrivilege 取值 None。当 AccountPrivilege 取值 None 时，如果 DBName 的取值为空字符串，则清除账号的所有全局权限。如果 DBName 的取值为指定数据库，则清除账号在该数据库的所有权限。
        """
        return pulumi.get(self, "account_privilege")

    @property
    @pulumi.getter(name="accountPrivilegeDetails")
    def account_privilege_details(self) -> Sequence[builtins.str]:
        """
        账号的权限信息。当 AccountPrivilege 取值为 Custom 时，该字段的取值范围如下：SELECT INSERT UPDATE DELETE CREATE DROP REFERENCES INDEX ALTER CREATE TEMPORARY TABLES LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW EVENT TRIGGER CREATE ROUTINE ALTER ROUTINE 当 AccountPrivilege 取值为 Global 时，该字段的取值范围如下：PROCESS REPLICATION SLAVE REPLICATION CLIENT SELECT INSERT UPDATE DELETE CREATE DROP RELOAD REFERENCES INDEX ALTER LOCK TABLES EXECUTE CREATE VIEW SHOW VIEW CREATE ROUTINE ALTER ROUTINE CREATE USER EVENT TRIGGER SHOW DATABASES CREATE TEMPORARY TABLES 说明  作为请求参数时，在 AccountPrivilege 取值为 Custom 时必填。 在 CreateDBAccount 接口中，会自动为账号赋予 REPLICATION SLAVE、PROCESS 和 REPLICATION CLIENT 全局权限。 可取多个值。使用英文逗号（,）分隔多个权限。写入方式为覆盖方式。
        """
        return pulumi.get(self, "account_privilege_details")

    @property
    @pulumi.getter(name="dbName")
    def db_name(self) -> builtins.str:
        """
        需修改账号授权的或账号已有权限的数据库名称。说明在 CreateDBAccount 和 GrantDBAccountPrivilege 接口中作为请求参数时，需确认 DBName 对应的数据库已存在。进行全局授权的修改时，应为 DBName 传空字符。
        """
        return pulumi.get(self, "db_name")


@pulumi.output_type
class GetDbAccountTableColumnPrivilegeResult(dict):
    def __init__(__self__, *,
                 column_privileges: Sequence['outputs.GetDbAccountTableColumnPrivilegeColumnPrivilegeResult'],
                 db_name: builtins.str,
                 table_privileges: Sequence['outputs.GetDbAccountTableColumnPrivilegeTablePrivilegeResult']):
        """
        :param Sequence['GetDbAccountTableColumnPrivilegeColumnPrivilegeArgs'] column_privileges: 账号的列权限信息。
        :param builtins.str db_name: 对账号进行权限设置的表所属的数据库的名称。
        :param Sequence['GetDbAccountTableColumnPrivilegeTablePrivilegeArgs'] table_privileges: 账号的表权限信息。
        """
        pulumi.set(__self__, "column_privileges", column_privileges)
        pulumi.set(__self__, "db_name", db_name)
        pulumi.set(__self__, "table_privileges", table_privileges)

    @property
    @pulumi.getter(name="columnPrivileges")
    def column_privileges(self) -> Sequence['outputs.GetDbAccountTableColumnPrivilegeColumnPrivilegeResult']:
        """
        账号的列权限信息。
        """
        return pulumi.get(self, "column_privileges")

    @property
    @pulumi.getter(name="dbName")
    def db_name(self) -> builtins.str:
        """
        对账号进行权限设置的表所属的数据库的名称。
        """
        return pulumi.get(self, "db_name")

    @property
    @pulumi.getter(name="tablePrivileges")
    def table_privileges(self) -> Sequence['outputs.GetDbAccountTableColumnPrivilegeTablePrivilegeResult']:
        """
        账号的表权限信息。
        """
        return pulumi.get(self, "table_privileges")


@pulumi.output_type
class GetDbAccountTableColumnPrivilegeColumnPrivilegeResult(dict):
    def __init__(__self__, *,
                 account_privilege_details: Sequence[builtins.str],
                 column_name: builtins.str,
                 table_name: builtins.str):
        """
        :param Sequence[builtins.str] account_privilege_details: 对账号进行列权限设置的权限信息。取值（可多选）：INSERT REFERENCES SELECT UPDATE说明多个权限之间使用英文逗号（,）分隔。
        :param builtins.str column_name: 对账号进行列权限设置的列的名称。
        :param builtins.str table_name: 对账号进行列权限设置的表所属的数据库的名称。
        """
        pulumi.set(__self__, "account_privilege_details", account_privilege_details)
        pulumi.set(__self__, "column_name", column_name)
        pulumi.set(__self__, "table_name", table_name)

    @property
    @pulumi.getter(name="accountPrivilegeDetails")
    def account_privilege_details(self) -> Sequence[builtins.str]:
        """
        对账号进行列权限设置的权限信息。取值（可多选）：INSERT REFERENCES SELECT UPDATE说明多个权限之间使用英文逗号（,）分隔。
        """
        return pulumi.get(self, "account_privilege_details")

    @property
    @pulumi.getter(name="columnName")
    def column_name(self) -> builtins.str:
        """
        对账号进行列权限设置的列的名称。
        """
        return pulumi.get(self, "column_name")

    @property
    @pulumi.getter(name="tableName")
    def table_name(self) -> builtins.str:
        """
        对账号进行列权限设置的表所属的数据库的名称。
        """
        return pulumi.get(self, "table_name")


@pulumi.output_type
class GetDbAccountTableColumnPrivilegeTablePrivilegeResult(dict):
    def __init__(__self__, *,
                 account_privilege_details: Sequence[builtins.str],
                 table_name: builtins.str):
        """
        :param Sequence[builtins.str] account_privilege_details: 账号的表权限。取值范围（可多选）：ALTER CREATE DELETE DROP INDEX INSERT SELECT SHOW VIEW TRIGGER UPDATE CREATE VIEW REFERENCES 说明多个权限之间使用英文逗号（,）分隔。
        :param builtins.str table_name: 对账号进行权限设置的表的名称。
        """
        pulumi.set(__self__, "account_privilege_details", account_privilege_details)
        pulumi.set(__self__, "table_name", table_name)

    @property
    @pulumi.getter(name="accountPrivilegeDetails")
    def account_privilege_details(self) -> Sequence[builtins.str]:
        """
        账号的表权限。取值范围（可多选）：ALTER CREATE DELETE DROP INDEX INSERT SELECT SHOW VIEW TRIGGER UPDATE CREATE VIEW REFERENCES 说明多个权限之间使用英文逗号（,）分隔。
        """
        return pulumi.get(self, "account_privilege_details")

    @property
    @pulumi.getter(name="tableName")
    def table_name(self) -> builtins.str:
        """
        对账号进行权限设置的表的名称。
        """
        return pulumi.get(self, "table_name")


