// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.bmq.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GroupResetInfo {
    /**
     * @return This parameter is required when the reset mode is OFFSET. Specifies the reference consumption position for re-consuming. Options are: EARLIEST: The reference position is the earliest consumption point. CURRENT: The reference position is the current consumption point. LATEST: The reference position is the latest consumption point.
     * 
     */
    private @Nullable String offsetType;
    /**
     * @return Partition number.
     * 
     */
    private @Nullable Integer partitionId;
    /**
     * @return Reset mode. Options are: TIMESTAMP: Reset the consumption position based on a specific time point. Specify a past or future time, and jump directly to the position at that time to start consuming. OFFSET: Reset the consumption position based on a specified offset. Start consuming from the specified position, and you can use the offsetType parameter to specify the offset.
     * 
     */
    private @Nullable String resetBy;
    /**
     * @return Reset value. If the reset mode is TIMESTAMP, this value is the time point for re-consuming messages, for example, 1722224612000. If the reset mode is OFFSET, this value is the relative offset from the reference position specified in OffsetType, for example, 100.
     * 
     */
    private @Nullable Integer resetValue;
    /**
     * @return Topic ID。
     * 
     */
    private @Nullable String topicId;

    private GroupResetInfo() {}
    /**
     * @return This parameter is required when the reset mode is OFFSET. Specifies the reference consumption position for re-consuming. Options are: EARLIEST: The reference position is the earliest consumption point. CURRENT: The reference position is the current consumption point. LATEST: The reference position is the latest consumption point.
     * 
     */
    public Optional<String> offsetType() {
        return Optional.ofNullable(this.offsetType);
    }
    /**
     * @return Partition number.
     * 
     */
    public Optional<Integer> partitionId() {
        return Optional.ofNullable(this.partitionId);
    }
    /**
     * @return Reset mode. Options are: TIMESTAMP: Reset the consumption position based on a specific time point. Specify a past or future time, and jump directly to the position at that time to start consuming. OFFSET: Reset the consumption position based on a specified offset. Start consuming from the specified position, and you can use the offsetType parameter to specify the offset.
     * 
     */
    public Optional<String> resetBy() {
        return Optional.ofNullable(this.resetBy);
    }
    /**
     * @return Reset value. If the reset mode is TIMESTAMP, this value is the time point for re-consuming messages, for example, 1722224612000. If the reset mode is OFFSET, this value is the relative offset from the reference position specified in OffsetType, for example, 100.
     * 
     */
    public Optional<Integer> resetValue() {
        return Optional.ofNullable(this.resetValue);
    }
    /**
     * @return Topic ID。
     * 
     */
    public Optional<String> topicId() {
        return Optional.ofNullable(this.topicId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GroupResetInfo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String offsetType;
        private @Nullable Integer partitionId;
        private @Nullable String resetBy;
        private @Nullable Integer resetValue;
        private @Nullable String topicId;
        public Builder() {}
        public Builder(GroupResetInfo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.offsetType = defaults.offsetType;
    	      this.partitionId = defaults.partitionId;
    	      this.resetBy = defaults.resetBy;
    	      this.resetValue = defaults.resetValue;
    	      this.topicId = defaults.topicId;
        }

        @CustomType.Setter
        public Builder offsetType(@Nullable String offsetType) {

            this.offsetType = offsetType;
            return this;
        }
        @CustomType.Setter
        public Builder partitionId(@Nullable Integer partitionId) {

            this.partitionId = partitionId;
            return this;
        }
        @CustomType.Setter
        public Builder resetBy(@Nullable String resetBy) {

            this.resetBy = resetBy;
            return this;
        }
        @CustomType.Setter
        public Builder resetValue(@Nullable Integer resetValue) {

            this.resetValue = resetValue;
            return this;
        }
        @CustomType.Setter
        public Builder topicId(@Nullable String topicId) {

            this.topicId = topicId;
            return this;
        }
        public GroupResetInfo build() {
            final var _resultValue = new GroupResetInfo();
            _resultValue.offsetType = offsetType;
            _resultValue.partitionId = partitionId;
            _resultValue.resetBy = resetBy;
            _resultValue.resetValue = resetValue;
            _resultValue.topicId = topicId;
            return _resultValue;
        }
    }
}
