// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Rdsmysql
{
    public static class GetInstanceReadonlyNodes
    {
        /// <summary>
        /// Plural Data Source schema for Byteplus::RDSMySQL::InstanceReadonlyNode
        /// </summary>
        public static Task<GetInstanceReadonlyNodesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetInstanceReadonlyNodesResult>("bytepluscc:rdsmysql/getInstanceReadonlyNodes:getInstanceReadonlyNodes", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::RDSMySQL::InstanceReadonlyNode
        /// </summary>
        public static Output<GetInstanceReadonlyNodesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceReadonlyNodesResult>("bytepluscc:rdsmysql/getInstanceReadonlyNodes:getInstanceReadonlyNodes", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::RDSMySQL::InstanceReadonlyNode
        /// </summary>
        public static Output<GetInstanceReadonlyNodesResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceReadonlyNodesResult>("bytepluscc:rdsmysql/getInstanceReadonlyNodes:getInstanceReadonlyNodes", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetInstanceReadonlyNodesResult
    {
        /// <summary>
        /// Uniquely identifies the data source.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of Resource Identifiers.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetInstanceReadonlyNodesResult(
            string id,

            ImmutableArray<string> ids)
        {
            Id = id;
            Ids = ids;
        }
    }
}
