// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Alb
{
    public static class GetServerGroups
    {
        /// <summary>
        /// Plural Data Source schema for Byteplus::ALB::ServerGroup
        /// </summary>
        public static Task<GetServerGroupsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServerGroupsResult>("bytepluscc:alb/getServerGroups:getServerGroups", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::ALB::ServerGroup
        /// </summary>
        public static Output<GetServerGroupsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerGroupsResult>("bytepluscc:alb/getServerGroups:getServerGroups", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::ALB::ServerGroup
        /// </summary>
        public static Output<GetServerGroupsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerGroupsResult>("bytepluscc:alb/getServerGroups:getServerGroups", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetServerGroupsResult
    {
        /// <summary>
        /// Uniquely identifies the data source.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of Resource Identifiers.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetServerGroupsResult(
            string id,

            ImmutableArray<string> ids)
        {
            Id = id;
            Ids = ids;
        }
    }
}
