// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.vefaas.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class KafkaTriggerKafkaCredentials {
    /**
     * @return Kafka 认证机制。取值：PLAIN，SCRAM-SHA-256。
     * 
     */
    private @Nullable String mechanism;
    /**
     * @return 创建 Kafka 实例时设置的 SASL/PLAIN 用户密码。
     * 
     */
    private @Nullable String password;
    /**
     * @return 创建 Kafka 实例时设置的 SASL/PLAIN 用户名称。
     * 
     */
    private @Nullable String username;

    private KafkaTriggerKafkaCredentials() {}
    /**
     * @return Kafka 认证机制。取值：PLAIN，SCRAM-SHA-256。
     * 
     */
    public Optional<String> mechanism() {
        return Optional.ofNullable(this.mechanism);
    }
    /**
     * @return 创建 Kafka 实例时设置的 SASL/PLAIN 用户密码。
     * 
     */
    public Optional<String> password() {
        return Optional.ofNullable(this.password);
    }
    /**
     * @return 创建 Kafka 实例时设置的 SASL/PLAIN 用户名称。
     * 
     */
    public Optional<String> username() {
        return Optional.ofNullable(this.username);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(KafkaTriggerKafkaCredentials defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String mechanism;
        private @Nullable String password;
        private @Nullable String username;
        public Builder() {}
        public Builder(KafkaTriggerKafkaCredentials defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.mechanism = defaults.mechanism;
    	      this.password = defaults.password;
    	      this.username = defaults.username;
        }

        @CustomType.Setter
        public Builder mechanism(@Nullable String mechanism) {

            this.mechanism = mechanism;
            return this;
        }
        @CustomType.Setter
        public Builder password(@Nullable String password) {

            this.password = password;
            return this;
        }
        @CustomType.Setter
        public Builder username(@Nullable String username) {

            this.username = username;
            return this;
        }
        public KafkaTriggerKafkaCredentials build() {
            final var _resultValue = new KafkaTriggerKafkaCredentials();
            _resultValue.mechanism = mechanism;
            _resultValue.password = password;
            _resultValue.username = username;
            return _resultValue;
        }
    }
}
