// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.vepfs.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DataFlowTaskReportArgs extends com.pulumi.resources.ResourceArgs {

    public static final DataFlowTaskReportArgs Empty = new DataFlowTaskReportArgs();

    /**
     * Download link for the report.
     * 
     */
    @Import(name="path")
    private @Nullable Output<String> path;

    /**
     * @return Download link for the report.
     * 
     */
    public Optional<Output<String>> path() {
        return Optional.ofNullable(this.path);
    }

    /**
     * Report type. TotalFiles: all files; FailedFiles: failure report; SuccessFiles: success report; InventoryFiles: reconciliation report.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return Report type. TotalFiles: all files; FailedFiles: failure report; SuccessFiles: success report; InventoryFiles: reconciliation report.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private DataFlowTaskReportArgs() {}

    private DataFlowTaskReportArgs(DataFlowTaskReportArgs $) {
        this.path = $.path;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DataFlowTaskReportArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DataFlowTaskReportArgs $;

        public Builder() {
            $ = new DataFlowTaskReportArgs();
        }

        public Builder(DataFlowTaskReportArgs defaults) {
            $ = new DataFlowTaskReportArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param path Download link for the report.
         * 
         * @return builder
         * 
         */
        public Builder path(@Nullable Output<String> path) {
            $.path = path;
            return this;
        }

        /**
         * @param path Download link for the report.
         * 
         * @return builder
         * 
         */
        public Builder path(String path) {
            return path(Output.of(path));
        }

        /**
         * @param type Report type. TotalFiles: all files; FailedFiles: failure report; SuccessFiles: success report; InventoryFiles: reconciliation report.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Report type. TotalFiles: all files; FailedFiles: failure report; SuccessFiles: success report; InventoryFiles: reconciliation report.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public DataFlowTaskReportArgs build() {
            return $;
        }
    }

}
