// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.vepfs.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DataFlowTaskTlsInfoArgs extends com.pulumi.resources.ResourceArgs {

    public static final DataFlowTaskTlsInfoArgs Empty = new DataFlowTaskTlsInfoArgs();

    /**
     * Whether to enable TLS log.
     * 
     */
    @Import(name="enable")
    private @Nullable Output<Boolean> enable;

    /**
     * @return Whether to enable TLS log.
     * 
     */
    public Optional<Output<Boolean>> enable() {
        return Optional.ofNullable(this.enable);
    }

    /**
     * TLS log project ID.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return TLS log project ID.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * TLS log project name.
     * 
     */
    @Import(name="projectName")
    private @Nullable Output<String> projectName;

    /**
     * @return TLS log project name.
     * 
     */
    public Optional<Output<String>> projectName() {
        return Optional.ofNullable(this.projectName);
    }

    /**
     * Redirect URL for the TLS log project.
     * 
     */
    @Import(name="projectUrl")
    private @Nullable Output<String> projectUrl;

    /**
     * @return Redirect URL for the TLS log project.
     * 
     */
    public Optional<Output<String>> projectUrl() {
        return Optional.ofNullable(this.projectUrl);
    }

    /**
     * Embedded address of the TLS log topic.
     * 
     */
    @Import(name="topicEmbeddedUrl")
    private @Nullable Output<String> topicEmbeddedUrl;

    /**
     * @return Embedded address of the TLS log topic.
     * 
     */
    public Optional<Output<String>> topicEmbeddedUrl() {
        return Optional.ofNullable(this.topicEmbeddedUrl);
    }

    /**
     * TLS log topic ID.
     * 
     */
    @Import(name="topicId")
    private @Nullable Output<String> topicId;

    /**
     * @return TLS log topic ID.
     * 
     */
    public Optional<Output<String>> topicId() {
        return Optional.ofNullable(this.topicId);
    }

    /**
     * TLS log topic name.
     * 
     */
    @Import(name="topicName")
    private @Nullable Output<String> topicName;

    /**
     * @return TLS log topic name.
     * 
     */
    public Optional<Output<String>> topicName() {
        return Optional.ofNullable(this.topicName);
    }

    /**
     * Redirect URL for TLS log topic.
     * 
     */
    @Import(name="topicUrl")
    private @Nullable Output<String> topicUrl;

    /**
     * @return Redirect URL for TLS log topic.
     * 
     */
    public Optional<Output<String>> topicUrl() {
        return Optional.ofNullable(this.topicUrl);
    }

    private DataFlowTaskTlsInfoArgs() {}

    private DataFlowTaskTlsInfoArgs(DataFlowTaskTlsInfoArgs $) {
        this.enable = $.enable;
        this.projectId = $.projectId;
        this.projectName = $.projectName;
        this.projectUrl = $.projectUrl;
        this.topicEmbeddedUrl = $.topicEmbeddedUrl;
        this.topicId = $.topicId;
        this.topicName = $.topicName;
        this.topicUrl = $.topicUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DataFlowTaskTlsInfoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DataFlowTaskTlsInfoArgs $;

        public Builder() {
            $ = new DataFlowTaskTlsInfoArgs();
        }

        public Builder(DataFlowTaskTlsInfoArgs defaults) {
            $ = new DataFlowTaskTlsInfoArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enable Whether to enable TLS log.
         * 
         * @return builder
         * 
         */
        public Builder enable(@Nullable Output<Boolean> enable) {
            $.enable = enable;
            return this;
        }

        /**
         * @param enable Whether to enable TLS log.
         * 
         * @return builder
         * 
         */
        public Builder enable(Boolean enable) {
            return enable(Output.of(enable));
        }

        /**
         * @param projectId TLS log project ID.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId TLS log project ID.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param projectName TLS log project name.
         * 
         * @return builder
         * 
         */
        public Builder projectName(@Nullable Output<String> projectName) {
            $.projectName = projectName;
            return this;
        }

        /**
         * @param projectName TLS log project name.
         * 
         * @return builder
         * 
         */
        public Builder projectName(String projectName) {
            return projectName(Output.of(projectName));
        }

        /**
         * @param projectUrl Redirect URL for the TLS log project.
         * 
         * @return builder
         * 
         */
        public Builder projectUrl(@Nullable Output<String> projectUrl) {
            $.projectUrl = projectUrl;
            return this;
        }

        /**
         * @param projectUrl Redirect URL for the TLS log project.
         * 
         * @return builder
         * 
         */
        public Builder projectUrl(String projectUrl) {
            return projectUrl(Output.of(projectUrl));
        }

        /**
         * @param topicEmbeddedUrl Embedded address of the TLS log topic.
         * 
         * @return builder
         * 
         */
        public Builder topicEmbeddedUrl(@Nullable Output<String> topicEmbeddedUrl) {
            $.topicEmbeddedUrl = topicEmbeddedUrl;
            return this;
        }

        /**
         * @param topicEmbeddedUrl Embedded address of the TLS log topic.
         * 
         * @return builder
         * 
         */
        public Builder topicEmbeddedUrl(String topicEmbeddedUrl) {
            return topicEmbeddedUrl(Output.of(topicEmbeddedUrl));
        }

        /**
         * @param topicId TLS log topic ID.
         * 
         * @return builder
         * 
         */
        public Builder topicId(@Nullable Output<String> topicId) {
            $.topicId = topicId;
            return this;
        }

        /**
         * @param topicId TLS log topic ID.
         * 
         * @return builder
         * 
         */
        public Builder topicId(String topicId) {
            return topicId(Output.of(topicId));
        }

        /**
         * @param topicName TLS log topic name.
         * 
         * @return builder
         * 
         */
        public Builder topicName(@Nullable Output<String> topicName) {
            $.topicName = topicName;
            return this;
        }

        /**
         * @param topicName TLS log topic name.
         * 
         * @return builder
         * 
         */
        public Builder topicName(String topicName) {
            return topicName(Output.of(topicName));
        }

        /**
         * @param topicUrl Redirect URL for TLS log topic.
         * 
         * @return builder
         * 
         */
        public Builder topicUrl(@Nullable Output<String> topicUrl) {
            $.topicUrl = topicUrl;
            return this;
        }

        /**
         * @param topicUrl Redirect URL for TLS log topic.
         * 
         * @return builder
         * 
         */
        public Builder topicUrl(String topicUrl) {
            return topicUrl(Output.of(topicUrl));
        }

        public DataFlowTaskTlsInfoArgs build() {
            return $;
        }
    }

}
