// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.privatelink;

import com.byteplus.bytepluscc.Utilities;
import com.byteplus.bytepluscc.privatelink.inputs.GetEndpointServiceArgs;
import com.byteplus.bytepluscc.privatelink.inputs.GetEndpointServicePlainArgs;
import com.byteplus.bytepluscc.privatelink.outputs.GetEndpointServiceResult;
import com.byteplus.bytepluscc.privatelink.outputs.GetEndpointServicesResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.resources.InvokeArgs;
import java.util.concurrent.CompletableFuture;

public final class PrivatelinkFunctions {
    /**
     * Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static Output<GetEndpointServiceResult> getEndpointService(GetEndpointServiceArgs args) {
        return getEndpointService(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static CompletableFuture<GetEndpointServiceResult> getEndpointServicePlain(GetEndpointServicePlainArgs args) {
        return getEndpointServicePlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static Output<GetEndpointServiceResult> getEndpointService(GetEndpointServiceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatelink/getEndpointService:getEndpointService", TypeShape.of(GetEndpointServiceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static Output<GetEndpointServiceResult> getEndpointService(GetEndpointServiceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatelink/getEndpointService:getEndpointService", TypeShape.of(GetEndpointServiceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static CompletableFuture<GetEndpointServiceResult> getEndpointServicePlain(GetEndpointServicePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatelink/getEndpointService:getEndpointService", TypeShape.of(GetEndpointServiceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static Output<GetEndpointServicesResult> getEndpointServices() {
        return getEndpointServices(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static CompletableFuture<GetEndpointServicesResult> getEndpointServicesPlain() {
        return getEndpointServicesPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static Output<GetEndpointServicesResult> getEndpointServices(InvokeArgs args) {
        return getEndpointServices(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static CompletableFuture<GetEndpointServicesResult> getEndpointServicesPlain(InvokeArgs args) {
        return getEndpointServicesPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static Output<GetEndpointServicesResult> getEndpointServices(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatelink/getEndpointServices:getEndpointServices", TypeShape.of(GetEndpointServicesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static Output<GetEndpointServicesResult> getEndpointServices(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:privatelink/getEndpointServices:getEndpointServices", TypeShape.of(GetEndpointServicesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::PrivateLink::EndpointService
     * 
     */
    public static CompletableFuture<GetEndpointServicesResult> getEndpointServicesPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:privatelink/getEndpointServices:getEndpointServices", TypeShape.of(GetEndpointServicesResult.class), args, Utilities.withVersion(options));
    }
}
