// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package certificateservice

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "bytepluscc:certificateservice/childCertInstance:ChildCertInstance":
		r = &ChildCertInstance{}
	case "bytepluscc:certificateservice/organizationInfo:OrganizationInfo":
		r = &OrganizationInfo{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"bytepluscc",
		"certificateservice/childCertInstance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"bytepluscc",
		"certificateservice/organizationInfo",
		&module{version},
	)
}
