// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Transitrouter
{
    public static class GetTransitRouterAttachmentToRouteTables
    {
        /// <summary>
        /// Plural Data Source schema for Byteplus::TransitRouter::TransitRouterAttachmentToRouteTable
        /// </summary>
        public static Task<GetTransitRouterAttachmentToRouteTablesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTransitRouterAttachmentToRouteTablesResult>("bytepluscc:transitrouter/getTransitRouterAttachmentToRouteTables:getTransitRouterAttachmentToRouteTables", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::TransitRouter::TransitRouterAttachmentToRouteTable
        /// </summary>
        public static Output<GetTransitRouterAttachmentToRouteTablesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTransitRouterAttachmentToRouteTablesResult>("bytepluscc:transitrouter/getTransitRouterAttachmentToRouteTables:getTransitRouterAttachmentToRouteTables", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::TransitRouter::TransitRouterAttachmentToRouteTable
        /// </summary>
        public static Output<GetTransitRouterAttachmentToRouteTablesResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTransitRouterAttachmentToRouteTablesResult>("bytepluscc:transitrouter/getTransitRouterAttachmentToRouteTables:getTransitRouterAttachmentToRouteTables", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetTransitRouterAttachmentToRouteTablesResult
    {
        /// <summary>
        /// Uniquely identifies the data source.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of Resource Identifiers.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetTransitRouterAttachmentToRouteTablesResult(
            string id,

            ImmutableArray<string> ids)
        {
            Id = id;
            Ids = ids;
        }
    }
}
