// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Plural Data Source schema for Byteplus::Redis::ParameterGroup
 */
export function getParameterGroups(opts?: pulumi.InvokeOptions): Promise<GetParameterGroupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytepluscc:redis/getParameterGroups:getParameterGroups", {
    }, opts);
}

/**
 * A collection of values returned by getParameterGroups.
 */
export interface GetParameterGroupsResult {
    /**
     * Uniquely identifies the data source.
     */
    readonly id: string;
    /**
     * Set of Resource Identifiers.
     */
    readonly ids: string[];
}
/**
 * Plural Data Source schema for Byteplus::Redis::ParameterGroup
 */
export function getParameterGroupsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetParameterGroupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytepluscc:redis/getParameterGroups:getParameterGroups", {
    }, opts);
}
