// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.vpc.inputs;

import com.byteplus.bytepluscc.vpc.inputs.IpamScopeTagArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IpamScopeState extends com.pulumi.resources.ResourceArgs {

    public static final IpamScopeState Empty = new IpamScopeState();

    /**
     * Account ID
     * 
     */
    @Import(name="accountId")
    private @Nullable Output<String> accountId;

    /**
     * @return Account ID
     * 
     */
    public Optional<Output<String>> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    /**
     * IPAM Scope Creation Time
     * 
     */
    @Import(name="createTime")
    private @Nullable Output<String> createTime;

    /**
     * @return IPAM Scope Creation Time
     * 
     */
    public Optional<Output<String>> createTime() {
        return Optional.ofNullable(this.createTime);
    }

    /**
     * IPAM Scope Description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return IPAM Scope Description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * IPAM ID。
     * 
     */
    @Import(name="ipamId")
    private @Nullable Output<String> ipamId;

    /**
     * @return IPAM ID。
     * 
     */
    public Optional<Output<String>> ipamId() {
        return Optional.ofNullable(this.ipamId);
    }

    /**
     * IPAM Region ID
     * 
     */
    @Import(name="ipamRegionId")
    private @Nullable Output<String> ipamRegionId;

    /**
     * @return IPAM Region ID
     * 
     */
    public Optional<Output<String>> ipamRegionId() {
        return Optional.ofNullable(this.ipamRegionId);
    }

    /**
     * IPAM Scope ID
     * 
     */
    @Import(name="ipamScopeId")
    private @Nullable Output<String> ipamScopeId;

    /**
     * @return IPAM Scope ID
     * 
     */
    public Optional<Output<String>> ipamScopeId() {
        return Optional.ofNullable(this.ipamScopeId);
    }

    /**
     * IPAM Scope Name
     * 
     */
    @Import(name="ipamScopeName")
    private @Nullable Output<String> ipamScopeName;

    /**
     * @return IPAM Scope Name
     * 
     */
    public Optional<Output<String>> ipamScopeName() {
        return Optional.ofNullable(this.ipamScopeName);
    }

    /**
     * IPAM Scope Type
     * 
     */
    @Import(name="ipamScopeType")
    private @Nullable Output<String> ipamScopeType;

    /**
     * @return IPAM Scope Type
     * 
     */
    public Optional<Output<String>> ipamScopeType() {
        return Optional.ofNullable(this.ipamScopeType);
    }

    /**
     * Default Scope
     * 
     */
    @Import(name="isDefault")
    private @Nullable Output<Boolean> isDefault;

    /**
     * @return Default Scope
     * 
     */
    public Optional<Output<Boolean>> isDefault() {
        return Optional.ofNullable(this.isDefault);
    }

    /**
     * Number of Address Pools
     * 
     */
    @Import(name="poolCount")
    private @Nullable Output<Integer> poolCount;

    /**
     * @return Number of Address Pools
     * 
     */
    public Optional<Output<Integer>> poolCount() {
        return Optional.ofNullable(this.poolCount);
    }

    /**
     * Project Name
     * 
     */
    @Import(name="projectName")
    private @Nullable Output<String> projectName;

    /**
     * @return Project Name
     * 
     */
    public Optional<Output<String>> projectName() {
        return Optional.ofNullable(this.projectName);
    }

    /**
     * IPAM Scope Status
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return IPAM Scope Status
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * IPAM Scope Tags
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<List<IpamScopeTagArgs>> tags;

    /**
     * @return IPAM Scope Tags
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    public Optional<Output<List<IpamScopeTagArgs>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    /**
     * IPAM Scope Update Time
     * 
     */
    @Import(name="updateTime")
    private @Nullable Output<String> updateTime;

    /**
     * @return IPAM Scope Update Time
     * 
     */
    public Optional<Output<String>> updateTime() {
        return Optional.ofNullable(this.updateTime);
    }

    private IpamScopeState() {}

    private IpamScopeState(IpamScopeState $) {
        this.accountId = $.accountId;
        this.createTime = $.createTime;
        this.description = $.description;
        this.ipamId = $.ipamId;
        this.ipamRegionId = $.ipamRegionId;
        this.ipamScopeId = $.ipamScopeId;
        this.ipamScopeName = $.ipamScopeName;
        this.ipamScopeType = $.ipamScopeType;
        this.isDefault = $.isDefault;
        this.poolCount = $.poolCount;
        this.projectName = $.projectName;
        this.status = $.status;
        this.tags = $.tags;
        this.updateTime = $.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IpamScopeState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IpamScopeState $;

        public Builder() {
            $ = new IpamScopeState();
        }

        public Builder(IpamScopeState defaults) {
            $ = new IpamScopeState(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Account ID
         * 
         * @return builder
         * 
         */
        public Builder accountId(@Nullable Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Account ID
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        /**
         * @param createTime IPAM Scope Creation Time
         * 
         * @return builder
         * 
         */
        public Builder createTime(@Nullable Output<String> createTime) {
            $.createTime = createTime;
            return this;
        }

        /**
         * @param createTime IPAM Scope Creation Time
         * 
         * @return builder
         * 
         */
        public Builder createTime(String createTime) {
            return createTime(Output.of(createTime));
        }

        /**
         * @param description IPAM Scope Description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description IPAM Scope Description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param ipamId IPAM ID。
         * 
         * @return builder
         * 
         */
        public Builder ipamId(@Nullable Output<String> ipamId) {
            $.ipamId = ipamId;
            return this;
        }

        /**
         * @param ipamId IPAM ID。
         * 
         * @return builder
         * 
         */
        public Builder ipamId(String ipamId) {
            return ipamId(Output.of(ipamId));
        }

        /**
         * @param ipamRegionId IPAM Region ID
         * 
         * @return builder
         * 
         */
        public Builder ipamRegionId(@Nullable Output<String> ipamRegionId) {
            $.ipamRegionId = ipamRegionId;
            return this;
        }

        /**
         * @param ipamRegionId IPAM Region ID
         * 
         * @return builder
         * 
         */
        public Builder ipamRegionId(String ipamRegionId) {
            return ipamRegionId(Output.of(ipamRegionId));
        }

        /**
         * @param ipamScopeId IPAM Scope ID
         * 
         * @return builder
         * 
         */
        public Builder ipamScopeId(@Nullable Output<String> ipamScopeId) {
            $.ipamScopeId = ipamScopeId;
            return this;
        }

        /**
         * @param ipamScopeId IPAM Scope ID
         * 
         * @return builder
         * 
         */
        public Builder ipamScopeId(String ipamScopeId) {
            return ipamScopeId(Output.of(ipamScopeId));
        }

        /**
         * @param ipamScopeName IPAM Scope Name
         * 
         * @return builder
         * 
         */
        public Builder ipamScopeName(@Nullable Output<String> ipamScopeName) {
            $.ipamScopeName = ipamScopeName;
            return this;
        }

        /**
         * @param ipamScopeName IPAM Scope Name
         * 
         * @return builder
         * 
         */
        public Builder ipamScopeName(String ipamScopeName) {
            return ipamScopeName(Output.of(ipamScopeName));
        }

        /**
         * @param ipamScopeType IPAM Scope Type
         * 
         * @return builder
         * 
         */
        public Builder ipamScopeType(@Nullable Output<String> ipamScopeType) {
            $.ipamScopeType = ipamScopeType;
            return this;
        }

        /**
         * @param ipamScopeType IPAM Scope Type
         * 
         * @return builder
         * 
         */
        public Builder ipamScopeType(String ipamScopeType) {
            return ipamScopeType(Output.of(ipamScopeType));
        }

        /**
         * @param isDefault Default Scope
         * 
         * @return builder
         * 
         */
        public Builder isDefault(@Nullable Output<Boolean> isDefault) {
            $.isDefault = isDefault;
            return this;
        }

        /**
         * @param isDefault Default Scope
         * 
         * @return builder
         * 
         */
        public Builder isDefault(Boolean isDefault) {
            return isDefault(Output.of(isDefault));
        }

        /**
         * @param poolCount Number of Address Pools
         * 
         * @return builder
         * 
         */
        public Builder poolCount(@Nullable Output<Integer> poolCount) {
            $.poolCount = poolCount;
            return this;
        }

        /**
         * @param poolCount Number of Address Pools
         * 
         * @return builder
         * 
         */
        public Builder poolCount(Integer poolCount) {
            return poolCount(Output.of(poolCount));
        }

        /**
         * @param projectName Project Name
         * 
         * @return builder
         * 
         */
        public Builder projectName(@Nullable Output<String> projectName) {
            $.projectName = projectName;
            return this;
        }

        /**
         * @param projectName Project Name
         * 
         * @return builder
         * 
         */
        public Builder projectName(String projectName) {
            return projectName(Output.of(projectName));
        }

        /**
         * @param status IPAM Scope Status
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status IPAM Scope Status
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        /**
         * @param tags IPAM Scope Tags
         * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<List<IpamScopeTagArgs>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags IPAM Scope Tags
         * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
         * 
         * @return builder
         * 
         */
        public Builder tags(List<IpamScopeTagArgs> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags IPAM Scope Tags
         * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
         * 
         * @return builder
         * 
         */
        public Builder tags(IpamScopeTagArgs... tags) {
            return tags(List.of(tags));
        }

        /**
         * @param updateTime IPAM Scope Update Time
         * 
         * @return builder
         * 
         */
        public Builder updateTime(@Nullable Output<String> updateTime) {
            $.updateTime = updateTime;
            return this;
        }

        /**
         * @param updateTime IPAM Scope Update Time
         * 
         * @return builder
         * 
         */
        public Builder updateTime(String updateTime) {
            return updateTime(Output.of(updateTime));
        }

        public IpamScopeState build() {
            return $;
        }
    }

}
