// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Redis
{
    /// <summary>
    /// Volcengine Redis expired key scan/cleanup task (KeyScanJob). Refers to a one-time expired key scan and cleanup job initiated for the target Redis instance. You can create, query, or cancel (interrupt) the job. The task is one-time and does not support updates. Finished/Failed/Interrupted are terminal states; canceled and failed tasks are considered nonexistent resources when queried.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Bytepluscc = Byteplus.Pulumi.Bytepluscc;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Bytepluscc.Redis.KeyScanJob("example", new()
    ///     {
    ///         InstanceId = "redis-xxxx",
    ///         ScanKeyNumPerSecond = 3000,
    ///         TimeoutMinutes = 60,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import bytepluscc:redis/keyScanJob:KeyScanJob example "instance_id|job_id"
    /// ```
    /// </summary>
    [ByteplusccResourceType("bytepluscc:redis/keyScanJob:KeyScanJob")]
    public partial class KeyScanJob : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Number of shards analyzed.
        /// </summary>
        [Output("completedCount")]
        public Output<int> CompletedCount { get; private set; } = null!;

        /// <summary>
        /// Task creation time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
        /// </summary>
        [Output("createTime")]
        public Output<string> CreateTime { get; private set; } = null!;

        /// <summary>
        /// Task end time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
        /// </summary>
        [Output("finishTime")]
        public Output<string> FinishTime { get; private set; } = null!;

        /// <summary>
        /// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
        /// </summary>
        [Output("instanceId")]
        public Output<string> InstanceId { get; private set; } = null!;

        /// <summary>
        /// Task ID of the scan job.
        /// </summary>
        [Output("jobId")]
        public Output<string> JobId { get; private set; } = null!;

        /// <summary>
        /// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
        /// </summary>
        [Output("scanKeyNumPerSecond")]
        public Output<int> ScanKeyNumPerSecond { get; private set; } = null!;

        /// <summary>
        /// Task start time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
        /// </summary>
        [Output("startTime")]
        public Output<string> StartTime { get; private set; } = null!;

        /// <summary>
        /// Task status. Values: Created, Running, Finished, Failed, Interrupted.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
        /// </summary>
        [Output("timeoutMinutes")]
        public Output<int> TimeoutMinutes { get; private set; } = null!;

        /// <summary>
        /// Total number of shards to analyze.
        /// </summary>
        [Output("totalCount")]
        public Output<int> TotalCount { get; private set; } = null!;


        /// <summary>
        /// Create a KeyScanJob resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public KeyScanJob(string name, KeyScanJobArgs args, CustomResourceOptions? options = null)
            : base("bytepluscc:redis/keyScanJob:KeyScanJob", name, args ?? new KeyScanJobArgs(), MakeResourceOptions(options, ""))
        {
        }

        private KeyScanJob(string name, Input<string> id, KeyScanJobState? state = null, CustomResourceOptions? options = null)
            : base("bytepluscc:redis/keyScanJob:KeyScanJob", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/byteplus-sdk",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing KeyScanJob resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static KeyScanJob Get(string name, Input<string> id, KeyScanJobState? state = null, CustomResourceOptions? options = null)
        {
            return new KeyScanJob(name, id, state, options);
        }
    }

    public sealed class KeyScanJobArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        /// <summary>
        /// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
        /// </summary>
        [Input("scanKeyNumPerSecond", required: true)]
        public Input<int> ScanKeyNumPerSecond { get; set; } = null!;

        /// <summary>
        /// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
        /// </summary>
        [Input("timeoutMinutes", required: true)]
        public Input<int> TimeoutMinutes { get; set; } = null!;

        public KeyScanJobArgs()
        {
        }
        public static new KeyScanJobArgs Empty => new KeyScanJobArgs();
    }

    public sealed class KeyScanJobState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of shards analyzed.
        /// </summary>
        [Input("completedCount")]
        public Input<int>? CompletedCount { get; set; }

        /// <summary>
        /// Task creation time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
        /// </summary>
        [Input("createTime")]
        public Input<string>? CreateTime { get; set; }

        /// <summary>
        /// Task end time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
        /// </summary>
        [Input("finishTime")]
        public Input<string>? FinishTime { get; set; }

        /// <summary>
        /// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
        /// </summary>
        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        /// <summary>
        /// Task ID of the scan job.
        /// </summary>
        [Input("jobId")]
        public Input<string>? JobId { get; set; }

        /// <summary>
        /// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
        /// </summary>
        [Input("scanKeyNumPerSecond")]
        public Input<int>? ScanKeyNumPerSecond { get; set; }

        /// <summary>
        /// Task start time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
        /// </summary>
        [Input("startTime")]
        public Input<string>? StartTime { get; set; }

        /// <summary>
        /// Task status. Values: Created, Running, Finished, Failed, Interrupted.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
        /// </summary>
        [Input("timeoutMinutes")]
        public Input<int>? TimeoutMinutes { get; set; }

        /// <summary>
        /// Total number of shards to analyze.
        /// </summary>
        [Input("totalCount")]
        public Input<int>? TotalCount { get; set; }

        public KeyScanJobState()
        {
        }
        public static new KeyScanJobState Empty => new KeyScanJobState();
    }
}
