// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.iam;

import com.byteplus.bytepluscc.Utilities;
import com.byteplus.bytepluscc.iam.ApiKeyArgs;
import com.byteplus.bytepluscc.iam.inputs.ApiKeyState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * IAM API Key。
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.byteplus.bytepluscc.iam.ApiKey;
 * import com.byteplus.bytepluscc.iam.ApiKeyArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new ApiKey("example", ApiKeyArgs.builder()
 *             .userName("user-xxxx")
 *             .name("ccapi-apikey-full")
 *             .permissionsBoundary("{\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"iam:*\"],\"Resource\":[\"*\"]}]}")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import bytepluscc:iam/apiKey:ApiKey example &#34;user_name|api_key_id&#34;
 * ```
 * 
 */
@ResourceType(type="bytepluscc:iam/apiKey:ApiKey")
public class ApiKey extends com.pulumi.resources.CustomResource {
    /**
     * API Key ID。
     * 
     */
    @Export(name="apiKeyId", refs={String.class}, tree="[0]")
    private Output<String> apiKeyId;

    /**
     * @return API Key ID。
     * 
     */
    public Output<String> apiKeyId() {
        return this.apiKeyId;
    }
    /**
     * Created At
     * 
     */
    @Export(name="createDate", refs={String.class}, tree="[0]")
    private Output<String> createDate;

    /**
     * @return Created At
     * 
     */
    public Output<String> createDate() {
        return this.createDate;
    }
    /**
     * API Key Name
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return API Key Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Permission Boundary
     * 
     */
    @Export(name="permissionsBoundary", refs={String.class}, tree="[0]")
    private Output<String> permissionsBoundary;

    /**
     * @return Permission Boundary
     * 
     */
    public Output<String> permissionsBoundary() {
        return this.permissionsBoundary;
    }
    /**
     * API Key Secret
     * 
     */
    @Export(name="secret", refs={String.class}, tree="[0]")
    private Output<String> secret;

    /**
     * @return API Key Secret
     * 
     */
    public Output<String> secret() {
        return this.secret;
    }
    /**
     * API Key Status
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return API Key Status
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Last Updated
     * 
     */
    @Export(name="updateDate", refs={String.class}, tree="[0]")
    private Output<String> updateDate;

    /**
     * @return Last Updated
     * 
     */
    public Output<String> updateDate() {
        return this.updateDate;
    }
    /**
     * Username
     * 
     */
    @Export(name="userName", refs={String.class}, tree="[0]")
    private Output<String> userName;

    /**
     * @return Username
     * 
     */
    public Output<String> userName() {
        return this.userName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ApiKey(java.lang.String name) {
        this(name, ApiKeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ApiKey(java.lang.String name, ApiKeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ApiKey(java.lang.String name, ApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:iam/apiKey:ApiKey", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ApiKey(java.lang.String name, Output<java.lang.String> id, @Nullable ApiKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:iam/apiKey:ApiKey", name, state, makeResourceOptions(options, id), false);
    }

    private static ApiKeyArgs makeArgs(ApiKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ApiKeyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/byteplus-sdk")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ApiKey get(java.lang.String name, Output<java.lang.String> id, @Nullable ApiKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ApiKey(name, id, state, options);
    }
}
