// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redis

import (
	"context"
	"reflect"

	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Plural Data Source schema for Byteplus::Redis::KeyScanJob
func GetKeyScanJobs(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetKeyScanJobsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetKeyScanJobsResult
	err := ctx.Invoke("bytepluscc:redis/getKeyScanJobs:getKeyScanJobs", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getKeyScanJobs.
type GetKeyScanJobsResult struct {
	// Uniquely identifies the data source.
	Id string `pulumi:"id"`
	// Set of Resource Identifiers.
	Ids []string `pulumi:"ids"`
}

func GetKeyScanJobsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetKeyScanJobsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetKeyScanJobsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("bytepluscc:redis/getKeyScanJobs:getKeyScanJobs", nil, GetKeyScanJobsResultOutput{}, options).(GetKeyScanJobsResultOutput), nil
	}).(GetKeyScanJobsResultOutput)
}

// A collection of values returned by getKeyScanJobs.
type GetKeyScanJobsResultOutput struct{ *pulumi.OutputState }

func (GetKeyScanJobsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetKeyScanJobsResult)(nil)).Elem()
}

func (o GetKeyScanJobsResultOutput) ToGetKeyScanJobsResultOutput() GetKeyScanJobsResultOutput {
	return o
}

func (o GetKeyScanJobsResultOutput) ToGetKeyScanJobsResultOutputWithContext(ctx context.Context) GetKeyScanJobsResultOutput {
	return o
}

// Uniquely identifies the data source.
func (o GetKeyScanJobsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetKeyScanJobsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Set of Resource Identifiers.
func (o GetKeyScanJobsResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetKeyScanJobsResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetKeyScanJobsResultOutput{})
}
