// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redis

import (
	"context"
	"reflect"

	"errors"
	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Volcengine Redis expired key scan/cleanup task (KeyScanJob). Refers to a one-time expired key scan and cleanup job initiated for the target Redis instance. You can create, query, or cancel (interrupt) the job. The task is one-time and does not support updates. Finished/Failed/Interrupted are terminal states; canceled and failed tasks are considered nonexistent resources when queried.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/redis"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := redis.NewKeyScanJob(ctx, "example", &redis.KeyScanJobArgs{
//				InstanceId:          pulumi.String("redis-xxxx"),
//				ScanKeyNumPerSecond: pulumi.Int(3000),
//				TimeoutMinutes:      pulumi.Int(60),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import bytepluscc:redis/keyScanJob:KeyScanJob example "instance_id|job_id"
// ```
type KeyScanJob struct {
	pulumi.CustomResourceState

	// Number of shards analyzed.
	CompletedCount pulumi.IntOutput `pulumi:"completedCount"`
	// Task creation time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	CreateTime pulumi.StringOutput `pulumi:"createTime"`
	// Task end time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	FinishTime pulumi.StringOutput `pulumi:"finishTime"`
	// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
	InstanceId pulumi.StringOutput `pulumi:"instanceId"`
	// Task ID of the scan job.
	JobId pulumi.StringOutput `pulumi:"jobId"`
	// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
	ScanKeyNumPerSecond pulumi.IntOutput `pulumi:"scanKeyNumPerSecond"`
	// Task start time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	StartTime pulumi.StringOutput `pulumi:"startTime"`
	// Task status. Values: Created, Running, Finished, Failed, Interrupted.
	Status pulumi.StringOutput `pulumi:"status"`
	// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
	TimeoutMinutes pulumi.IntOutput `pulumi:"timeoutMinutes"`
	// Total number of shards to analyze.
	TotalCount pulumi.IntOutput `pulumi:"totalCount"`
}

// NewKeyScanJob registers a new resource with the given unique name, arguments, and options.
func NewKeyScanJob(ctx *pulumi.Context,
	name string, args *KeyScanJobArgs, opts ...pulumi.ResourceOption) (*KeyScanJob, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.InstanceId == nil {
		return nil, errors.New("invalid value for required argument 'InstanceId'")
	}
	if args.ScanKeyNumPerSecond == nil {
		return nil, errors.New("invalid value for required argument 'ScanKeyNumPerSecond'")
	}
	if args.TimeoutMinutes == nil {
		return nil, errors.New("invalid value for required argument 'TimeoutMinutes'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource KeyScanJob
	err := ctx.RegisterResource("bytepluscc:redis/keyScanJob:KeyScanJob", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKeyScanJob gets an existing KeyScanJob resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKeyScanJob(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KeyScanJobState, opts ...pulumi.ResourceOption) (*KeyScanJob, error) {
	var resource KeyScanJob
	err := ctx.ReadResource("bytepluscc:redis/keyScanJob:KeyScanJob", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering KeyScanJob resources.
type keyScanJobState struct {
	// Number of shards analyzed.
	CompletedCount *int `pulumi:"completedCount"`
	// Task creation time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	CreateTime *string `pulumi:"createTime"`
	// Task end time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	FinishTime *string `pulumi:"finishTime"`
	// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
	InstanceId *string `pulumi:"instanceId"`
	// Task ID of the scan job.
	JobId *string `pulumi:"jobId"`
	// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
	ScanKeyNumPerSecond *int `pulumi:"scanKeyNumPerSecond"`
	// Task start time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	StartTime *string `pulumi:"startTime"`
	// Task status. Values: Created, Running, Finished, Failed, Interrupted.
	Status *string `pulumi:"status"`
	// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
	TimeoutMinutes *int `pulumi:"timeoutMinutes"`
	// Total number of shards to analyze.
	TotalCount *int `pulumi:"totalCount"`
}

type KeyScanJobState struct {
	// Number of shards analyzed.
	CompletedCount pulumi.IntPtrInput
	// Task creation time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	CreateTime pulumi.StringPtrInput
	// Task end time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	FinishTime pulumi.StringPtrInput
	// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
	InstanceId pulumi.StringPtrInput
	// Task ID of the scan job.
	JobId pulumi.StringPtrInput
	// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
	ScanKeyNumPerSecond pulumi.IntPtrInput
	// Task start time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
	StartTime pulumi.StringPtrInput
	// Task status. Values: Created, Running, Finished, Failed, Interrupted.
	Status pulumi.StringPtrInput
	// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
	TimeoutMinutes pulumi.IntPtrInput
	// Total number of shards to analyze.
	TotalCount pulumi.IntPtrInput
}

func (KeyScanJobState) ElementType() reflect.Type {
	return reflect.TypeOf((*keyScanJobState)(nil)).Elem()
}

type keyScanJobArgs struct {
	// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
	InstanceId string `pulumi:"instanceId"`
	// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
	ScanKeyNumPerSecond int `pulumi:"scanKeyNumPerSecond"`
	// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
	TimeoutMinutes int `pulumi:"timeoutMinutes"`
}

// The set of arguments for constructing a KeyScanJob resource.
type KeyScanJobArgs struct {
	// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
	InstanceId pulumi.StringInput
	// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
	ScanKeyNumPerSecond pulumi.IntInput
	// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
	TimeoutMinutes pulumi.IntInput
}

func (KeyScanJobArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*keyScanJobArgs)(nil)).Elem()
}

type KeyScanJobInput interface {
	pulumi.Input

	ToKeyScanJobOutput() KeyScanJobOutput
	ToKeyScanJobOutputWithContext(ctx context.Context) KeyScanJobOutput
}

func (*KeyScanJob) ElementType() reflect.Type {
	return reflect.TypeOf((**KeyScanJob)(nil)).Elem()
}

func (i *KeyScanJob) ToKeyScanJobOutput() KeyScanJobOutput {
	return i.ToKeyScanJobOutputWithContext(context.Background())
}

func (i *KeyScanJob) ToKeyScanJobOutputWithContext(ctx context.Context) KeyScanJobOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyScanJobOutput)
}

// KeyScanJobArrayInput is an input type that accepts KeyScanJobArray and KeyScanJobArrayOutput values.
// You can construct a concrete instance of `KeyScanJobArrayInput` via:
//
//	KeyScanJobArray{ KeyScanJobArgs{...} }
type KeyScanJobArrayInput interface {
	pulumi.Input

	ToKeyScanJobArrayOutput() KeyScanJobArrayOutput
	ToKeyScanJobArrayOutputWithContext(context.Context) KeyScanJobArrayOutput
}

type KeyScanJobArray []KeyScanJobInput

func (KeyScanJobArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KeyScanJob)(nil)).Elem()
}

func (i KeyScanJobArray) ToKeyScanJobArrayOutput() KeyScanJobArrayOutput {
	return i.ToKeyScanJobArrayOutputWithContext(context.Background())
}

func (i KeyScanJobArray) ToKeyScanJobArrayOutputWithContext(ctx context.Context) KeyScanJobArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyScanJobArrayOutput)
}

// KeyScanJobMapInput is an input type that accepts KeyScanJobMap and KeyScanJobMapOutput values.
// You can construct a concrete instance of `KeyScanJobMapInput` via:
//
//	KeyScanJobMap{ "key": KeyScanJobArgs{...} }
type KeyScanJobMapInput interface {
	pulumi.Input

	ToKeyScanJobMapOutput() KeyScanJobMapOutput
	ToKeyScanJobMapOutputWithContext(context.Context) KeyScanJobMapOutput
}

type KeyScanJobMap map[string]KeyScanJobInput

func (KeyScanJobMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KeyScanJob)(nil)).Elem()
}

func (i KeyScanJobMap) ToKeyScanJobMapOutput() KeyScanJobMapOutput {
	return i.ToKeyScanJobMapOutputWithContext(context.Background())
}

func (i KeyScanJobMap) ToKeyScanJobMapOutputWithContext(ctx context.Context) KeyScanJobMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyScanJobMapOutput)
}

type KeyScanJobOutput struct{ *pulumi.OutputState }

func (KeyScanJobOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KeyScanJob)(nil)).Elem()
}

func (o KeyScanJobOutput) ToKeyScanJobOutput() KeyScanJobOutput {
	return o
}

func (o KeyScanJobOutput) ToKeyScanJobOutputWithContext(ctx context.Context) KeyScanJobOutput {
	return o
}

// Number of shards analyzed.
func (o KeyScanJobOutput) CompletedCount() pulumi.IntOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.IntOutput { return v.CompletedCount }).(pulumi.IntOutput)
}

// Task creation time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
func (o KeyScanJobOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.StringOutput { return v.CreateTime }).(pulumi.StringOutput)
}

// Task end time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
func (o KeyScanJobOutput) FinishTime() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.StringOutput { return v.FinishTime }).(pulumi.StringOutput)
}

// Instance ID. You can call the DescribeDBInstances API to query basic information for all Redis instances in the target region, including the instance ID.
func (o KeyScanJobOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.StringOutput { return v.InstanceId }).(pulumi.StringOutput)
}

// Task ID of the scan job.
func (o KeyScanJobOutput) JobId() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.StringOutput { return v.JobId }).(pulumi.StringOutput)
}

// Number of expired keys scanned per second. Value range: integer between 2000 and 100000.
func (o KeyScanJobOutput) ScanKeyNumPerSecond() pulumi.IntOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.IntOutput { return v.ScanKeyNumPerSecond }).(pulumi.IntOutput)
}

// Task start time. Format: yyyy-MM-ddTHH:mm:ssZ (UTC).
func (o KeyScanJobOutput) StartTime() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.StringOutput { return v.StartTime }).(pulumi.StringOutput)
}

// Task status. Values: Created, Running, Finished, Failed, Interrupted.
func (o KeyScanJobOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Scan timeout. Value range: integer between 30 and 1440, unit: minutes.
func (o KeyScanJobOutput) TimeoutMinutes() pulumi.IntOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.IntOutput { return v.TimeoutMinutes }).(pulumi.IntOutput)
}

// Total number of shards to analyze.
func (o KeyScanJobOutput) TotalCount() pulumi.IntOutput {
	return o.ApplyT(func(v *KeyScanJob) pulumi.IntOutput { return v.TotalCount }).(pulumi.IntOutput)
}

type KeyScanJobArrayOutput struct{ *pulumi.OutputState }

func (KeyScanJobArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KeyScanJob)(nil)).Elem()
}

func (o KeyScanJobArrayOutput) ToKeyScanJobArrayOutput() KeyScanJobArrayOutput {
	return o
}

func (o KeyScanJobArrayOutput) ToKeyScanJobArrayOutputWithContext(ctx context.Context) KeyScanJobArrayOutput {
	return o
}

func (o KeyScanJobArrayOutput) Index(i pulumi.IntInput) KeyScanJobOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *KeyScanJob {
		return vs[0].([]*KeyScanJob)[vs[1].(int)]
	}).(KeyScanJobOutput)
}

type KeyScanJobMapOutput struct{ *pulumi.OutputState }

func (KeyScanJobMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KeyScanJob)(nil)).Elem()
}

func (o KeyScanJobMapOutput) ToKeyScanJobMapOutput() KeyScanJobMapOutput {
	return o
}

func (o KeyScanJobMapOutput) ToKeyScanJobMapOutputWithContext(ctx context.Context) KeyScanJobMapOutput {
	return o
}

func (o KeyScanJobMapOutput) MapIndex(k pulumi.StringInput) KeyScanJobOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *KeyScanJob {
		return vs[0].(map[string]*KeyScanJob)[vs[1].(string)]
	}).(KeyScanJobOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KeyScanJobInput)(nil)).Elem(), &KeyScanJob{})
	pulumi.RegisterInputType(reflect.TypeOf((*KeyScanJobArrayInput)(nil)).Elem(), KeyScanJobArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KeyScanJobMapInput)(nil)).Elem(), KeyScanJobMap{})
	pulumi.RegisterOutputType(KeyScanJobOutput{})
	pulumi.RegisterOutputType(KeyScanJobArrayOutput{})
	pulumi.RegisterOutputType(KeyScanJobMapOutput{})
}
