// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.waf;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class IpGroupArgs extends com.pulumi.resources.ResourceArgs {

    public static final IpGroupArgs Empty = new IpGroupArgs();

    /**
     * IP Address or Address Range List
     * 
     */
    @Import(name="ipLists", required=true)
    private Output<List<String>> ipLists;

    /**
     * @return IP Address or Address Range List
     * 
     */
    public Output<List<String>> ipLists() {
        return this.ipLists;
    }

    /**
     * IP Address Group Name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return IP Address Group Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private IpGroupArgs() {}

    private IpGroupArgs(IpGroupArgs $) {
        this.ipLists = $.ipLists;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IpGroupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IpGroupArgs $;

        public Builder() {
            $ = new IpGroupArgs();
        }

        public Builder(IpGroupArgs defaults) {
            $ = new IpGroupArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ipLists IP Address or Address Range List
         * 
         * @return builder
         * 
         */
        public Builder ipLists(Output<List<String>> ipLists) {
            $.ipLists = ipLists;
            return this;
        }

        /**
         * @param ipLists IP Address or Address Range List
         * 
         * @return builder
         * 
         */
        public Builder ipLists(List<String> ipLists) {
            return ipLists(Output.of(ipLists));
        }

        /**
         * @param ipLists IP Address or Address Range List
         * 
         * @return builder
         * 
         */
        public Builder ipLists(String... ipLists) {
            return ipLists(List.of(ipLists));
        }

        /**
         * @param name IP Address Group Name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name IP Address Group Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public IpGroupArgs build() {
            if ($.ipLists == null) {
                throw new MissingRequiredPropertyException("IpGroupArgs", "ipLists");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("IpGroupArgs", "name");
            }
            return $;
        }
    }

}
