// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.waf;

import com.byteplus.bytepluscc.Utilities;
import com.byteplus.bytepluscc.waf.SystemBotArgs;
import com.byteplus.bytepluscc.waf.inputs.SystemBotState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Volcengine WAF system Bot rule configuration. System Bot rules are built-in bot detection rules in WAF, categorized by BotType. Each category contains several independently configurable sub-rules (SubRule), each uniquely identified by a RuleTag. Use UpdateSystemBotConfig to set the action and switch for a sub-rule (RuleTag) under a specified domain (Host) (Enable=1 means enabled and considered created, Enable=0 means disabled and considered deleted), and use ListSystemBotConfig to query the current configuration of each sub-rule. Resource granularity is &#39;domain name + sub-rule tag&#39;.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.byteplus.bytepluscc.waf.SystemBot;
 * import com.byteplus.bytepluscc.waf.SystemBotArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new SystemBot("example", SystemBotArgs.builder()
 *             .host("www.testwaf.com")
 *             .ruleTag("J000000000025")
 *             .botType("search_engine_bot")
 *             .action("js")
 *             .projectName("default")
 *             .verificationExemptionTime(300)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import bytepluscc:waf/systemBot:SystemBot example &#34;host|rule_tag&#34;
 * ```
 * 
 */
@ResourceType(type="bytepluscc:waf/systemBot:SystemBot")
public class SystemBot extends com.pulumi.resources.CustomResource {
    /**
     * Action taken when this sub-rule is triggered. Values: observe, block, etc.
     * 
     */
    @Export(name="action", refs={String.class}, tree="[0]")
    private Output<String> action;

    /**
     * @return Action taken when this sub-rule is triggered. Values: observe, block, etc.
     * 
     */
    public Output<String> action() {
        return this.action;
    }
    /**
     * Category of the system Bot rule, such as&lt;span pulumi-lang-nodejs=&#34; llmCrawlerBot &#34; pulumi-lang-dotnet=&#34; LlmCrawlerBot &#34; pulumi-lang-go=&#34; llmCrawlerBot &#34; pulumi-lang-python=&#34; llm_crawler_bot &#34; pulumi-lang-yaml=&#34; llmCrawlerBot &#34; pulumi-lang-java=&#34; llmCrawlerBot &#34; pulumi-lang-hcl=&#34; llm_crawler_bot &#34;&gt; llmCrawlerBot &lt;/span&gt;(large model crawler),&lt;span pulumi-lang-nodejs=&#34; userBot &#34; pulumi-lang-dotnet=&#34; UserBot &#34; pulumi-lang-go=&#34; userBot &#34; pulumi-lang-python=&#34; user_bot &#34; pulumi-lang-yaml=&#34; userBot &#34; pulumi-lang-java=&#34; userBot &#34; pulumi-lang-hcl=&#34; user_bot &#34;&gt; userBot &lt;/span&gt;(user-triggered crawling),&lt;span pulumi-lang-nodejs=&#34; searchEngineBot &#34; pulumi-lang-dotnet=&#34; SearchEngineBot &#34; pulumi-lang-go=&#34; searchEngineBot &#34; pulumi-lang-python=&#34; search_engine_bot &#34; pulumi-lang-yaml=&#34; searchEngineBot &#34; pulumi-lang-java=&#34; searchEngineBot &#34; pulumi-lang-hcl=&#34; search_engine_bot &#34;&gt; searchEngineBot &lt;/span&gt;(search engine), marketing (marketing tool), etc.
     * 
     */
    @Export(name="botType", refs={String.class}, tree="[0]")
    private Output<String> botType;

    /**
     * @return Category of the system Bot rule, such as&lt;span pulumi-lang-nodejs=&#34; llmCrawlerBot &#34; pulumi-lang-dotnet=&#34; LlmCrawlerBot &#34; pulumi-lang-go=&#34; llmCrawlerBot &#34; pulumi-lang-python=&#34; llm_crawler_bot &#34; pulumi-lang-yaml=&#34; llmCrawlerBot &#34; pulumi-lang-java=&#34; llmCrawlerBot &#34; pulumi-lang-hcl=&#34; llm_crawler_bot &#34;&gt; llmCrawlerBot &lt;/span&gt;(large model crawler),&lt;span pulumi-lang-nodejs=&#34; userBot &#34; pulumi-lang-dotnet=&#34; UserBot &#34; pulumi-lang-go=&#34; userBot &#34; pulumi-lang-python=&#34; user_bot &#34; pulumi-lang-yaml=&#34; userBot &#34; pulumi-lang-java=&#34; userBot &#34; pulumi-lang-hcl=&#34; user_bot &#34;&gt; userBot &lt;/span&gt;(user-triggered crawling),&lt;span pulumi-lang-nodejs=&#34; searchEngineBot &#34; pulumi-lang-dotnet=&#34; SearchEngineBot &#34; pulumi-lang-go=&#34; searchEngineBot &#34; pulumi-lang-python=&#34; search_engine_bot &#34; pulumi-lang-yaml=&#34; searchEngineBot &#34; pulumi-lang-java=&#34; searchEngineBot &#34; pulumi-lang-hcl=&#34; search_engine_bot &#34;&gt; searchEngineBot &lt;/span&gt;(search engine), marketing (marketing tool), etc.
     * 
     */
    public Output<String> botType() {
        return this.botType;
    }
    /**
     * Description of the sub-rule.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return Description of the sub-rule.
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * Sub-rule switch. Values:
     * 
     *     - 1: Enabled (fixed as 1 when created)
     *     - 0: Disabled (fixed as 0 when deleted)
     * 
     */
    @Export(name="enable", refs={Integer.class}, tree="[0]")
    private Output<Integer> enable;

    /**
     * @return Sub-rule switch. Values:
     * 
     *     - 1: Enabled (fixed as 1 when created)
     *     - 0: Disabled (fixed as 0 when deleted)
     * 
     */
    public Output<Integer> enable() {
        return this.enable;
    }
    /**
     * Domain name to be protected by the system Bot rule.
     * 
     */
    @Export(name="host", refs={String.class}, tree="[0]")
    private Output<String> host;

    /**
     * @return Domain name to be protected by the system Bot rule.
     * 
     */
    public Output<String> host() {
        return this.host;
    }
    /**
     * Whether this sub-rule supports IP-based matching.
     * 
     */
    @Export(name="ipMatch", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> ipMatch;

    /**
     * @return Whether this sub-rule supports IP-based matching.
     * 
     */
    public Output<Boolean> ipMatch() {
        return this.ipMatch;
    }
    /**
     * Sub-rule name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Sub-rule name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Project name to which the resource belongs.
     * 
     */
    @Export(name="projectName", refs={String.class}, tree="[0]")
    private Output<String> projectName;

    /**
     * @return Project name to which the resource belongs.
     * 
     */
    public Output<String> projectName() {
        return this.projectName;
    }
    /**
     * Unique tag for the system Bot sub-rule, such as J000000001026. Used to uniquely identify a sub-rule within a BotType category.
     * 
     */
    @Export(name="ruleTag", refs={String.class}, tree="[0]")
    private Output<String> ruleTag;

    /**
     * @return Unique tag for the system Bot sub-rule, such as J000000001026. Used to uniquely identify a sub-rule within a BotType category.
     * 
     */
    public Output<String> ruleTag() {
        return this.ruleTag;
    }
    /**
     * Verification exemption duration, in seconds. The period during which verification is not required after a hit and successful verification.
     * 
     */
    @Export(name="verificationExemptionTime", refs={Integer.class}, tree="[0]")
    private Output<Integer> verificationExemptionTime;

    /**
     * @return Verification exemption duration, in seconds. The period during which verification is not required after a hit and successful verification.
     * 
     */
    public Output<Integer> verificationExemptionTime() {
        return this.verificationExemptionTime;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SystemBot(java.lang.String name) {
        this(name, SystemBotArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SystemBot(java.lang.String name, SystemBotArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SystemBot(java.lang.String name, SystemBotArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:waf/systemBot:SystemBot", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SystemBot(java.lang.String name, Output<java.lang.String> id, @Nullable SystemBotState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:waf/systemBot:SystemBot", name, state, makeResourceOptions(options, id), false);
    }

    private static SystemBotArgs makeArgs(SystemBotArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SystemBotArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/byteplus-sdk")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SystemBot get(java.lang.String name, Output<java.lang.String> id, @Nullable SystemBotState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SystemBot(name, id, state, options);
    }
}
