// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Plural Data Source schema for Byteplus::TransitRouter::TransitRouterTrafficQosQueuePolicy
 */
export function getTransitRouterTrafficQosQueuePolicies(opts?: pulumi.InvokeOptions): Promise<GetTransitRouterTrafficQosQueuePoliciesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytepluscc:transitrouter/getTransitRouterTrafficQosQueuePolicies:getTransitRouterTrafficQosQueuePolicies", {
    }, opts);
}

/**
 * A collection of values returned by getTransitRouterTrafficQosQueuePolicies.
 */
export interface GetTransitRouterTrafficQosQueuePoliciesResult {
    /**
     * Uniquely identifies the data source.
     */
    readonly id: string;
    /**
     * Set of Resource Identifiers.
     */
    readonly ids: string[];
}
/**
 * Plural Data Source schema for Byteplus::TransitRouter::TransitRouterTrafficQosQueuePolicy
 */
export function getTransitRouterTrafficQosQueuePoliciesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTransitRouterTrafficQosQueuePoliciesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytepluscc:transitrouter/getTransitRouterTrafficQosQueuePolicies:getTransitRouterTrafficQosQueuePolicies", {
    }, opts);
}
