// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.ecs.outputs;

import com.byteplus.bytepluscc.ecs.outputs.DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType;
import com.byteplus.bytepluscc.ecs.outputs.DedicatedHostClusterDedicatedHostClusterCapacityLocalVolumeCapacity;
import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DedicatedHostClusterDedicatedHostClusterCapacity {
    /**
     * @return Supported instance types and the remaining number of instances that can be created for each type in this dedicated host cluster.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    private @Nullable List<DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType> availableInstanceTypes;
    /**
     * @return Total remaining available memory in this dedicated host cluster, measured in GiB.
     * 
     */
    private @Nullable Integer availableMemory;
    /**
     * @return Total remaining available vCPU count in this dedicated host cluster.
     * 
     */
    private @Nullable Integer availableVcpus;
    /**
     * @return Available and total capacity of each type of local disk in this dedicated host cluster.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    private @Nullable List<DedicatedHostClusterDedicatedHostClusterCapacityLocalVolumeCapacity> localVolumeCapacities;
    /**
     * @return Total memory of this dedicated host cluster, measured in GiB.
     * 
     */
    private @Nullable Integer totalMemory;
    /**
     * @return Total vCPU count of this dedicated host cluster.
     * 
     */
    private @Nullable Integer totalVcpus;

    private DedicatedHostClusterDedicatedHostClusterCapacity() {}
    /**
     * @return Supported instance types and the remaining number of instances that can be created for each type in this dedicated host cluster.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    public List<DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType> availableInstanceTypes() {
        return this.availableInstanceTypes == null ? List.of() : this.availableInstanceTypes;
    }
    /**
     * @return Total remaining available memory in this dedicated host cluster, measured in GiB.
     * 
     */
    public Optional<Integer> availableMemory() {
        return Optional.ofNullable(this.availableMemory);
    }
    /**
     * @return Total remaining available vCPU count in this dedicated host cluster.
     * 
     */
    public Optional<Integer> availableVcpus() {
        return Optional.ofNullable(this.availableVcpus);
    }
    /**
     * @return Available and total capacity of each type of local disk in this dedicated host cluster.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    public List<DedicatedHostClusterDedicatedHostClusterCapacityLocalVolumeCapacity> localVolumeCapacities() {
        return this.localVolumeCapacities == null ? List.of() : this.localVolumeCapacities;
    }
    /**
     * @return Total memory of this dedicated host cluster, measured in GiB.
     * 
     */
    public Optional<Integer> totalMemory() {
        return Optional.ofNullable(this.totalMemory);
    }
    /**
     * @return Total vCPU count of this dedicated host cluster.
     * 
     */
    public Optional<Integer> totalVcpus() {
        return Optional.ofNullable(this.totalVcpus);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DedicatedHostClusterDedicatedHostClusterCapacity defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType> availableInstanceTypes;
        private @Nullable Integer availableMemory;
        private @Nullable Integer availableVcpus;
        private @Nullable List<DedicatedHostClusterDedicatedHostClusterCapacityLocalVolumeCapacity> localVolumeCapacities;
        private @Nullable Integer totalMemory;
        private @Nullable Integer totalVcpus;
        public Builder() {}
        public Builder(DedicatedHostClusterDedicatedHostClusterCapacity defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.availableInstanceTypes = defaults.availableInstanceTypes;
    	      this.availableMemory = defaults.availableMemory;
    	      this.availableVcpus = defaults.availableVcpus;
    	      this.localVolumeCapacities = defaults.localVolumeCapacities;
    	      this.totalMemory = defaults.totalMemory;
    	      this.totalVcpus = defaults.totalVcpus;
        }

        @CustomType.Setter
        public Builder availableInstanceTypes(@Nullable List<DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType> availableInstanceTypes) {

            this.availableInstanceTypes = availableInstanceTypes;
            return this;
        }
        public Builder availableInstanceTypes(DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType... availableInstanceTypes) {
            return availableInstanceTypes(List.of(availableInstanceTypes));
        }
        @CustomType.Setter
        public Builder availableMemory(@Nullable Integer availableMemory) {

            this.availableMemory = availableMemory;
            return this;
        }
        @CustomType.Setter
        public Builder availableVcpus(@Nullable Integer availableVcpus) {

            this.availableVcpus = availableVcpus;
            return this;
        }
        @CustomType.Setter
        public Builder localVolumeCapacities(@Nullable List<DedicatedHostClusterDedicatedHostClusterCapacityLocalVolumeCapacity> localVolumeCapacities) {

            this.localVolumeCapacities = localVolumeCapacities;
            return this;
        }
        public Builder localVolumeCapacities(DedicatedHostClusterDedicatedHostClusterCapacityLocalVolumeCapacity... localVolumeCapacities) {
            return localVolumeCapacities(List.of(localVolumeCapacities));
        }
        @CustomType.Setter
        public Builder totalMemory(@Nullable Integer totalMemory) {

            this.totalMemory = totalMemory;
            return this;
        }
        @CustomType.Setter
        public Builder totalVcpus(@Nullable Integer totalVcpus) {

            this.totalVcpus = totalVcpus;
            return this;
        }
        public DedicatedHostClusterDedicatedHostClusterCapacity build() {
            final var _resultValue = new DedicatedHostClusterDedicatedHostClusterCapacity();
            _resultValue.availableInstanceTypes = availableInstanceTypes;
            _resultValue.availableMemory = availableMemory;
            _resultValue.availableVcpus = availableVcpus;
            _resultValue.localVolumeCapacities = localVolumeCapacities;
            _resultValue.totalMemory = totalMemory;
            _resultValue.totalVcpus = totalVcpus;
            return _resultValue;
        }
    }
}
