// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("bytepluscc");

/**
 * The Access Key for Byteplus Provider. It must be provided, but it can also be sourced from the `BYTEPLUS_ACCESS_KEY`
 * environment variable
 */
export declare const accessKey: string | undefined;
Object.defineProperty(exports, "accessKey", {
    get() {
        return __config.get("accessKey") ?? utilities.getEnv("BYTEPLUS_ACCESS_KEY");
    },
    enumerable: true,
});

/**
 * An `assumeRole` block (documented below). Only one `assumeRole` block may be in the configuration.
 */
export declare const assumeRole: outputs.config.AssumeRole | undefined;
Object.defineProperty(exports, "assumeRole", {
    get() {
        return __config.getObject<outputs.config.AssumeRole>("assumeRole");
    },
    enumerable: true,
});

/**
 * CUSTOMER HEADERS for Byteplus Provider. The customerHeaders field uses commas (,) to separate multiple headers, and
 * colons (:) to separate each header key from its corresponding value.
 */
export declare const customerHeaders: string | undefined;
Object.defineProperty(exports, "customerHeaders", {
    get() {
        return __config.get("customerHeaders") ?? utilities.getEnv("BYTEPLUS_CUSTOMER_HEADERS");
    },
    enumerable: true,
});

/**
 * Disable SSL for Byteplus Provider
 */
export declare const disableSsl: boolean | undefined;
Object.defineProperty(exports, "disableSsl", {
    get() {
        return __config.getObject<boolean>("disableSsl") ?? utilities.getEnvBoolean("BYTEPLUS_DISABLE_SSL");
    },
    enumerable: true,
});

/**
 * An `endpoints` block (documented below). Only one `endpoints` block may be in the configuration.
 */
export declare const endpoints: outputs.config.Endpoints | undefined;
Object.defineProperty(exports, "endpoints", {
    get() {
        return __config.getObject<outputs.config.Endpoints>("endpoints");
    },
    enumerable: true,
});

/**
 * PROXY URL for Byteplus Provider
 */
export declare const proxyUrl: string | undefined;
Object.defineProperty(exports, "proxyUrl", {
    get() {
        return __config.get("proxyUrl") ?? utilities.getEnv("BYTEPLUS_PROXY_URL");
    },
    enumerable: true,
});

/**
 * The Region for Byteplus Provider. It must be provided, but it can also be sourced from the `BYTEPLUS_REGION` environment
 * variable
 */
export declare const region: string | undefined;
Object.defineProperty(exports, "region", {
    get() {
        return __config.get("region") ?? utilities.getEnv("BYTEPLUS_REGION");
    },
    enumerable: true,
});

/**
 * he Secret Key for Byteplus Provider. It must be provided, but it can also be sourced from the `BYTEPLUS_SECRET_KEY`
 * environment variable
 */
export declare const secretKey: string | undefined;
Object.defineProperty(exports, "secretKey", {
    get() {
        return __config.get("secretKey") ?? utilities.getEnv("BYTEPLUS_SECRET_KEY");
    },
    enumerable: true,
});

