// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * The cloud-native messaging engine is 100% compatible with the Apache Kafka protocol. It is a fully managed, high-throughput, low-latency, highly available, highly scalable, and highly stable distributed messaging engine service built on cloud-native architecture. It supports flexible, dynamic scaling and integrated stream-batch processing, delivering enterprise-grade, real-time stream data processing at large scale. It helps you build the 'central nervous system' for data processing and is widely used in scenarios such as log collection, data aggregation, and offline data analysis.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as byteplus from "@pulumi/byteplus";
 *
 * const bMQInstanceDemo = new byteplus.index.BmqInstance("BMQInstanceDemo", {
 *     name: "BMQInstanceDemo",
 *     billingType: "POST",
 *     projectName: "default",
 *     specification: "bmq.standard",
 *     vpcId: "vpc-miltj87lh2ww5smt1bxxxxx",
 *     messageRetention: 1,
 *     endpoints: {
 *         "public": {
 *             eipId: "eip-3nriu2y2ufwu8931exxxxx",
 *         },
 *         overlay: {
 *             vpcIds: ["vpc-miltj87lh2ww5smt1bxxxxx"],
 *         },
 *     },
 *     securityGroupIdList: ["sg-3nqnz9en1ucxs931eaxxxxx"],
 *     subnetIdList: ["subnet-w02wsq25fitc865ykaxxxxx"],
 *     zoneIdList: ["cn-beijing-a"],
 *     tags: [{
 *         key: "env",
 *         type: "CUSTOM",
 *         value: "test",
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import bytepluscc:bmq/instance:Instance example "instance_id"
 * ```
 */
export class Instance extends pulumi.CustomResource {
    /**
     * Get an existing Instance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InstanceState, opts?: pulumi.CustomResourceOptions): Instance {
        return new Instance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bytepluscc:bmq/instance:Instance';

    /**
     * Returns true if the given object is an instance of Instance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Instance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Instance.__pulumiType;
    }

    /**
     * Whether to enable auto-renewal. Possible values: true: Enable auto-renewal. false: Disable auto-renewal
     */
    public readonly autoRenew!: pulumi.Output<string>;
    /**
     * Unit of purchase duration. Possible values: MONTHLY: Monthly purchase. YEARLY: Annual purchase
     */
    public readonly billingPeriod!: pulumi.Output<string>;
    /**
     * Instance billing method. Possible values: POST: Pay-as-you-go. MIX: Subscription
     */
    public readonly billingType!: pulumi.Output<string>;
    /**
     * Instance creation time
     */
    public /*out*/ readonly createdTime!: pulumi.Output<string>;
    /**
     * Instance description statement
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * Whether public access is enabled for the instance. To enable public access, configure the public IP ID in the same region
     */
    public readonly eipId!: pulumi.Output<string>;
    /**
     * Response data for all instance endpoints
     */
    public readonly endpoints!: pulumi.Output<outputs.bmq.InstanceEndpoints>;
    /**
     * Instance expiration time
     */
    public /*out*/ readonly expirationTime!: pulumi.Output<string>;
    /**
     * Maximum number of consumer groups per instance
     */
    public /*out*/ readonly groupLimit!: pulumi.Output<number>;
    /**
     * Instance ID
     */
    public /*out*/ readonly instanceId!: pulumi.Output<string>;
    /**
     * Message retention period for all topics under the instance, in hours
     */
    public readonly messageRetention!: pulumi.Output<number>;
    /**
     * Set a custom name for the BMQ instance. Constraints: Use lowercase letters, numbers, and hyphens (-). Length: 1–64 characters
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Maximum number of partitions per instance
     */
    public /*out*/ readonly partitionLimit!: pulumi.Output<number>;
    /**
     * Project name to which the instance belongs
     */
    public readonly projectName!: pulumi.Output<string>;
    public /*out*/ readonly resourceTags!: pulumi.Output<outputs.bmq.InstanceResourceTag[]>;
    /**
     * Instance resource statistics response data
     */
    public /*out*/ readonly resources!: pulumi.Output<outputs.bmq.InstanceResources>;
    /**
     * List of security groups used by the instance
     */
    public readonly securityGroupIdLists!: pulumi.Output<string[]>;
    /**
     * Instance specification
     */
    public readonly specification!: pulumi.Output<string>;
    /**
     * Instance status. Possible values: INITIALIZING: Initializing, INITIALIZATION*FAILED: Initialization failed, RUNNING: Running, MODIFYING: Updating, MODIFY*FAILED: Update failed, RELEASING: Releasing, STOPPING: Stopping, STOPPED: Stopped, RECOVERING: Recovering, EXCEPTION: Exception, CAPACITY*EXPAXION*FAILED: Capacity expansion failed, EXPANDING*CAPACITY: Expanding capacity, CANCEL*EXPANDING_CAPACITY: Canceling capacity expansion, RESTARTING: Restarting, UNPAID: Unpaid
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * List of subnets used by the instance
     */
    public readonly subnetIdLists!: pulumi.Output<string[]>;
    public readonly tags!: pulumi.Output<outputs.bmq.InstanceTag[]>;
    /**
     * Purchase duration for subscription instances, in months
     */
    public readonly times!: pulumi.Output<number>;
    /**
     * Maximum number of topics per instance
     */
    public /*out*/ readonly topicLimit!: pulumi.Output<number>;
    /**
     * VPC ID where the instance is located
     */
    public readonly vpcId!: pulumi.Output<string>;
    /**
     * List of availability zones where the instance is located
     */
    public readonly zoneIdLists!: pulumi.Output<string[]>;

    /**
     * Create a Instance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InstanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InstanceArgs | InstanceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InstanceState | undefined;
            resourceInputs["autoRenew"] = state ? state.autoRenew : undefined;
            resourceInputs["billingPeriod"] = state ? state.billingPeriod : undefined;
            resourceInputs["billingType"] = state ? state.billingType : undefined;
            resourceInputs["createdTime"] = state ? state.createdTime : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["eipId"] = state ? state.eipId : undefined;
            resourceInputs["endpoints"] = state ? state.endpoints : undefined;
            resourceInputs["expirationTime"] = state ? state.expirationTime : undefined;
            resourceInputs["groupLimit"] = state ? state.groupLimit : undefined;
            resourceInputs["instanceId"] = state ? state.instanceId : undefined;
            resourceInputs["messageRetention"] = state ? state.messageRetention : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["partitionLimit"] = state ? state.partitionLimit : undefined;
            resourceInputs["projectName"] = state ? state.projectName : undefined;
            resourceInputs["resourceTags"] = state ? state.resourceTags : undefined;
            resourceInputs["resources"] = state ? state.resources : undefined;
            resourceInputs["securityGroupIdLists"] = state ? state.securityGroupIdLists : undefined;
            resourceInputs["specification"] = state ? state.specification : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["subnetIdLists"] = state ? state.subnetIdLists : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["times"] = state ? state.times : undefined;
            resourceInputs["topicLimit"] = state ? state.topicLimit : undefined;
            resourceInputs["vpcId"] = state ? state.vpcId : undefined;
            resourceInputs["zoneIdLists"] = state ? state.zoneIdLists : undefined;
        } else {
            const args = argsOrState as InstanceArgs | undefined;
            if ((!args || args.billingType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'billingType'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.projectName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectName'");
            }
            if ((!args || args.securityGroupIdLists === undefined) && !opts.urn) {
                throw new Error("Missing required property 'securityGroupIdLists'");
            }
            if ((!args || args.specification === undefined) && !opts.urn) {
                throw new Error("Missing required property 'specification'");
            }
            if ((!args || args.subnetIdLists === undefined) && !opts.urn) {
                throw new Error("Missing required property 'subnetIdLists'");
            }
            if ((!args || args.vpcId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vpcId'");
            }
            if ((!args || args.zoneIdLists === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zoneIdLists'");
            }
            resourceInputs["autoRenew"] = args ? args.autoRenew : undefined;
            resourceInputs["billingPeriod"] = args ? args.billingPeriod : undefined;
            resourceInputs["billingType"] = args ? args.billingType : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["eipId"] = args ? args.eipId : undefined;
            resourceInputs["endpoints"] = args ? args.endpoints : undefined;
            resourceInputs["messageRetention"] = args ? args.messageRetention : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["projectName"] = args ? args.projectName : undefined;
            resourceInputs["securityGroupIdLists"] = args ? args.securityGroupIdLists : undefined;
            resourceInputs["specification"] = args ? args.specification : undefined;
            resourceInputs["subnetIdLists"] = args ? args.subnetIdLists : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["times"] = args ? args.times : undefined;
            resourceInputs["vpcId"] = args ? args.vpcId : undefined;
            resourceInputs["zoneIdLists"] = args ? args.zoneIdLists : undefined;
            resourceInputs["createdTime"] = undefined /*out*/;
            resourceInputs["expirationTime"] = undefined /*out*/;
            resourceInputs["groupLimit"] = undefined /*out*/;
            resourceInputs["instanceId"] = undefined /*out*/;
            resourceInputs["partitionLimit"] = undefined /*out*/;
            resourceInputs["resourceTags"] = undefined /*out*/;
            resourceInputs["resources"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["topicLimit"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Instance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Instance resources.
 */
export interface InstanceState {
    /**
     * Whether to enable auto-renewal. Possible values: true: Enable auto-renewal. false: Disable auto-renewal
     */
    autoRenew?: pulumi.Input<string>;
    /**
     * Unit of purchase duration. Possible values: MONTHLY: Monthly purchase. YEARLY: Annual purchase
     */
    billingPeriod?: pulumi.Input<string>;
    /**
     * Instance billing method. Possible values: POST: Pay-as-you-go. MIX: Subscription
     */
    billingType?: pulumi.Input<string>;
    /**
     * Instance creation time
     */
    createdTime?: pulumi.Input<string>;
    /**
     * Instance description statement
     */
    description?: pulumi.Input<string>;
    /**
     * Whether public access is enabled for the instance. To enable public access, configure the public IP ID in the same region
     */
    eipId?: pulumi.Input<string>;
    /**
     * Response data for all instance endpoints
     */
    endpoints?: pulumi.Input<inputs.bmq.InstanceEndpoints>;
    /**
     * Instance expiration time
     */
    expirationTime?: pulumi.Input<string>;
    /**
     * Maximum number of consumer groups per instance
     */
    groupLimit?: pulumi.Input<number>;
    /**
     * Instance ID
     */
    instanceId?: pulumi.Input<string>;
    /**
     * Message retention period for all topics under the instance, in hours
     */
    messageRetention?: pulumi.Input<number>;
    /**
     * Set a custom name for the BMQ instance. Constraints: Use lowercase letters, numbers, and hyphens (-). Length: 1–64 characters
     */
    name?: pulumi.Input<string>;
    /**
     * Maximum number of partitions per instance
     */
    partitionLimit?: pulumi.Input<number>;
    /**
     * Project name to which the instance belongs
     */
    projectName?: pulumi.Input<string>;
    resourceTags?: pulumi.Input<pulumi.Input<inputs.bmq.InstanceResourceTag>[]>;
    /**
     * Instance resource statistics response data
     */
    resources?: pulumi.Input<inputs.bmq.InstanceResources>;
    /**
     * List of security groups used by the instance
     */
    securityGroupIdLists?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Instance specification
     */
    specification?: pulumi.Input<string>;
    /**
     * Instance status. Possible values: INITIALIZING: Initializing, INITIALIZATION*FAILED: Initialization failed, RUNNING: Running, MODIFYING: Updating, MODIFY*FAILED: Update failed, RELEASING: Releasing, STOPPING: Stopping, STOPPED: Stopped, RECOVERING: Recovering, EXCEPTION: Exception, CAPACITY*EXPAXION*FAILED: Capacity expansion failed, EXPANDING*CAPACITY: Expanding capacity, CANCEL*EXPANDING_CAPACITY: Canceling capacity expansion, RESTARTING: Restarting, UNPAID: Unpaid
     */
    status?: pulumi.Input<string>;
    /**
     * List of subnets used by the instance
     */
    subnetIdLists?: pulumi.Input<pulumi.Input<string>[]>;
    tags?: pulumi.Input<pulumi.Input<inputs.bmq.InstanceTag>[]>;
    /**
     * Purchase duration for subscription instances, in months
     */
    times?: pulumi.Input<number>;
    /**
     * Maximum number of topics per instance
     */
    topicLimit?: pulumi.Input<number>;
    /**
     * VPC ID where the instance is located
     */
    vpcId?: pulumi.Input<string>;
    /**
     * List of availability zones where the instance is located
     */
    zoneIdLists?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Instance resource.
 */
export interface InstanceArgs {
    /**
     * Whether to enable auto-renewal. Possible values: true: Enable auto-renewal. false: Disable auto-renewal
     */
    autoRenew?: pulumi.Input<string>;
    /**
     * Unit of purchase duration. Possible values: MONTHLY: Monthly purchase. YEARLY: Annual purchase
     */
    billingPeriod?: pulumi.Input<string>;
    /**
     * Instance billing method. Possible values: POST: Pay-as-you-go. MIX: Subscription
     */
    billingType: pulumi.Input<string>;
    /**
     * Instance description statement
     */
    description?: pulumi.Input<string>;
    /**
     * Whether public access is enabled for the instance. To enable public access, configure the public IP ID in the same region
     */
    eipId?: pulumi.Input<string>;
    /**
     * Response data for all instance endpoints
     */
    endpoints?: pulumi.Input<inputs.bmq.InstanceEndpoints>;
    /**
     * Message retention period for all topics under the instance, in hours
     */
    messageRetention?: pulumi.Input<number>;
    /**
     * Set a custom name for the BMQ instance. Constraints: Use lowercase letters, numbers, and hyphens (-). Length: 1–64 characters
     */
    name: pulumi.Input<string>;
    /**
     * Project name to which the instance belongs
     */
    projectName: pulumi.Input<string>;
    /**
     * List of security groups used by the instance
     */
    securityGroupIdLists: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Instance specification
     */
    specification: pulumi.Input<string>;
    /**
     * List of subnets used by the instance
     */
    subnetIdLists: pulumi.Input<pulumi.Input<string>[]>;
    tags?: pulumi.Input<pulumi.Input<inputs.bmq.InstanceTag>[]>;
    /**
     * Purchase duration for subscription instances, in months
     */
    times?: pulumi.Input<number>;
    /**
     * VPC ID where the instance is located
     */
    vpcId: pulumi.Input<string>;
    /**
     * List of availability zones where the instance is located
     */
    zoneIdLists: pulumi.Input<pulumi.Input<string>[]>;
}
