// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Fwcenter
{
    /// <summary>
    /// NAT boundary firewall instance. Provides security protection and access control for north-south traffic passing through the NAT gateway.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Bytepluscc = Byteplus.Pulumi.Bytepluscc;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Bytepluscc.Fwcenter.NatFireWall("example", new()
    ///     {
    ///         NatGatewayId = "ngw-xxxxxx",
    ///         NatFirewallName = "example",
    ///         FirewallCidr = "192.168.208.0/28",
    ///         Bandwidth = 100,
    ///         ProjectName = "default",
    ///         CloudFirewallId = "CloudFirewallxxxxxxxx",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import bytepluscc:fwcenter/natFireWall:NatFireWall example "nat_firewall_id"
    /// ```
    /// </summary>
    [ByteplusccResourceType("bytepluscc:fwcenter/natFireWall:NatFireWall")]
    public partial class NatFireWall : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        /// </summary>
        [Output("bandwidth")]
        public Output<int> Bandwidth { get; private set; } = null!;

        /// <summary>
        /// Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.
        /// </summary>
        [Output("canCreate")]
        public Output<bool> CanCreate { get; private set; } = null!;

        /// <summary>
        /// Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        /// </summary>
        [Output("cloudFirewallId")]
        public Output<string> CloudFirewallId { get; private set; } = null!;

        /// <summary>
        /// Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.
        /// </summary>
        [Output("errMessage")]
        public Output<string> ErrMessage { get; private set; } = null!;

        /// <summary>
        /// Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        /// </summary>
        [Output("firewallCidr")]
        public Output<string> FirewallCidr { get; private set; } = null!;

        /// <summary>
        /// Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.
        /// </summary>
        [Output("firewallStatus")]
        public Output<string> FirewallStatus { get; private set; } = null!;

        /// <summary>
        /// Unique identifier of the NAT boundary firewall instance.
        /// </summary>
        [Output("natFirewallId")]
        public Output<string> NatFirewallId { get; private set; } = null!;

        /// <summary>
        /// Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        /// </summary>
        [Output("natFirewallName")]
        public Output<string> NatFirewallName { get; private set; } = null!;

        /// <summary>
        /// Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.
        /// </summary>
        [Output("natFirewallSubnetCidr")]
        public Output<string> NatFirewallSubnetCidr { get; private set; } = null!;

        /// <summary>
        /// NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        /// </summary>
        [Output("natGatewayId")]
        public Output<string> NatGatewayId { get; private set; } = null!;

        /// <summary>
        /// Name of the NAT gateway, used to identify the associated NAT gateway.
        /// </summary>
        [Output("natGatewayName")]
        public Output<string> NatGatewayName { get; private set; } = null!;

        /// <summary>
        /// Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.
        /// </summary>
        [Output("peakTrafficWithin7Day")]
        public Output<int> PeakTrafficWithin7Day { get; private set; } = null!;

        /// <summary>
        /// Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        /// </summary>
        [Output("projectName")]
        public Output<string> ProjectName { get; private set; } = null!;

        /// <summary>
        /// Project name to which the associated NAT gateway belongs.
        /// </summary>
        [Output("projectNameForNatGate")]
        public Output<string> ProjectNameForNatGate { get; private set; } = null!;

        /// <summary>
        /// Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.
        /// </summary>
        [Output("vpcCidr")]
        public Output<string> VpcCidr { get; private set; } = null!;

        /// <summary>
        /// Unique identifier of the associated VPC.
        /// </summary>
        [Output("vpcId")]
        public Output<string> VpcId { get; private set; } = null!;

        /// <summary>
        /// Name of the associated VPC.
        /// </summary>
        [Output("vpcName")]
        public Output<string> VpcName { get; private set; } = null!;

        /// <summary>
        /// Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.
        /// </summary>
        [Output("zoneId")]
        public Output<string> ZoneId { get; private set; } = null!;


        /// <summary>
        /// Create a NatFireWall resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NatFireWall(string name, NatFireWallArgs args, CustomResourceOptions? options = null)
            : base("bytepluscc:fwcenter/natFireWall:NatFireWall", name, args ?? new NatFireWallArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NatFireWall(string name, Input<string> id, NatFireWallState? state = null, CustomResourceOptions? options = null)
            : base("bytepluscc:fwcenter/natFireWall:NatFireWall", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/byteplus-sdk",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NatFireWall resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NatFireWall Get(string name, Input<string> id, NatFireWallState? state = null, CustomResourceOptions? options = null)
        {
            return new NatFireWall(name, id, state, options);
        }
    }

    public sealed class NatFireWallArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        /// </summary>
        [Input("bandwidth", required: true)]
        public Input<int> Bandwidth { get; set; } = null!;

        /// <summary>
        /// Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        /// </summary>
        [Input("cloudFirewallId")]
        public Input<string>? CloudFirewallId { get; set; }

        /// <summary>
        /// Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        /// </summary>
        [Input("firewallCidr", required: true)]
        public Input<string> FirewallCidr { get; set; } = null!;

        /// <summary>
        /// Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        /// </summary>
        [Input("natFirewallName", required: true)]
        public Input<string> NatFirewallName { get; set; } = null!;

        /// <summary>
        /// NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        /// </summary>
        [Input("natGatewayId", required: true)]
        public Input<string> NatGatewayId { get; set; } = null!;

        /// <summary>
        /// Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        /// </summary>
        [Input("projectName")]
        public Input<string>? ProjectName { get; set; }

        public NatFireWallArgs()
        {
        }
        public static new NatFireWallArgs Empty => new NatFireWallArgs();
    }

    public sealed class NatFireWallState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        /// </summary>
        [Input("bandwidth")]
        public Input<int>? Bandwidth { get; set; }

        /// <summary>
        /// Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.
        /// </summary>
        [Input("canCreate")]
        public Input<bool>? CanCreate { get; set; }

        /// <summary>
        /// Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        /// </summary>
        [Input("cloudFirewallId")]
        public Input<string>? CloudFirewallId { get; set; }

        /// <summary>
        /// Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.
        /// </summary>
        [Input("errMessage")]
        public Input<string>? ErrMessage { get; set; }

        /// <summary>
        /// Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        /// </summary>
        [Input("firewallCidr")]
        public Input<string>? FirewallCidr { get; set; }

        /// <summary>
        /// Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.
        /// </summary>
        [Input("firewallStatus")]
        public Input<string>? FirewallStatus { get; set; }

        /// <summary>
        /// Unique identifier of the NAT boundary firewall instance.
        /// </summary>
        [Input("natFirewallId")]
        public Input<string>? NatFirewallId { get; set; }

        /// <summary>
        /// Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        /// </summary>
        [Input("natFirewallName")]
        public Input<string>? NatFirewallName { get; set; }

        /// <summary>
        /// Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.
        /// </summary>
        [Input("natFirewallSubnetCidr")]
        public Input<string>? NatFirewallSubnetCidr { get; set; }

        /// <summary>
        /// NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        /// </summary>
        [Input("natGatewayId")]
        public Input<string>? NatGatewayId { get; set; }

        /// <summary>
        /// Name of the NAT gateway, used to identify the associated NAT gateway.
        /// </summary>
        [Input("natGatewayName")]
        public Input<string>? NatGatewayName { get; set; }

        /// <summary>
        /// Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.
        /// </summary>
        [Input("peakTrafficWithin7Day")]
        public Input<int>? PeakTrafficWithin7Day { get; set; }

        /// <summary>
        /// Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        /// </summary>
        [Input("projectName")]
        public Input<string>? ProjectName { get; set; }

        /// <summary>
        /// Project name to which the associated NAT gateway belongs.
        /// </summary>
        [Input("projectNameForNatGate")]
        public Input<string>? ProjectNameForNatGate { get; set; }

        /// <summary>
        /// Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.
        /// </summary>
        [Input("vpcCidr")]
        public Input<string>? VpcCidr { get; set; }

        /// <summary>
        /// Unique identifier of the associated VPC.
        /// </summary>
        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        /// <summary>
        /// Name of the associated VPC.
        /// </summary>
        [Input("vpcName")]
        public Input<string>? VpcName { get; set; }

        /// <summary>
        /// Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.
        /// </summary>
        [Input("zoneId")]
        public Input<string>? ZoneId { get; set; }

        public NatFireWallState()
        {
        }
        public static new NatFireWallState Empty => new NatFireWallState();
    }
}
