// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.cdn.inputs;

import com.byteplus.bytepluscc.cdn.inputs.DomainRuleEngineRuleArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainRuleEngineArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainRuleEngineArgs Empty = new DomainRuleEngineArgs();

    /**
     * Indicates the list of rules in the rule engine. The order of rules in the list determines their priority.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    @Import(name="rules")
    private @Nullable Output<List<DomainRuleEngineRuleArgs>> rules;

    /**
     * @return Indicates the list of rules in the rule engine. The order of rules in the list determines their priority.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    public Optional<Output<List<DomainRuleEngineRuleArgs>>> rules() {
        return Optional.ofNullable(this.rules);
    }

    /**
     * Indicates whether this feature is enabled. Valid values: true: Enable this feature. false: Disable this feature. The default value is false.
     * 
     */
    @Import(name="switch")
    private @Nullable Output<Boolean> switch_;

    /**
     * @return Indicates whether this feature is enabled. Valid values: true: Enable this feature. false: Disable this feature. The default value is false.
     * 
     */
    public Optional<Output<Boolean>> switch_() {
        return Optional.ofNullable(this.switch_);
    }

    private DomainRuleEngineArgs() {}

    private DomainRuleEngineArgs(DomainRuleEngineArgs $) {
        this.rules = $.rules;
        this.switch_ = $.switch_;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainRuleEngineArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainRuleEngineArgs $;

        public Builder() {
            $ = new DomainRuleEngineArgs();
        }

        public Builder(DomainRuleEngineArgs defaults) {
            $ = new DomainRuleEngineArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param rules Indicates the list of rules in the rule engine. The order of rules in the list determines their priority.
         * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
         * 
         * @return builder
         * 
         */
        public Builder rules(@Nullable Output<List<DomainRuleEngineRuleArgs>> rules) {
            $.rules = rules;
            return this;
        }

        /**
         * @param rules Indicates the list of rules in the rule engine. The order of rules in the list determines their priority.
         * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
         * 
         * @return builder
         * 
         */
        public Builder rules(List<DomainRuleEngineRuleArgs> rules) {
            return rules(Output.of(rules));
        }

        /**
         * @param rules Indicates the list of rules in the rule engine. The order of rules in the list determines their priority.
         * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
         * 
         * @return builder
         * 
         */
        public Builder rules(DomainRuleEngineRuleArgs... rules) {
            return rules(List.of(rules));
        }

        /**
         * @param switch_ Indicates whether this feature is enabled. Valid values: true: Enable this feature. false: Disable this feature. The default value is false.
         * 
         * @return builder
         * 
         */
        public Builder switch_(@Nullable Output<Boolean> switch_) {
            $.switch_ = switch_;
            return this;
        }

        /**
         * @param switch_ Indicates whether this feature is enabled. Valid values: true: Enable this feature. false: Disable this feature. The default value is false.
         * 
         * @return builder
         * 
         */
        public Builder switch_(Boolean switch_) {
            return switch_(Output.of(switch_));
        }

        public DomainRuleEngineArgs build() {
            return $;
        }
    }

}
