// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Waf.Inputs
{

    public sealed class CustomPageAccurateAccurateRuleGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Matching object. For example: request.uri, request.header, request.header.clientip, request.queryargs.abc, request.header.custom-header, request.cookie.custom-cookie, etc.
        /// </summary>
        [Input("httpObj")]
        public Input<string>? HttpObj { get; set; }

        /// <summary>
        /// Matching object type enumeration. 0: Request protocol; 1: Request URI; 2: Request method; 3: Request path; 4: Request parameter; 5: Request header; 6: User-Agent; 7: Referer; 8: Cookie; 9: Request body length; 10: Request body format; 11: X-Forwarded-For; 12: Client IP; 13: Custom Args; 14: Custom Header; 15: Custom Cookie.
        /// </summary>
        [Input("objType")]
        public Input<int>? ObjType { get; set; }

        /// <summary>
        /// Matching operator enumeration. 0–5: numerical comparison; 6–11: substring match; 12–15: set match; 16: regex; 17–21: IP recognition (only for request.header.clientip or custom objects).
        /// </summary>
        [Input("opretar")]
        public Input<int>? Opretar { get; set; }

        /// <summary>
        /// Matching attribute type enumeration. 0: Value; 5: IP (used only when Operator=17~21).
        /// </summary>
        [Input("property")]
        public Input<int>? Property { get; set; }

        /// <summary>
        /// Matching value. For IP recognition operations with Operator=17~21, no matching content is involved and this can be an empty string; for other operators, enter the actual matching value.
        /// </summary>
        [Input("valueString")]
        public Input<string>? ValueString { get; set; }

        public CustomPageAccurateAccurateRuleGetArgs()
        {
        }
        public static new CustomPageAccurateAccurateRuleGetArgs Empty => new CustomPageAccurateAccurateRuleGetArgs();
    }
}
