// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Waf.Inputs
{

    public sealed class CustomPageAccurateGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("accurateRules")]
        private InputList<Inputs.CustomPageAccurateAccurateRuleGetArgs>? _accurateRules;

        /// <summary>
        /// Sub-rule list in advanced conditions.
        /// Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
        /// </summary>
        public InputList<Inputs.CustomPageAccurateAccurateRuleGetArgs> AccurateRules
        {
            get => _accurateRules ?? (_accurateRules = new InputList<Inputs.CustomPageAccurateAccurateRuleGetArgs>());
            set => _accurateRules = value;
        }

        /// <summary>
        /// Logical relationship between sub-rules. 0: OR; 1: AND.
        /// </summary>
        [Input("logic")]
        public Input<int>? Logic { get; set; }

        public CustomPageAccurateGetArgs()
        {
        }
        public static new CustomPageAccurateGetArgs Empty => new CustomPageAccurateGetArgs();
    }
}
