// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.waf.outputs;

import com.byteplus.bytepluscc.waf.outputs.GetCustomPageAccurate;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCustomPageResult {
    /**
     * @return Advanced condition configuration. Only takes effect when Advanced=1.
     * 
     */
    private GetCustomPageAccurate accurate;
    /**
     * @return Enable advanced conditions. 0: Off (default); 1: On. If enabled, Accurate must also be configured.
     * 
     */
    private Integer advanced;
    /**
     * @return Custom response page content. Maximum length: 4096 bytes. Only effective when PageMode=0.
     * 
     */
    private String body;
    /**
     * @return Client IP. Value is fixed as ALL, meaning it applies to all source IPs.
     * 
     */
    private String clientIp;
    /**
     * @return Custom response status code, such as 403, 405, 503. Only effective when PageMode=0.
     * 
     */
    private String code;
    /**
     * @return Custom response Content-Type response header. For example: text/html, application/json, etc. Only effective when PageMode=0.
     * 
     */
    private String contentType;
    /**
     * @return Rule description.
     * 
     */
    private String description;
    /**
     * @return Rule switch. 0: Off; 1: On.
     * 
     */
    private Integer enable;
    /**
     * @return Domain name. The website domain name to be protected. Before calling, make sure the domain name has been added to the current WAF instance.
     * 
     */
    private String host;
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    private String id;
    /**
     * @return Rule name. Must start with a Chinese character, letter, or number. Allows Chinese characters, letters, numbers, periods (.), underscores (_), and hyphens (-). Length: 1–128 characters.
     * 
     */
    private String name;
    /**
     * @return Response page mode. 0: Custom response body; 2: Redirect URL.
     * 
     */
    private Integer pageMode;
    /**
     * @return Associated protection policy. 1: Observe; 8: Block.
     * 
     */
    private Integer policy;
    /**
     * @return Project name, which is the project associated with the current resource. Only projects with permissions under the current identity can be associated. Default is default.
     * 
     */
    private String projectName;
    /**
     * @return Redirect target URL. Only effective when PageMode=2.
     * 
     */
    private String redirectUrl;
    /**
     * @return Custom block response rule ID.
     * 
     */
    private String ruleId;
    /**
     * @return Rule display ID. The RuleTag prefix for custom interception response rules is always B, consisting of the prefix B and a 12-digit RuleId (zero-padded in the middle if fewer than 12 digits). For example, RuleId=116869 corresponds to RuleTag=B000000116869.
     * 
     */
    private String ruleTag;
    /**
     * @return Last updated time of the rule.
     * 
     */
    private String updateTime;
    /**
     * @return URL path where the rule takes effect.
     * 
     */
    private String url;

    private GetCustomPageResult() {}
    /**
     * @return Advanced condition configuration. Only takes effect when Advanced=1.
     * 
     */
    public GetCustomPageAccurate accurate() {
        return this.accurate;
    }
    /**
     * @return Enable advanced conditions. 0: Off (default); 1: On. If enabled, Accurate must also be configured.
     * 
     */
    public Integer advanced() {
        return this.advanced;
    }
    /**
     * @return Custom response page content. Maximum length: 4096 bytes. Only effective when PageMode=0.
     * 
     */
    public String body() {
        return this.body;
    }
    /**
     * @return Client IP. Value is fixed as ALL, meaning it applies to all source IPs.
     * 
     */
    public String clientIp() {
        return this.clientIp;
    }
    /**
     * @return Custom response status code, such as 403, 405, 503. Only effective when PageMode=0.
     * 
     */
    public String code() {
        return this.code;
    }
    /**
     * @return Custom response Content-Type response header. For example: text/html, application/json, etc. Only effective when PageMode=0.
     * 
     */
    public String contentType() {
        return this.contentType;
    }
    /**
     * @return Rule description.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Rule switch. 0: Off; 1: On.
     * 
     */
    public Integer enable() {
        return this.enable;
    }
    /**
     * @return Domain name. The website domain name to be protected. Before calling, make sure the domain name has been added to the current WAF instance.
     * 
     */
    public String host() {
        return this.host;
    }
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Rule name. Must start with a Chinese character, letter, or number. Allows Chinese characters, letters, numbers, periods (.), underscores (_), and hyphens (-). Length: 1–128 characters.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Response page mode. 0: Custom response body; 2: Redirect URL.
     * 
     */
    public Integer pageMode() {
        return this.pageMode;
    }
    /**
     * @return Associated protection policy. 1: Observe; 8: Block.
     * 
     */
    public Integer policy() {
        return this.policy;
    }
    /**
     * @return Project name, which is the project associated with the current resource. Only projects with permissions under the current identity can be associated. Default is default.
     * 
     */
    public String projectName() {
        return this.projectName;
    }
    /**
     * @return Redirect target URL. Only effective when PageMode=2.
     * 
     */
    public String redirectUrl() {
        return this.redirectUrl;
    }
    /**
     * @return Custom block response rule ID.
     * 
     */
    public String ruleId() {
        return this.ruleId;
    }
    /**
     * @return Rule display ID. The RuleTag prefix for custom interception response rules is always B, consisting of the prefix B and a 12-digit RuleId (zero-padded in the middle if fewer than 12 digits). For example, RuleId=116869 corresponds to RuleTag=B000000116869.
     * 
     */
    public String ruleTag() {
        return this.ruleTag;
    }
    /**
     * @return Last updated time of the rule.
     * 
     */
    public String updateTime() {
        return this.updateTime;
    }
    /**
     * @return URL path where the rule takes effect.
     * 
     */
    public String url() {
        return this.url;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCustomPageResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetCustomPageAccurate accurate;
        private Integer advanced;
        private String body;
        private String clientIp;
        private String code;
        private String contentType;
        private String description;
        private Integer enable;
        private String host;
        private String id;
        private String name;
        private Integer pageMode;
        private Integer policy;
        private String projectName;
        private String redirectUrl;
        private String ruleId;
        private String ruleTag;
        private String updateTime;
        private String url;
        public Builder() {}
        public Builder(GetCustomPageResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accurate = defaults.accurate;
    	      this.advanced = defaults.advanced;
    	      this.body = defaults.body;
    	      this.clientIp = defaults.clientIp;
    	      this.code = defaults.code;
    	      this.contentType = defaults.contentType;
    	      this.description = defaults.description;
    	      this.enable = defaults.enable;
    	      this.host = defaults.host;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.pageMode = defaults.pageMode;
    	      this.policy = defaults.policy;
    	      this.projectName = defaults.projectName;
    	      this.redirectUrl = defaults.redirectUrl;
    	      this.ruleId = defaults.ruleId;
    	      this.ruleTag = defaults.ruleTag;
    	      this.updateTime = defaults.updateTime;
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder accurate(GetCustomPageAccurate accurate) {
            if (accurate == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "accurate");
            }
            this.accurate = accurate;
            return this;
        }
        @CustomType.Setter
        public Builder advanced(Integer advanced) {
            if (advanced == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "advanced");
            }
            this.advanced = advanced;
            return this;
        }
        @CustomType.Setter
        public Builder body(String body) {
            if (body == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "body");
            }
            this.body = body;
            return this;
        }
        @CustomType.Setter
        public Builder clientIp(String clientIp) {
            if (clientIp == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "clientIp");
            }
            this.clientIp = clientIp;
            return this;
        }
        @CustomType.Setter
        public Builder code(String code) {
            if (code == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "code");
            }
            this.code = code;
            return this;
        }
        @CustomType.Setter
        public Builder contentType(String contentType) {
            if (contentType == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "contentType");
            }
            this.contentType = contentType;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder enable(Integer enable) {
            if (enable == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "enable");
            }
            this.enable = enable;
            return this;
        }
        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "host");
            }
            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder pageMode(Integer pageMode) {
            if (pageMode == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "pageMode");
            }
            this.pageMode = pageMode;
            return this;
        }
        @CustomType.Setter
        public Builder policy(Integer policy) {
            if (policy == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "policy");
            }
            this.policy = policy;
            return this;
        }
        @CustomType.Setter
        public Builder projectName(String projectName) {
            if (projectName == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "projectName");
            }
            this.projectName = projectName;
            return this;
        }
        @CustomType.Setter
        public Builder redirectUrl(String redirectUrl) {
            if (redirectUrl == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "redirectUrl");
            }
            this.redirectUrl = redirectUrl;
            return this;
        }
        @CustomType.Setter
        public Builder ruleId(String ruleId) {
            if (ruleId == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "ruleId");
            }
            this.ruleId = ruleId;
            return this;
        }
        @CustomType.Setter
        public Builder ruleTag(String ruleTag) {
            if (ruleTag == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "ruleTag");
            }
            this.ruleTag = ruleTag;
            return this;
        }
        @CustomType.Setter
        public Builder updateTime(String updateTime) {
            if (updateTime == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "updateTime");
            }
            this.updateTime = updateTime;
            return this;
        }
        @CustomType.Setter
        public Builder url(String url) {
            if (url == null) {
              throw new MissingRequiredPropertyException("GetCustomPageResult", "url");
            }
            this.url = url;
            return this;
        }
        public GetCustomPageResult build() {
            final var _resultValue = new GetCustomPageResult();
            _resultValue.accurate = accurate;
            _resultValue.advanced = advanced;
            _resultValue.body = body;
            _resultValue.clientIp = clientIp;
            _resultValue.code = code;
            _resultValue.contentType = contentType;
            _resultValue.description = description;
            _resultValue.enable = enable;
            _resultValue.host = host;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.pageMode = pageMode;
            _resultValue.policy = policy;
            _resultValue.projectName = projectName;
            _resultValue.redirectUrl = redirectUrl;
            _resultValue.ruleId = ruleId;
            _resultValue.ruleTag = ruleTag;
            _resultValue.updateTime = updateTime;
            _resultValue.url = url;
            return _resultValue;
        }
    }
}
