// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Data Source schema for Byteplus::IAM::ApiKey
 */
export function getApiKey(args: GetApiKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetApiKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytepluscc:iam/getApiKey:getApiKey", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getApiKey.
 */
export interface GetApiKeyArgs {
    /**
     * Uniquely identifies the resource.
     */
    id: string;
}

/**
 * A collection of values returned by getApiKey.
 */
export interface GetApiKeyResult {
    /**
     * API Key ID。
     */
    readonly apiKeyId: string;
    /**
     * Created At
     */
    readonly createDate: string;
    /**
     * Uniquely identifies the resource.
     */
    readonly id: string;
    /**
     * API Key Name
     */
    readonly name: string;
    /**
     * Permission Boundary
     */
    readonly permissionsBoundary: string;
    /**
     * API Key Secret
     */
    readonly secret: string;
    /**
     * API Key Status
     */
    readonly status: string;
    /**
     * Last Updated
     */
    readonly updateDate: string;
    /**
     * Username
     */
    readonly userName: string;
}
/**
 * Data Source schema for Byteplus::IAM::ApiKey
 */
export function getApiKeyOutput(args: GetApiKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetApiKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytepluscc:iam/getApiKey:getApiKey", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getApiKey.
 */
export interface GetApiKeyOutputArgs {
    /**
     * Uniquely identifies the resource.
     */
    id: pulumi.Input<string>;
}
