// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vpc

import (
	"context"
	"reflect"

	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Data Source schema for Byteplus::VPC::IpamScope
func LookupIpamScope(ctx *pulumi.Context, args *LookupIpamScopeArgs, opts ...pulumi.InvokeOption) (*LookupIpamScopeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupIpamScopeResult
	err := ctx.Invoke("bytepluscc:vpc/getIpamScope:getIpamScope", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpamScope.
type LookupIpamScopeArgs struct {
	// Uniquely identifies the resource.
	Id string `pulumi:"id"`
}

// A collection of values returned by getIpamScope.
type LookupIpamScopeResult struct {
	// Account ID
	AccountId string `pulumi:"accountId"`
	// IPAM Scope Creation Time
	CreateTime string `pulumi:"createTime"`
	// IPAM Scope Description
	Description string `pulumi:"description"`
	// Uniquely identifies the resource.
	Id string `pulumi:"id"`
	// IPAM ID。
	IpamId string `pulumi:"ipamId"`
	// IPAM Region ID
	IpamRegionId string `pulumi:"ipamRegionId"`
	// IPAM Scope ID
	IpamScopeId string `pulumi:"ipamScopeId"`
	// IPAM Scope Name
	IpamScopeName string `pulumi:"ipamScopeName"`
	// IPAM Scope Type
	IpamScopeType string `pulumi:"ipamScopeType"`
	// Default Scope
	IsDefault bool `pulumi:"isDefault"`
	// Number of Address Pools
	PoolCount int `pulumi:"poolCount"`
	// Project Name
	ProjectName string `pulumi:"projectName"`
	// IPAM Scope Status
	Status string `pulumi:"status"`
	// IPAM Scope Tags
	Tags []GetIpamScopeTag `pulumi:"tags"`
	// IPAM Scope Update Time
	UpdateTime string `pulumi:"updateTime"`
}

func LookupIpamScopeOutput(ctx *pulumi.Context, args LookupIpamScopeOutputArgs, opts ...pulumi.InvokeOption) LookupIpamScopeResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupIpamScopeResultOutput, error) {
			args := v.(LookupIpamScopeArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("bytepluscc:vpc/getIpamScope:getIpamScope", args, LookupIpamScopeResultOutput{}, options).(LookupIpamScopeResultOutput), nil
		}).(LookupIpamScopeResultOutput)
}

// A collection of arguments for invoking getIpamScope.
type LookupIpamScopeOutputArgs struct {
	// Uniquely identifies the resource.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupIpamScopeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpamScopeArgs)(nil)).Elem()
}

// A collection of values returned by getIpamScope.
type LookupIpamScopeResultOutput struct{ *pulumi.OutputState }

func (LookupIpamScopeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpamScopeResult)(nil)).Elem()
}

func (o LookupIpamScopeResultOutput) ToLookupIpamScopeResultOutput() LookupIpamScopeResultOutput {
	return o
}

func (o LookupIpamScopeResultOutput) ToLookupIpamScopeResultOutputWithContext(ctx context.Context) LookupIpamScopeResultOutput {
	return o
}

// Account ID
func (o LookupIpamScopeResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.AccountId }).(pulumi.StringOutput)
}

// IPAM Scope Creation Time
func (o LookupIpamScopeResultOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.CreateTime }).(pulumi.StringOutput)
}

// IPAM Scope Description
func (o LookupIpamScopeResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.Description }).(pulumi.StringOutput)
}

// Uniquely identifies the resource.
func (o LookupIpamScopeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.Id }).(pulumi.StringOutput)
}

// IPAM ID。
func (o LookupIpamScopeResultOutput) IpamId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.IpamId }).(pulumi.StringOutput)
}

// IPAM Region ID
func (o LookupIpamScopeResultOutput) IpamRegionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.IpamRegionId }).(pulumi.StringOutput)
}

// IPAM Scope ID
func (o LookupIpamScopeResultOutput) IpamScopeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.IpamScopeId }).(pulumi.StringOutput)
}

// IPAM Scope Name
func (o LookupIpamScopeResultOutput) IpamScopeName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.IpamScopeName }).(pulumi.StringOutput)
}

// IPAM Scope Type
func (o LookupIpamScopeResultOutput) IpamScopeType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.IpamScopeType }).(pulumi.StringOutput)
}

// Default Scope
func (o LookupIpamScopeResultOutput) IsDefault() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) bool { return v.IsDefault }).(pulumi.BoolOutput)
}

// Number of Address Pools
func (o LookupIpamScopeResultOutput) PoolCount() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) int { return v.PoolCount }).(pulumi.IntOutput)
}

// Project Name
func (o LookupIpamScopeResultOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.ProjectName }).(pulumi.StringOutput)
}

// IPAM Scope Status
func (o LookupIpamScopeResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.Status }).(pulumi.StringOutput)
}

// IPAM Scope Tags
func (o LookupIpamScopeResultOutput) Tags() GetIpamScopeTagArrayOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) []GetIpamScopeTag { return v.Tags }).(GetIpamScopeTagArrayOutput)
}

// IPAM Scope Update Time
func (o LookupIpamScopeResultOutput) UpdateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpamScopeResult) string { return v.UpdateTime }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIpamScopeResultOutput{})
}
