// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Vpc
{
    public static class GetIpamPools
    {
        /// <summary>
        /// Plural Data Source schema for Byteplus::VPC::IpamPool
        /// </summary>
        public static Task<GetIpamPoolsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetIpamPoolsResult>("bytepluscc:vpc/getIpamPools:getIpamPools", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::VPC::IpamPool
        /// </summary>
        public static Output<GetIpamPoolsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetIpamPoolsResult>("bytepluscc:vpc/getIpamPools:getIpamPools", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::VPC::IpamPool
        /// </summary>
        public static Output<GetIpamPoolsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetIpamPoolsResult>("bytepluscc:vpc/getIpamPools:getIpamPools", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetIpamPoolsResult
    {
        /// <summary>
        /// Uniquely identifies the data source.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of Resource Identifiers.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetIpamPoolsResult(
            string id,

            ImmutableArray<string> ids)
        {
            Id = id;
            Ids = ids;
        }
    }
}
