// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Vpc
{
    public static class GetIpam
    {
        /// <summary>
        /// Data Source schema for Byteplus::VPC::IPAM
        /// </summary>
        public static Task<GetIpamResult> InvokeAsync(GetIpamArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetIpamResult>("bytepluscc:vpc/getIpam:getIpam", args ?? new GetIpamArgs(), options.WithDefaults());

        /// <summary>
        /// Data Source schema for Byteplus::VPC::IPAM
        /// </summary>
        public static Output<GetIpamResult> Invoke(GetIpamInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetIpamResult>("bytepluscc:vpc/getIpam:getIpam", args ?? new GetIpamInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Data Source schema for Byteplus::VPC::IPAM
        /// </summary>
        public static Output<GetIpamResult> Invoke(GetIpamInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetIpamResult>("bytepluscc:vpc/getIpam:getIpam", args ?? new GetIpamInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetIpamArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Uniquely identifies the resource.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetIpamArgs()
        {
        }
        public static new GetIpamArgs Empty => new GetIpamArgs();
    }

    public sealed class GetIpamInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Uniquely identifies the resource.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetIpamInvokeArgs()
        {
        }
        public static new GetIpamInvokeArgs Empty => new GetIpamInvokeArgs();
    }


    [OutputType]
    public sealed class GetIpamResult
    {
        /// <summary>
        /// Account ID
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// Creation Time
        /// </summary>
        public readonly string CreateTime;
        /// <summary>
        /// Default Resource Discovery Association ID
        /// </summary>
        public readonly string DefaultResourceDiscoveryAssociationId;
        /// <summary>
        /// Default Resource Discovery Instance ID
        /// </summary>
        public readonly string DefaultResourceDiscoveryId;
        /// <summary>
        /// Description
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Uniquely identifies the resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// IPAM ID
        /// </summary>
        public readonly string IpamId;
        /// <summary>
        /// IPAM Name
        /// </summary>
        public readonly string IpamName;
        /// <summary>
        /// Region ID
        /// </summary>
        public readonly string IpamRegionId;
        /// <summary>
        /// IPAM Effective Region
        /// </summary>
        public readonly ImmutableArray<string> OperatingRegions;
        /// <summary>
        /// System Default Created Private IPAM Scope
        /// </summary>
        public readonly string PrivateDefaultScopeId;
        /// <summary>
        /// Project Name
        /// </summary>
        public readonly string ProjectName;
        /// <summary>
        /// System Default Created Public IPAM Scope
        /// </summary>
        public readonly string PublicDefaultScopeId;
        /// <summary>
        /// Resource Discovery Association Count
        /// </summary>
        public readonly int ResourceDiscoveryAssociationCount;
        /// <summary>
        /// IPAM Scope Count
        /// </summary>
        public readonly int ScopeCount;
        /// <summary>
        /// IPAM Status
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// IPAM Tag Information
        /// </summary>
        public readonly ImmutableArray<Outputs.GetIpamTagResult> Tags;
        /// <summary>
        /// Update Time
        /// </summary>
        public readonly string UpdateTime;

        [OutputConstructor]
        private GetIpamResult(
            string accountId,

            string createTime,

            string defaultResourceDiscoveryAssociationId,

            string defaultResourceDiscoveryId,

            string description,

            string id,

            string ipamId,

            string ipamName,

            string ipamRegionId,

            ImmutableArray<string> operatingRegions,

            string privateDefaultScopeId,

            string projectName,

            string publicDefaultScopeId,

            int resourceDiscoveryAssociationCount,

            int scopeCount,

            string status,

            ImmutableArray<Outputs.GetIpamTagResult> tags,

            string updateTime)
        {
            AccountId = accountId;
            CreateTime = createTime;
            DefaultResourceDiscoveryAssociationId = defaultResourceDiscoveryAssociationId;
            DefaultResourceDiscoveryId = defaultResourceDiscoveryId;
            Description = description;
            Id = id;
            IpamId = ipamId;
            IpamName = ipamName;
            IpamRegionId = ipamRegionId;
            OperatingRegions = operatingRegions;
            PrivateDefaultScopeId = privateDefaultScopeId;
            ProjectName = projectName;
            PublicDefaultScopeId = publicDefaultScopeId;
            ResourceDiscoveryAssociationCount = resourceDiscoveryAssociationCount;
            ScopeCount = scopeCount;
            Status = status;
            Tags = tags;
            UpdateTime = updateTime;
        }
    }
}
