// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Vpc
{
    public static class GetIpv4Gateways
    {
        /// <summary>
        /// Plural Data Source schema for Byteplus::VPC::Ipv4Gateway
        /// </summary>
        public static Task<GetIpv4GatewaysResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetIpv4GatewaysResult>("bytepluscc:vpc/getIpv4Gateways:getIpv4Gateways", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::VPC::Ipv4Gateway
        /// </summary>
        public static Output<GetIpv4GatewaysResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetIpv4GatewaysResult>("bytepluscc:vpc/getIpv4Gateways:getIpv4Gateways", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Plural Data Source schema for Byteplus::VPC::Ipv4Gateway
        /// </summary>
        public static Output<GetIpv4GatewaysResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetIpv4GatewaysResult>("bytepluscc:vpc/getIpv4Gateways:getIpv4Gateways", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetIpv4GatewaysResult
    {
        /// <summary>
        /// Uniquely identifies the data source.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of Resource Identifiers.
        /// </summary>
        public readonly ImmutableArray<string> Ids;

        [OutputConstructor]
        private GetIpv4GatewaysResult(
            string id,

            ImmutableArray<string> ids)
        {
            Id = id;
            Ids = ids;
        }
    }
}
