// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace config {
    export interface AssumeRole {
        /**
         * he TRN of the role to assume.
         */
        assumeRoleTrn: string;
        /**
         * The duration of the session when making the AssumeRole call. Its value ranges from 900 to 43200(seconds), and default is 3600 seconds.
         */
        durationSeconds?: number;
        /**
         * A more restrictive policy when making the AssumeRole call
         */
        policy?: string;
    }

    export interface Endpoints {
        /**
         * Use this to override the default Cloud Control API service endpoint URL
         */
        cloudcontrolapi?: string;
        /**
         * Use this to override the default STS service endpoint URL
         */
        sts?: string;
    }

}

export namespace ecs {
    export interface GetImageDetectionResults {
        /**
         * 检测状态。可以选择Finished（已完成）、Processing（处理中）类型。
         */
        detectionStatus: string;
        /**
         * 镜像检测项详情。
         */
        items: outputs.ecs.GetImageDetectionResultsItem[];
    }

    export interface GetImageDetectionResultsItem {
        /**
         * 检测项名称。
         */
        name: string;
        /**
         * 该检测项对应结果。
         */
        result: string;
        /**
         * 风险描述码。
         */
        riskCode: string;
        /**
         * 风险等级。若该参数返回值为空，表示无风险。
         */
        riskLevel: string;
    }

    export interface GetImageSnapshot {
        /**
         * 快照大小。单位为GiB。
         */
        size: number;
        /**
         * 快照ID。
         */
        snapshotId: string;
        /**
         * 云盘种类。system：系统盘。data：数据盘。
         */
        volumeKind: string;
    }

    export interface GetImageTag {
        /**
         * 镜像标签的标签键。
         */
        key: string;
        /**
         * 镜像标签的值。
         */
        value: string;
    }

    export interface ImageDetectionResults {
        /**
         * 检测状态。可以选择Finished（已完成）、Processing（处理中）类型。
         */
        detectionStatus: string;
        items: outputs.ecs.ImageDetectionResultsItem[];
    }

    export interface ImageDetectionResultsItem {
        /**
         * 检测项名称。
         */
        name: string;
        /**
         * 该检测项对应结果。
         */
        result: string;
        /**
         * 风险描述码。
         */
        riskCode: string;
        /**
         * 风险等级。若该参数返回值为空，表示无风险。
         */
        riskLevel: string;
    }

    export interface ImageSnapshot {
        /**
         * 快照大小。单位为GiB。
         */
        size: number;
        /**
         * 快照ID。
         */
        snapshotId: string;
        /**
         * 云盘种类。system：系统盘。data：数据盘。
         */
        volumeKind: string;
    }

    export interface ImageTag {
        /**
         * 镜像标签的标签键。
         */
        key: string;
        /**
         * 镜像标签的值。
         */
        value: string;
    }

}
