// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Byteplus.Pulumi.Bytepluscc.Ecs.Outputs
{

    [OutputType]
    public sealed class DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType
    {
        /// <summary>
        /// Number of instances of this type that can still be created in the dedicated host cluster.
        /// </summary>
        public readonly int? AvailableCapacity;
        /// <summary>
        /// Instance type.
        /// </summary>
        public readonly string? InstanceType;

        [OutputConstructor]
        private DedicatedHostClusterDedicatedHostClusterCapacityAvailableInstanceType(
            int? availableCapacity,

            string? instanceType)
        {
            AvailableCapacity = availableCapacity;
            InstanceType = instanceType;
        }
    }
}
