// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Plural Data Source schema for Byteplus::VPC::NetworkAcl
 */
export function getNetworkAcls(opts?: pulumi.InvokeOptions): Promise<GetNetworkAclsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytepluscc:vpc/getNetworkAcls:getNetworkAcls", {
    }, opts);
}

/**
 * A collection of values returned by getNetworkAcls.
 */
export interface GetNetworkAclsResult {
    /**
     * Uniquely identifies the data source.
     */
    readonly id: string;
    /**
     * Set of Resource Identifiers.
     */
    readonly ids: string[];
}
/**
 * Plural Data Source schema for Byteplus::VPC::NetworkAcl
 */
export function getNetworkAclsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkAclsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytepluscc:vpc/getNetworkAcls:getNetworkAcls", {
    }, opts);
}
