// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * IPAM。
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as bytepluscc from "@byteplus/pulumi-bytepluscc";
 *
 * const example = new bytepluscc.vpc.Ipam("example", {
 *     operatingRegions: ["cn-beijing"],
 *     projectName: "default",
 *     ipamName: "tf-ipam-full",
 *     description: "created by terraform full case",
 *     tags: [
 *         {
 *             key: "case",
 *             value: "tf-c02",
 *         },
 *         {
 *             key: "env",
 *             value: "terraform",
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import bytepluscc:vpc/ipam:Ipam example "ipam_id"
 * ```
 */
export class Ipam extends pulumi.CustomResource {
    /**
     * Get an existing Ipam resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpamState, opts?: pulumi.CustomResourceOptions): Ipam {
        return new Ipam(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bytepluscc:vpc/ipam:Ipam';

    /**
     * Returns true if the given object is an instance of Ipam.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ipam {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ipam.__pulumiType;
    }

    /**
     * Account ID
     */
    declare public /*out*/ readonly accountId: pulumi.Output<string>;
    /**
     * Creation Time
     */
    declare public /*out*/ readonly createTime: pulumi.Output<string>;
    /**
     * Default Resource Discovery Association ID
     */
    declare public /*out*/ readonly defaultResourceDiscoveryAssociationId: pulumi.Output<string>;
    /**
     * Default Resource Discovery Instance ID
     */
    declare public /*out*/ readonly defaultResourceDiscoveryId: pulumi.Output<string>;
    /**
     * Description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * IPAM ID
     */
    declare public /*out*/ readonly ipamId: pulumi.Output<string>;
    /**
     * IPAM Name
     */
    declare public readonly ipamName: pulumi.Output<string>;
    /**
     * Region ID
     */
    declare public /*out*/ readonly ipamRegionId: pulumi.Output<string>;
    /**
     * IPAM Effective Region
     */
    declare public readonly operatingRegions: pulumi.Output<string[]>;
    /**
     * System Default Created Private IPAM Scope
     */
    declare public /*out*/ readonly privateDefaultScopeId: pulumi.Output<string>;
    /**
     * Project Name
     */
    declare public readonly projectName: pulumi.Output<string>;
    /**
     * System Default Created Public IPAM Scope
     */
    declare public /*out*/ readonly publicDefaultScopeId: pulumi.Output<string>;
    /**
     * Resource Discovery Association Count
     */
    declare public /*out*/ readonly resourceDiscoveryAssociationCount: pulumi.Output<number>;
    /**
     * IPAM Scope Count
     */
    declare public /*out*/ readonly scopeCount: pulumi.Output<number>;
    /**
     * IPAM Status
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * IPAM Tag Information
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    declare public readonly tags: pulumi.Output<outputs.vpc.IpamTag[]>;
    /**
     * Update Time
     */
    declare public /*out*/ readonly updateTime: pulumi.Output<string>;

    /**
     * Create a Ipam resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpamArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpamArgs | IpamState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpamState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["createTime"] = state?.createTime;
            resourceInputs["defaultResourceDiscoveryAssociationId"] = state?.defaultResourceDiscoveryAssociationId;
            resourceInputs["defaultResourceDiscoveryId"] = state?.defaultResourceDiscoveryId;
            resourceInputs["description"] = state?.description;
            resourceInputs["ipamId"] = state?.ipamId;
            resourceInputs["ipamName"] = state?.ipamName;
            resourceInputs["ipamRegionId"] = state?.ipamRegionId;
            resourceInputs["operatingRegions"] = state?.operatingRegions;
            resourceInputs["privateDefaultScopeId"] = state?.privateDefaultScopeId;
            resourceInputs["projectName"] = state?.projectName;
            resourceInputs["publicDefaultScopeId"] = state?.publicDefaultScopeId;
            resourceInputs["resourceDiscoveryAssociationCount"] = state?.resourceDiscoveryAssociationCount;
            resourceInputs["scopeCount"] = state?.scopeCount;
            resourceInputs["status"] = state?.status;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["updateTime"] = state?.updateTime;
        } else {
            const args = argsOrState as IpamArgs | undefined;
            if (args?.operatingRegions === undefined && !opts.urn) {
                throw new Error("Missing required property 'operatingRegions'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["ipamName"] = args?.ipamName;
            resourceInputs["operatingRegions"] = args?.operatingRegions;
            resourceInputs["projectName"] = args?.projectName;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["accountId"] = undefined /*out*/;
            resourceInputs["createTime"] = undefined /*out*/;
            resourceInputs["defaultResourceDiscoveryAssociationId"] = undefined /*out*/;
            resourceInputs["defaultResourceDiscoveryId"] = undefined /*out*/;
            resourceInputs["ipamId"] = undefined /*out*/;
            resourceInputs["ipamRegionId"] = undefined /*out*/;
            resourceInputs["privateDefaultScopeId"] = undefined /*out*/;
            resourceInputs["publicDefaultScopeId"] = undefined /*out*/;
            resourceInputs["resourceDiscoveryAssociationCount"] = undefined /*out*/;
            resourceInputs["scopeCount"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updateTime"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Ipam.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Ipam resources.
 */
export interface IpamState {
    /**
     * Account ID
     */
    accountId?: pulumi.Input<string | undefined>;
    /**
     * Creation Time
     */
    createTime?: pulumi.Input<string | undefined>;
    /**
     * Default Resource Discovery Association ID
     */
    defaultResourceDiscoveryAssociationId?: pulumi.Input<string | undefined>;
    /**
     * Default Resource Discovery Instance ID
     */
    defaultResourceDiscoveryId?: pulumi.Input<string | undefined>;
    /**
     * Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * IPAM ID
     */
    ipamId?: pulumi.Input<string | undefined>;
    /**
     * IPAM Name
     */
    ipamName?: pulumi.Input<string | undefined>;
    /**
     * Region ID
     */
    ipamRegionId?: pulumi.Input<string | undefined>;
    /**
     * IPAM Effective Region
     */
    operatingRegions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * System Default Created Private IPAM Scope
     */
    privateDefaultScopeId?: pulumi.Input<string | undefined>;
    /**
     * Project Name
     */
    projectName?: pulumi.Input<string | undefined>;
    /**
     * System Default Created Public IPAM Scope
     */
    publicDefaultScopeId?: pulumi.Input<string | undefined>;
    /**
     * Resource Discovery Association Count
     */
    resourceDiscoveryAssociationCount?: pulumi.Input<number | undefined>;
    /**
     * IPAM Scope Count
     */
    scopeCount?: pulumi.Input<number | undefined>;
    /**
     * IPAM Status
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * IPAM Tag Information
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.vpc.IpamTag>[] | undefined>;
    /**
     * Update Time
     */
    updateTime?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Ipam resource.
 */
export interface IpamArgs {
    /**
     * Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * IPAM Name
     */
    ipamName?: pulumi.Input<string | undefined>;
    /**
     * IPAM Effective Region
     */
    operatingRegions: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Project Name
     */
    projectName?: pulumi.Input<string | undefined>;
    /**
     * IPAM Tag Information
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.vpc.IpamTag>[] | undefined>;
}
