// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.transitrouter;

import com.byteplus.bytepluscc.Utilities;
import com.byteplus.bytepluscc.transitrouter.TransitRouterForwardPolicyTableArgs;
import com.byteplus.bytepluscc.transitrouter.inputs.TransitRouterForwardPolicyTableState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * Forwarding policy for the transit router. The forwarding policy controls the forwarding behavior of the transit router.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.byteplus.bytepluscc.transitrouter.TransitRouterForwardPolicyTable;
 * import com.byteplus.bytepluscc.transitrouter.TransitRouterForwardPolicyTableArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new TransitRouterForwardPolicyTable("example", TransitRouterForwardPolicyTableArgs.builder()
 *             .transitRouterId("tr-xxxxxx")
 *             .transitRouterForwardPolicyTableName("ccapi-forward-policy-table-full")
 *             .description("transit router forward policy table full fields")
 *             .transitRouterAttachmentIds("attachment_id-xxxx")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import bytepluscc:transitrouter/transitRouterForwardPolicyTable:TransitRouterForwardPolicyTable example &#34;transit_router_id|transit_router_forward_policy_table_id&#34;
 * ```
 * 
 */
@ResourceType(type="bytepluscc:transitrouter/transitRouterForwardPolicyTable:TransitRouterForwardPolicyTable")
public class TransitRouterForwardPolicyTable extends com.pulumi.resources.CustomResource {
    /**
     * Creation time of the forwarding policy.
     * 
     */
    @Export(name="creationTime", refs={String.class}, tree="[0]")
    private Output<String> creationTime;

    /**
     * @return Creation time of the forwarding policy.
     * 
     */
    public Output<String> creationTime() {
        return this.creationTime;
    }
    /**
     * Description of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length limit: 0–255 characters.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return Description of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: comma (,), period (.), underscore (_), space ( ), equals sign (=), hyphen (-), Chinese comma (，), and Chinese period (。). Length limit: 0–255 characters.
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * Status of the forwarding policy. Creating: Being created. Deleting: Being deleted. Pending: Being configured. Available: Available.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Status of the forwarding policy. Creating: Being created. Deleting: Being deleted. Pending: Being configured. Available: Available.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * List of associated IDs for the transit router instance.
     * 
     */
    @Export(name="transitRouterAttachmentIds", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> transitRouterAttachmentIds;

    /**
     * @return List of associated IDs for the transit router instance.
     * 
     */
    public Output<List<String>> transitRouterAttachmentIds() {
        return this.transitRouterAttachmentIds;
    }
    /**
     * Forwarding policy ID.
     * 
     */
    @Export(name="transitRouterForwardPolicyTableId", refs={String.class}, tree="[0]")
    private Output<String> transitRouterForwardPolicyTableId;

    /**
     * @return Forwarding policy ID.
     * 
     */
    public Output<String> transitRouterForwardPolicyTableId() {
        return this.transitRouterForwardPolicyTableId;
    }
    /**
     * Name of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length limit: 1–128 characters. If this parameter is not provided or no value is specified, the forwarding policy ID is used by default.
     * 
     */
    @Export(name="transitRouterForwardPolicyTableName", refs={String.class}, tree="[0]")
    private Output<String> transitRouterForwardPolicyTableName;

    /**
     * @return Name of the forwarding policy. Must start with a letter, number, or Chinese character. Can include letters, numbers, Chinese characters, and the following special characters: period (.), underscore (_), and hyphen (-). Length limit: 1–128 characters. If this parameter is not provided or no value is specified, the forwarding policy ID is used by default.
     * 
     */
    public Output<String> transitRouterForwardPolicyTableName() {
        return this.transitRouterForwardPolicyTableName;
    }
    /**
     * Transit router instance ID.
     * 
     */
    @Export(name="transitRouterId", refs={String.class}, tree="[0]")
    private Output<String> transitRouterId;

    /**
     * @return Transit router instance ID.
     * 
     */
    public Output<String> transitRouterId() {
        return this.transitRouterId;
    }
    /**
     * Last operation time of the forwarding policy.
     * 
     */
    @Export(name="updateTime", refs={String.class}, tree="[0]")
    private Output<String> updateTime;

    /**
     * @return Last operation time of the forwarding policy.
     * 
     */
    public Output<String> updateTime() {
        return this.updateTime;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TransitRouterForwardPolicyTable(java.lang.String name) {
        this(name, TransitRouterForwardPolicyTableArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TransitRouterForwardPolicyTable(java.lang.String name, TransitRouterForwardPolicyTableArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TransitRouterForwardPolicyTable(java.lang.String name, TransitRouterForwardPolicyTableArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:transitrouter/transitRouterForwardPolicyTable:TransitRouterForwardPolicyTable", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private TransitRouterForwardPolicyTable(java.lang.String name, Output<java.lang.String> id, @Nullable TransitRouterForwardPolicyTableState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:transitrouter/transitRouterForwardPolicyTable:TransitRouterForwardPolicyTable", name, state, makeResourceOptions(options, id), false);
    }

    private static TransitRouterForwardPolicyTableArgs makeArgs(TransitRouterForwardPolicyTableArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TransitRouterForwardPolicyTableArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/byteplus-sdk")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TransitRouterForwardPolicyTable get(java.lang.String name, Output<java.lang.String> id, @Nullable TransitRouterForwardPolicyTableState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TransitRouterForwardPolicyTable(name, id, state, options);
    }
}
