// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kafka

import (
	"context"
	"reflect"

	"errors"
	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Kafka ACL rule used to control permissions for specified SASL users to access Topic or Group resources from specified IPs.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/kafka"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := kafka.NewAcl(ctx, "example", &kafka.AclArgs{
//				InstanceId:   pulumi.String("kafka-xxxxxx"),
//				UserName:     pulumi.String("*"),
//				Ip:           pulumi.String("*"),
//				ResourceType: pulumi.String("Topic"),
//				PatternType:  pulumi.String("Literal"),
//				Resource:     pulumi.String("*"),
//				AccessPolicy: pulumi.String("Write"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import bytepluscc:kafka/acl:Acl example "instance_id|user_name|ip|resource_type|pattern_type|resource|access_policy"
// ```
type Acl struct {
	pulumi.CustomResourceState

	// Access policy for the rule. Read grants read permission; Write grants write permission. Only one value is allowed—if multiple are provided, only the first takes effect.
	AccessPolicy pulumi.StringOutput `pulumi:"accessPolicy"`
	// Instance ID for the ACL to be created.
	InstanceId pulumi.StringOutput `pulumi:"instanceId"`
	// IP address or subnet allowed by the rule. Supports specifying '*', which allows access from any IP. Separate multiple IPs with ','.
	Ip pulumi.StringOutput `pulumi:"ip"`
	// Rule matching method. Literal: exact match; Prefixed: prefix match.
	PatternType pulumi.StringOutput `pulumi:"patternType"`
	// Name or prefix of the Topic or Group resource bound to the rule.
	Resource pulumi.StringOutput `pulumi:"resource"`
	// Resource type bound to the rule. Supports configuring 'Topic' or 'Group'.
	ResourceType pulumi.StringOutput `pulumi:"resourceType"`
	// SASL users allowed by the rule. Supports specifying '*', which allows access for any user.
	UserName pulumi.StringOutput `pulumi:"userName"`
}

// NewAcl registers a new resource with the given unique name, arguments, and options.
func NewAcl(ctx *pulumi.Context,
	name string, args *AclArgs, opts ...pulumi.ResourceOption) (*Acl, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccessPolicy == nil {
		return nil, errors.New("invalid value for required argument 'AccessPolicy'")
	}
	if args.InstanceId == nil {
		return nil, errors.New("invalid value for required argument 'InstanceId'")
	}
	if args.Ip == nil {
		return nil, errors.New("invalid value for required argument 'Ip'")
	}
	if args.PatternType == nil {
		return nil, errors.New("invalid value for required argument 'PatternType'")
	}
	if args.Resource == nil {
		return nil, errors.New("invalid value for required argument 'Resource'")
	}
	if args.ResourceType == nil {
		return nil, errors.New("invalid value for required argument 'ResourceType'")
	}
	if args.UserName == nil {
		return nil, errors.New("invalid value for required argument 'UserName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Acl
	err := ctx.RegisterResource("bytepluscc:kafka/acl:Acl", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAcl gets an existing Acl resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAcl(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AclState, opts ...pulumi.ResourceOption) (*Acl, error) {
	var resource Acl
	err := ctx.ReadResource("bytepluscc:kafka/acl:Acl", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Acl resources.
type aclState struct {
	// Access policy for the rule. Read grants read permission; Write grants write permission. Only one value is allowed—if multiple are provided, only the first takes effect.
	AccessPolicy *string `pulumi:"accessPolicy"`
	// Instance ID for the ACL to be created.
	InstanceId *string `pulumi:"instanceId"`
	// IP address or subnet allowed by the rule. Supports specifying '*', which allows access from any IP. Separate multiple IPs with ','.
	Ip *string `pulumi:"ip"`
	// Rule matching method. Literal: exact match; Prefixed: prefix match.
	PatternType *string `pulumi:"patternType"`
	// Name or prefix of the Topic or Group resource bound to the rule.
	Resource *string `pulumi:"resource"`
	// Resource type bound to the rule. Supports configuring 'Topic' or 'Group'.
	ResourceType *string `pulumi:"resourceType"`
	// SASL users allowed by the rule. Supports specifying '*', which allows access for any user.
	UserName *string `pulumi:"userName"`
}

type AclState struct {
	// Access policy for the rule. Read grants read permission; Write grants write permission. Only one value is allowed—if multiple are provided, only the first takes effect.
	AccessPolicy pulumi.StringPtrInput
	// Instance ID for the ACL to be created.
	InstanceId pulumi.StringPtrInput
	// IP address or subnet allowed by the rule. Supports specifying '*', which allows access from any IP. Separate multiple IPs with ','.
	Ip pulumi.StringPtrInput
	// Rule matching method. Literal: exact match; Prefixed: prefix match.
	PatternType pulumi.StringPtrInput
	// Name or prefix of the Topic or Group resource bound to the rule.
	Resource pulumi.StringPtrInput
	// Resource type bound to the rule. Supports configuring 'Topic' or 'Group'.
	ResourceType pulumi.StringPtrInput
	// SASL users allowed by the rule. Supports specifying '*', which allows access for any user.
	UserName pulumi.StringPtrInput
}

func (AclState) ElementType() reflect.Type {
	return reflect.TypeOf((*aclState)(nil)).Elem()
}

type aclArgs struct {
	// Access policy for the rule. Read grants read permission; Write grants write permission. Only one value is allowed—if multiple are provided, only the first takes effect.
	AccessPolicy string `pulumi:"accessPolicy"`
	// Instance ID for the ACL to be created.
	InstanceId string `pulumi:"instanceId"`
	// IP address or subnet allowed by the rule. Supports specifying '*', which allows access from any IP. Separate multiple IPs with ','.
	Ip string `pulumi:"ip"`
	// Rule matching method. Literal: exact match; Prefixed: prefix match.
	PatternType string `pulumi:"patternType"`
	// Name or prefix of the Topic or Group resource bound to the rule.
	Resource string `pulumi:"resource"`
	// Resource type bound to the rule. Supports configuring 'Topic' or 'Group'.
	ResourceType string `pulumi:"resourceType"`
	// SASL users allowed by the rule. Supports specifying '*', which allows access for any user.
	UserName string `pulumi:"userName"`
}

// The set of arguments for constructing a Acl resource.
type AclArgs struct {
	// Access policy for the rule. Read grants read permission; Write grants write permission. Only one value is allowed—if multiple are provided, only the first takes effect.
	AccessPolicy pulumi.StringInput
	// Instance ID for the ACL to be created.
	InstanceId pulumi.StringInput
	// IP address or subnet allowed by the rule. Supports specifying '*', which allows access from any IP. Separate multiple IPs with ','.
	Ip pulumi.StringInput
	// Rule matching method. Literal: exact match; Prefixed: prefix match.
	PatternType pulumi.StringInput
	// Name or prefix of the Topic or Group resource bound to the rule.
	Resource pulumi.StringInput
	// Resource type bound to the rule. Supports configuring 'Topic' or 'Group'.
	ResourceType pulumi.StringInput
	// SASL users allowed by the rule. Supports specifying '*', which allows access for any user.
	UserName pulumi.StringInput
}

func (AclArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*aclArgs)(nil)).Elem()
}

type AclInput interface {
	pulumi.Input

	ToAclOutput() AclOutput
	ToAclOutputWithContext(ctx context.Context) AclOutput
}

func (*Acl) ElementType() reflect.Type {
	return reflect.TypeOf((**Acl)(nil)).Elem()
}

func (i *Acl) ToAclOutput() AclOutput {
	return i.ToAclOutputWithContext(context.Background())
}

func (i *Acl) ToAclOutputWithContext(ctx context.Context) AclOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AclOutput)
}

// AclArrayInput is an input type that accepts AclArray and AclArrayOutput values.
// You can construct a concrete instance of `AclArrayInput` via:
//
//	AclArray{ AclArgs{...} }
type AclArrayInput interface {
	pulumi.Input

	ToAclArrayOutput() AclArrayOutput
	ToAclArrayOutputWithContext(context.Context) AclArrayOutput
}

type AclArray []AclInput

func (AclArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Acl)(nil)).Elem()
}

func (i AclArray) ToAclArrayOutput() AclArrayOutput {
	return i.ToAclArrayOutputWithContext(context.Background())
}

func (i AclArray) ToAclArrayOutputWithContext(ctx context.Context) AclArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AclArrayOutput)
}

// AclMapInput is an input type that accepts AclMap and AclMapOutput values.
// You can construct a concrete instance of `AclMapInput` via:
//
//	AclMap{ "key": AclArgs{...} }
type AclMapInput interface {
	pulumi.Input

	ToAclMapOutput() AclMapOutput
	ToAclMapOutputWithContext(context.Context) AclMapOutput
}

type AclMap map[string]AclInput

func (AclMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Acl)(nil)).Elem()
}

func (i AclMap) ToAclMapOutput() AclMapOutput {
	return i.ToAclMapOutputWithContext(context.Background())
}

func (i AclMap) ToAclMapOutputWithContext(ctx context.Context) AclMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AclMapOutput)
}

type AclOutput struct{ *pulumi.OutputState }

func (AclOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Acl)(nil)).Elem()
}

func (o AclOutput) ToAclOutput() AclOutput {
	return o
}

func (o AclOutput) ToAclOutputWithContext(ctx context.Context) AclOutput {
	return o
}

// Access policy for the rule. Read grants read permission; Write grants write permission. Only one value is allowed—if multiple are provided, only the first takes effect.
func (o AclOutput) AccessPolicy() pulumi.StringOutput {
	return o.ApplyT(func(v *Acl) pulumi.StringOutput { return v.AccessPolicy }).(pulumi.StringOutput)
}

// Instance ID for the ACL to be created.
func (o AclOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *Acl) pulumi.StringOutput { return v.InstanceId }).(pulumi.StringOutput)
}

// IP address or subnet allowed by the rule. Supports specifying '*', which allows access from any IP. Separate multiple IPs with ','.
func (o AclOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v *Acl) pulumi.StringOutput { return v.Ip }).(pulumi.StringOutput)
}

// Rule matching method. Literal: exact match; Prefixed: prefix match.
func (o AclOutput) PatternType() pulumi.StringOutput {
	return o.ApplyT(func(v *Acl) pulumi.StringOutput { return v.PatternType }).(pulumi.StringOutput)
}

// Name or prefix of the Topic or Group resource bound to the rule.
func (o AclOutput) Resource() pulumi.StringOutput {
	return o.ApplyT(func(v *Acl) pulumi.StringOutput { return v.Resource }).(pulumi.StringOutput)
}

// Resource type bound to the rule. Supports configuring 'Topic' or 'Group'.
func (o AclOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *Acl) pulumi.StringOutput { return v.ResourceType }).(pulumi.StringOutput)
}

// SASL users allowed by the rule. Supports specifying '*', which allows access for any user.
func (o AclOutput) UserName() pulumi.StringOutput {
	return o.ApplyT(func(v *Acl) pulumi.StringOutput { return v.UserName }).(pulumi.StringOutput)
}

type AclArrayOutput struct{ *pulumi.OutputState }

func (AclArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Acl)(nil)).Elem()
}

func (o AclArrayOutput) ToAclArrayOutput() AclArrayOutput {
	return o
}

func (o AclArrayOutput) ToAclArrayOutputWithContext(ctx context.Context) AclArrayOutput {
	return o
}

func (o AclArrayOutput) Index(i pulumi.IntInput) AclOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Acl {
		return vs[0].([]*Acl)[vs[1].(int)]
	}).(AclOutput)
}

type AclMapOutput struct{ *pulumi.OutputState }

func (AclMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Acl)(nil)).Elem()
}

func (o AclMapOutput) ToAclMapOutput() AclMapOutput {
	return o
}

func (o AclMapOutput) ToAclMapOutputWithContext(ctx context.Context) AclMapOutput {
	return o
}

func (o AclMapOutput) MapIndex(k pulumi.StringInput) AclOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Acl {
		return vs[0].(map[string]*Acl)[vs[1].(string)]
	}).(AclOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AclInput)(nil)).Elem(), &Acl{})
	pulumi.RegisterInputType(reflect.TypeOf((*AclArrayInput)(nil)).Elem(), AclArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AclMapInput)(nil)).Elem(), AclMap{})
	pulumi.RegisterOutputType(AclOutput{})
	pulumi.RegisterOutputType(AclArrayOutput{})
	pulumi.RegisterOutputType(AclMapOutput{})
}
