// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bmq

import (
	"context"
	"reflect"

	"github.com/byteplus-sdk/pulumi-bytepluscc/sdk/go/bytepluscc/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Data Source schema for Byteplus::BMQ::Instance
func LookupInstance(ctx *pulumi.Context, args *LookupInstanceArgs, opts ...pulumi.InvokeOption) (*LookupInstanceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupInstanceResult
	err := ctx.Invoke("bytepluscc:bmq/getInstance:getInstance", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstance.
type LookupInstanceArgs struct {
	// Uniquely identifies the resource.
	Id string `pulumi:"id"`
}

// A collection of values returned by getInstance.
type LookupInstanceResult struct {
	// Whether to enable auto-renewal. Possible values: true: Enable auto-renewal. false: Disable auto-renewal
	AutoRenew string `pulumi:"autoRenew"`
	// Unit of purchase duration. Possible values: MONTHLY: Monthly purchase. YEARLY: Annual purchase
	BillingPeriod string `pulumi:"billingPeriod"`
	// Instance billing method. Possible values: POST: Pay-as-you-go. MIX: Subscription
	BillingType string `pulumi:"billingType"`
	// Instance creation time
	CreatedTime string `pulumi:"createdTime"`
	// Instance description statement
	Description string `pulumi:"description"`
	// Whether public access is enabled for the instance. To enable public access, configure the public IP ID in the same region
	EipId string `pulumi:"eipId"`
	// Response data for all instance endpoints
	Endpoints GetInstanceEndpoints `pulumi:"endpoints"`
	// Instance expiration time
	ExpirationTime string `pulumi:"expirationTime"`
	// Maximum number of consumer groups per instance
	GroupLimit int `pulumi:"groupLimit"`
	// Uniquely identifies the resource.
	Id string `pulumi:"id"`
	// Instance ID
	InstanceId string `pulumi:"instanceId"`
	// Message retention period for all topics under the instance, in hours
	MessageRetention int `pulumi:"messageRetention"`
	// Set a custom name for the BMQ instance. Constraints: Use lowercase letters, numbers, and hyphens (-). Length: 1–64 characters
	Name string `pulumi:"name"`
	// Maximum number of partitions per instance
	PartitionLimit int `pulumi:"partitionLimit"`
	// Project name to which the instance belongs
	ProjectName string `pulumi:"projectName"`
	// Instance resource tag list
	ResourceTags []GetInstanceResourceTag `pulumi:"resourceTags"`
	// Instance resource statistics response data
	Resources GetInstanceResources `pulumi:"resources"`
	// List of security groups used by the instance
	SecurityGroupIdLists []string `pulumi:"securityGroupIdLists"`
	// Instance specification
	Specification string `pulumi:"specification"`
	// Instance status. Possible values: INITIALIZING: Initializing, INITIALIZATION*FAILED: Initialization failed, RUNNING: Running, MODIFYING: Updating, MODIFY*FAILED: Update failed, RELEASING: Releasing, STOPPING: Stopping, STOPPED: Stopped, RECOVERING: Recovering, EXCEPTION: Exception, CAPACITY*EXPAXION*FAILED: Capacity expansion failed, EXPANDING*CAPACITY: Expanding capacity, CANCEL*EXPANDING_CAPACITY: Canceling capacity expansion, RESTARTING: Restarting, UNPAID: Unpaid
	Status string `pulumi:"status"`
	// List of subnets used by the instance
	SubnetIdLists []string `pulumi:"subnetIdLists"`
	// Instance resource tag list
	Tags []GetInstanceTag `pulumi:"tags"`
	// Purchase duration for subscription instances, in months
	Times int `pulumi:"times"`
	// Maximum number of topics per instance
	TopicLimit int `pulumi:"topicLimit"`
	// VPC ID where the instance is located
	VpcId string `pulumi:"vpcId"`
	// List of availability zones where the instance is located
	ZoneIdLists []string `pulumi:"zoneIdLists"`
}

func LookupInstanceOutput(ctx *pulumi.Context, args LookupInstanceOutputArgs, opts ...pulumi.InvokeOption) LookupInstanceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupInstanceResultOutput, error) {
			args := v.(LookupInstanceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("bytepluscc:bmq/getInstance:getInstance", args, LookupInstanceResultOutput{}, options).(LookupInstanceResultOutput), nil
		}).(LookupInstanceResultOutput)
}

// A collection of arguments for invoking getInstance.
type LookupInstanceOutputArgs struct {
	// Uniquely identifies the resource.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupInstanceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceArgs)(nil)).Elem()
}

// A collection of values returned by getInstance.
type LookupInstanceResultOutput struct{ *pulumi.OutputState }

func (LookupInstanceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceResult)(nil)).Elem()
}

func (o LookupInstanceResultOutput) ToLookupInstanceResultOutput() LookupInstanceResultOutput {
	return o
}

func (o LookupInstanceResultOutput) ToLookupInstanceResultOutputWithContext(ctx context.Context) LookupInstanceResultOutput {
	return o
}

// Whether to enable auto-renewal. Possible values: true: Enable auto-renewal. false: Disable auto-renewal
func (o LookupInstanceResultOutput) AutoRenew() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.AutoRenew }).(pulumi.StringOutput)
}

// Unit of purchase duration. Possible values: MONTHLY: Monthly purchase. YEARLY: Annual purchase
func (o LookupInstanceResultOutput) BillingPeriod() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.BillingPeriod }).(pulumi.StringOutput)
}

// Instance billing method. Possible values: POST: Pay-as-you-go. MIX: Subscription
func (o LookupInstanceResultOutput) BillingType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.BillingType }).(pulumi.StringOutput)
}

// Instance creation time
func (o LookupInstanceResultOutput) CreatedTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.CreatedTime }).(pulumi.StringOutput)
}

// Instance description statement
func (o LookupInstanceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Description }).(pulumi.StringOutput)
}

// Whether public access is enabled for the instance. To enable public access, configure the public IP ID in the same region
func (o LookupInstanceResultOutput) EipId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.EipId }).(pulumi.StringOutput)
}

// Response data for all instance endpoints
func (o LookupInstanceResultOutput) Endpoints() GetInstanceEndpointsOutput {
	return o.ApplyT(func(v LookupInstanceResult) GetInstanceEndpoints { return v.Endpoints }).(GetInstanceEndpointsOutput)
}

// Instance expiration time
func (o LookupInstanceResultOutput) ExpirationTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.ExpirationTime }).(pulumi.StringOutput)
}

// Maximum number of consumer groups per instance
func (o LookupInstanceResultOutput) GroupLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.GroupLimit }).(pulumi.IntOutput)
}

// Uniquely identifies the resource.
func (o LookupInstanceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Id }).(pulumi.StringOutput)
}

// Instance ID
func (o LookupInstanceResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

// Message retention period for all topics under the instance, in hours
func (o LookupInstanceResultOutput) MessageRetention() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.MessageRetention }).(pulumi.IntOutput)
}

// Set a custom name for the BMQ instance. Constraints: Use lowercase letters, numbers, and hyphens (-). Length: 1–64 characters
func (o LookupInstanceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Name }).(pulumi.StringOutput)
}

// Maximum number of partitions per instance
func (o LookupInstanceResultOutput) PartitionLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.PartitionLimit }).(pulumi.IntOutput)
}

// Project name to which the instance belongs
func (o LookupInstanceResultOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.ProjectName }).(pulumi.StringOutput)
}

// Instance resource tag list
func (o LookupInstanceResultOutput) ResourceTags() GetInstanceResourceTagArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []GetInstanceResourceTag { return v.ResourceTags }).(GetInstanceResourceTagArrayOutput)
}

// Instance resource statistics response data
func (o LookupInstanceResultOutput) Resources() GetInstanceResourcesOutput {
	return o.ApplyT(func(v LookupInstanceResult) GetInstanceResources { return v.Resources }).(GetInstanceResourcesOutput)
}

// List of security groups used by the instance
func (o LookupInstanceResultOutput) SecurityGroupIdLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []string { return v.SecurityGroupIdLists }).(pulumi.StringArrayOutput)
}

// Instance specification
func (o LookupInstanceResultOutput) Specification() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Specification }).(pulumi.StringOutput)
}

// Instance status. Possible values: INITIALIZING: Initializing, INITIALIZATION*FAILED: Initialization failed, RUNNING: Running, MODIFYING: Updating, MODIFY*FAILED: Update failed, RELEASING: Releasing, STOPPING: Stopping, STOPPED: Stopped, RECOVERING: Recovering, EXCEPTION: Exception, CAPACITY*EXPAXION*FAILED: Capacity expansion failed, EXPANDING*CAPACITY: Expanding capacity, CANCEL*EXPANDING_CAPACITY: Canceling capacity expansion, RESTARTING: Restarting, UNPAID: Unpaid
func (o LookupInstanceResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Status }).(pulumi.StringOutput)
}

// List of subnets used by the instance
func (o LookupInstanceResultOutput) SubnetIdLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []string { return v.SubnetIdLists }).(pulumi.StringArrayOutput)
}

// Instance resource tag list
func (o LookupInstanceResultOutput) Tags() GetInstanceTagArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []GetInstanceTag { return v.Tags }).(GetInstanceTagArrayOutput)
}

// Purchase duration for subscription instances, in months
func (o LookupInstanceResultOutput) Times() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.Times }).(pulumi.IntOutput)
}

// Maximum number of topics per instance
func (o LookupInstanceResultOutput) TopicLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.TopicLimit }).(pulumi.IntOutput)
}

// VPC ID where the instance is located
func (o LookupInstanceResultOutput) VpcId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.VpcId }).(pulumi.StringOutput)
}

// List of availability zones where the instance is located
func (o LookupInstanceResultOutput) ZoneIdLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []string { return v.ZoneIdLists }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupInstanceResultOutput{})
}
