// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.vepfs;

import com.byteplus.bytepluscc.Utilities;
import com.byteplus.bytepluscc.vepfs.DataFlowTaskArgs;
import com.byteplus.bytepluscc.vepfs.inputs.DataFlowTaskState;
import com.byteplus.bytepluscc.vepfs.outputs.DataFlowTaskDeletePolicy;
import com.byteplus.bytepluscc.vepfs.outputs.DataFlowTaskEntryListFileInfo;
import com.byteplus.bytepluscc.vepfs.outputs.DataFlowTaskReport;
import com.byteplus.bytepluscc.vepfs.outputs.DataFlowTaskTlsInfo;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * vePFS data flow task. Used to perform preheating (Import), settling (Export), reconciliation (Inventory), and deletion (Delete) operations between the vePFS file system and TOS bucket.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.byteplus.bytepluscc.vepfs.DataFlowTask;
 * import com.byteplus.bytepluscc.vepfs.DataFlowTaskArgs;
 * import com.pulumi.bytepluscc.vepfs.inputs.DataFlowTaskEntryListFileInfoArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new DataFlowTask("example", DataFlowTaskArgs.builder()
 *             .fileSystemId("vepfs-xxxxxx")
 *             .taskAction("Import")
 *             .dataType("MetaAndData")
 *             .dataStorage("example-bucket")
 *             .subPath("/")
 *             .sameNameFilePolicy("KeepLatest")
 *             .entryListFileInfo(DataFlowTaskEntryListFileInfoArgs.builder()
 *                 .file_name("data.csv")
 *                 .file_bucket("example-bucket")
 *                 .file_key("data.csv")
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import bytepluscc:vepfs/dataFlowTask:DataFlowTask example &#34;file_system_id|data_flow_task_id&#34;
 * ```
 * 
 */
@ResourceType(type="bytepluscc:vepfs/dataFlowTask:DataFlowTask")
public class DataFlowTask extends com.pulumi.resources.CustomResource {
    /**
     * Task creation time.
     * 
     */
    @Export(name="createTime", refs={String.class}, tree="[0]")
    private Output<String> createTime;

    /**
     * @return Task creation time.
     * 
     */
    public Output<String> createTime() {
        return this.createTime;
    }
    /**
     * Data flow task ID.
     * 
     */
    @Export(name="dataFlowTaskId", refs={String.class}, tree="[0]")
    private Output<String> dataFlowTaskId;

    /**
     * @return Data flow task ID.
     * 
     */
    public Output<String> dataFlowTaskId() {
        return this.dataFlowTaskId;
    }
    /**
     * Source storage (TOS bucket) name.
     * 
     */
    @Export(name="dataStorage", refs={String.class}, tree="[0]")
    private Output<String> dataStorage;

    /**
     * @return Source storage (TOS bucket) name.
     * 
     */
    public Output<String> dataStorage() {
        return this.dataStorage;
    }
    /**
     * Bucket path prefix.
     * 
     */
    @Export(name="dataStoragePath", refs={String.class}, tree="[0]")
    private Output<String> dataStoragePath;

    /**
     * @return Bucket path prefix.
     * 
     */
    public Output<String> dataStoragePath() {
        return this.dataStoragePath;
    }
    /**
     * Data type operated on by the task. Metadata: Metadata; MetaAndData: Metadata and data.
     * 
     */
    @Export(name="dataType", refs={String.class}, tree="[0]")
    private Output<String> dataType;

    /**
     * @return Data type operated on by the task. Metadata: Metadata; MetaAndData: Metadata and data.
     * 
     */
    public Output<String> dataType() {
        return this.dataType;
    }
    /**
     * Deletion policy. Required when the task type is Delete (TaskAction = Delete).
     * 
     */
    @Export(name="deletePolicy", refs={DataFlowTaskDeletePolicy.class}, tree="[0]")
    private Output<DataFlowTaskDeletePolicy> deletePolicy;

    /**
     * @return Deletion policy. Required when the task type is Delete (TaskAction = Delete).
     * 
     */
    public Output<DataFlowTaskDeletePolicy> deletePolicy() {
        return this.deletePolicy;
    }
    /**
     * Whether to enable TLS log analysis. Only provided in the create request; the server responds with detailed information via TlsInfo.
     * 
     */
    @Export(name="enableTlsLog", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableTlsLog;

    /**
     * @return Whether to enable TLS log analysis. Only provided in the create request; the server responds with detailed information via TlsInfo.
     * 
     */
    public Output<Boolean> enableTlsLog() {
        return this.enableTlsLog;
    }
    /**
     * Task end time.
     * 
     */
    @Export(name="endTime", refs={String.class}, tree="[0]")
    private Output<String> endTime;

    /**
     * @return Task end time.
     * 
     */
    public Output<String> endTime() {
        return this.endTime;
    }
    /**
     * List file information for task execution.
     * 
     */
    @Export(name="entryListFileInfo", refs={DataFlowTaskEntryListFileInfo.class}, tree="[0]")
    private Output<DataFlowTaskEntryListFileInfo> entryListFileInfo;

    /**
     * @return List file information for task execution.
     * 
     */
    public Output<DataFlowTaskEntryListFileInfo> entryListFileInfo() {
        return this.entryListFileInfo;
    }
    /**
     * Download link for the list file used in task execution.
     * 
     */
    @Export(name="entryListFileUrl", refs={String.class}, tree="[0]")
    private Output<String> entryListFileUrl;

    /**
     * @return Download link for the list file used in task execution.
     * 
     */
    public Output<String> entryListFileUrl() {
        return this.entryListFileUrl;
    }
    /**
     * Completed operations (applies to preheating and settling tasks).
     * 
     */
    @Export(name="execCount", refs={String.class}, tree="[0]")
    private Output<String> execCount;

    /**
     * @return Completed operations (applies to preheating and settling tasks).
     * 
     */
    public Output<String> execCount() {
        return this.execCount;
    }
    /**
     * Executed task capacity.
     * 
     */
    @Export(name="execSize", refs={String.class}, tree="[0]")
    private Output<String> execSize;

    /**
     * @return Executed task capacity.
     * 
     */
    public Output<String> execSize() {
        return this.execSize;
    }
    /**
     * Export task symlink handling policy. Skip: skip symlink files; NormalFile: export as independent files.
     * 
     */
    @Export(name="exportSymlinkPolicy", refs={String.class}, tree="[0]")
    private Output<String> exportSymlinkPolicy;

    /**
     * @return Export task symlink handling policy. Skip: skip symlink files; NormalFile: export as independent files.
     * 
     */
    public Output<String> exportSymlinkPolicy() {
        return this.exportSymlinkPolicy;
    }
    /**
     * Total number of failures after being added to the queue.
     * 
     */
    @Export(name="failedCount", refs={String.class}, tree="[0]")
    private Output<String> failedCount;

    /**
     * @return Total number of failures after being added to the queue.
     * 
     */
    public Output<String> failedCount() {
        return this.failedCount;
    }
    /**
     * File system ID.
     * 
     */
    @Export(name="fileSystemId", refs={String.class}, tree="[0]")
    private Output<String> fileSystemId;

    /**
     * @return File system ID.
     * 
     */
    public Output<String> fileSystemId() {
        return this.fileSystemId;
    }
    /**
     * Fileset ID。
     * 
     */
    @Export(name="filesetId", refs={String.class}, tree="[0]")
    private Output<String> filesetId;

    /**
     * @return Fileset ID。
     * 
     */
    public Output<String> filesetId() {
        return this.filesetId;
    }
    /**
     * Fileset path.
     * 
     */
    @Export(name="filesetPath", refs={String.class}, tree="[0]")
    private Output<String> filesetPath;

    /**
     * @return Fileset path.
     * 
     */
    public Output<String> filesetPath() {
        return this.filesetPath;
    }
    /**
     * Total number of operations added to the queue (valid for preheating and settling tasks).
     * 
     */
    @Export(name="queueCount", refs={String.class}, tree="[0]")
    private Output<String> queueCount;

    /**
     * @return Total number of operations added to the queue (valid for preheating and settling tasks).
     * 
     */
    public Output<String> queueCount() {
        return this.queueCount;
    }
    /**
     * Task report list.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    @Export(name="reports", refs={List.class,DataFlowTaskReport.class}, tree="[0,1]")
    private Output<List<DataFlowTaskReport>> reports;

    /**
     * @return Task report list.
     * Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.
     * 
     */
    public Output<List<DataFlowTaskReport>> reports() {
        return this.reports;
    }
    /**
     * Same-name file policy. Skip: Skip files with the same name; KeepLatest: Keep the latest file; OverWrite: Overwrite files with the same name.
     * 
     */
    @Export(name="sameNameFilePolicy", refs={String.class}, tree="[0]")
    private Output<String> sameNameFilePolicy;

    /**
     * @return Same-name file policy. Skip: Skip files with the same name; KeepLatest: Keep the latest file; OverWrite: Overwrite files with the same name.
     * 
     */
    public Output<String> sameNameFilePolicy() {
        return this.sameNameFilePolicy;
    }
    /**
     * Task start time.
     * 
     */
    @Export(name="startTime", refs={String.class}, tree="[0]")
    private Output<String> startTime;

    /**
     * @return Task start time.
     * 
     */
    public Output<String> startTime() {
        return this.startTime;
    }
    /**
     * Task status. Creating: Creating; Running: Running; Finished: Finished; Canceling: Canceling; Canceled: Canceled; Deleting: Deleting; Error: Error; Deleted: Deleted.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Task status. Creating: Creating; Running: Running; Finished: Finished; Canceling: Canceling; Canceled: Canceled; Deleting: Deleting; Error: Error; Deleted: Deleted.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Subpath under Fileset (represents the full file system path if Fileset ID is not specified).
     * 
     */
    @Export(name="subPath", refs={String.class}, tree="[0]")
    private Output<String> subPath;

    /**
     * @return Subpath under Fileset (represents the full file system path if Fileset ID is not specified).
     * 
     */
    public Output<String> subPath() {
        return this.subPath;
    }
    /**
     * Task type. Import: Preheating task; Export: Settling task; Inventory: Reconciliation task; Delete: Deletion task.
     * 
     */
    @Export(name="taskAction", refs={String.class}, tree="[0]")
    private Output<String> taskAction;

    /**
     * @return Task type. Import: Preheating task; Export: Settling task; Inventory: Reconciliation task; Delete: Deletion task.
     * 
     */
    public Output<String> taskAction() {
        return this.taskAction;
    }
    /**
     * TLS log information. Displayed by the server only if TLS log analysis (EnableTlsLog=true) is enabled during creation.
     * 
     */
    @Export(name="tlsInfo", refs={DataFlowTaskTlsInfo.class}, tree="[0]")
    private Output<DataFlowTaskTlsInfo> tlsInfo;

    /**
     * @return TLS log information. Displayed by the server only if TLS log analysis (EnableTlsLog=true) is enabled during creation.
     * 
     */
    public Output<DataFlowTaskTlsInfo> tlsInfo() {
        return this.tlsInfo;
    }
    /**
     * Total task capacity.
     * 
     */
    @Export(name="totalSize", refs={String.class}, tree="[0]")
    private Output<String> totalSize;

    /**
     * @return Total task capacity.
     * 
     */
    public Output<String> totalSize() {
        return this.totalSize;
    }
    /**
     * Task modification time.
     * 
     */
    @Export(name="updateTime", refs={String.class}, tree="[0]")
    private Output<String> updateTime;

    /**
     * @return Task modification time.
     * 
     */
    public Output<String> updateTime() {
        return this.updateTime;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DataFlowTask(java.lang.String name) {
        this(name, DataFlowTaskArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DataFlowTask(java.lang.String name, DataFlowTaskArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DataFlowTask(java.lang.String name, DataFlowTaskArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:vepfs/dataFlowTask:DataFlowTask", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private DataFlowTask(java.lang.String name, Output<java.lang.String> id, @Nullable DataFlowTaskState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("bytepluscc:vepfs/dataFlowTask:DataFlowTask", name, state, makeResourceOptions(options, id), false);
    }

    private static DataFlowTaskArgs makeArgs(DataFlowTaskArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DataFlowTaskArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/byteplus-sdk")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DataFlowTask get(java.lang.String name, Output<java.lang.String> id, @Nullable DataFlowTaskState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DataFlowTask(name, id, state, options);
    }
}
