# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['NatFireWallArgs', 'NatFireWall']

@pulumi.input_type
class NatFireWallArgs:
    def __init__(__self__, *,
                 bandwidth: pulumi.Input[_builtins.int],
                 firewall_cidr: pulumi.Input[_builtins.str],
                 nat_firewall_name: pulumi.Input[_builtins.str],
                 nat_gateway_id: pulumi.Input[_builtins.str],
                 cloud_firewall_id: pulumi.Input[Optional[_builtins.str]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a NatFireWall resource.

        :param pulumi.Input[_builtins.int] bandwidth: Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        :param pulumi.Input[_builtins.str] firewall_cidr: Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        :param pulumi.Input[_builtins.str] nat_firewall_name: Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        :param pulumi.Input[_builtins.str] nat_gateway_id: NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        :param pulumi.Input[_builtins.str] cloud_firewall_id: Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        :param pulumi.Input[_builtins.str] project_name: Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        """
        pulumi.set(__self__, "bandwidth", bandwidth)
        pulumi.set(__self__, "firewall_cidr", firewall_cidr)
        pulumi.set(__self__, "nat_firewall_name", nat_firewall_name)
        pulumi.set(__self__, "nat_gateway_id", nat_gateway_id)
        if cloud_firewall_id is not None:
            pulumi.set(__self__, "cloud_firewall_id", cloud_firewall_id)
        if project_name is not None:
            pulumi.set(__self__, "project_name", project_name)

    @_builtins.property
    @pulumi.getter
    def bandwidth(self) -> pulumi.Input[_builtins.int]:
        """
        Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        """
        return pulumi.get(self, "bandwidth")

    @bandwidth.setter
    def bandwidth(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "bandwidth", value)

    @_builtins.property
    @pulumi.getter(name="firewallCidr")
    def firewall_cidr(self) -> pulumi.Input[_builtins.str]:
        """
        Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        """
        return pulumi.get(self, "firewall_cidr")

    @firewall_cidr.setter
    def firewall_cidr(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "firewall_cidr", value)

    @_builtins.property
    @pulumi.getter(name="natFirewallName")
    def nat_firewall_name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        """
        return pulumi.get(self, "nat_firewall_name")

    @nat_firewall_name.setter
    def nat_firewall_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "nat_firewall_name", value)

    @_builtins.property
    @pulumi.getter(name="natGatewayId")
    def nat_gateway_id(self) -> pulumi.Input[_builtins.str]:
        """
        NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        """
        return pulumi.get(self, "nat_gateway_id")

    @nat_gateway_id.setter
    def nat_gateway_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "nat_gateway_id", value)

    @_builtins.property
    @pulumi.getter(name="cloudFirewallId")
    def cloud_firewall_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        """
        return pulumi.get(self, "cloud_firewall_id")

    @cloud_firewall_id.setter
    def cloud_firewall_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cloud_firewall_id", value)

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        """
        return pulumi.get(self, "project_name")

    @project_name.setter
    def project_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_name", value)


@pulumi.input_type
class _NatFireWallState:
    def __init__(__self__, *,
                 account_id: pulumi.Input[Optional[_builtins.str]] = None,
                 bandwidth: pulumi.Input[Optional[_builtins.int]] = None,
                 can_create: pulumi.Input[Optional[_builtins.bool]] = None,
                 cloud_firewall_id: pulumi.Input[Optional[_builtins.str]] = None,
                 err_message: pulumi.Input[Optional[_builtins.str]] = None,
                 firewall_cidr: pulumi.Input[Optional[_builtins.str]] = None,
                 firewall_status: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_firewall_id: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_firewall_name: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_firewall_subnet_cidr: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_gateway_id: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_gateway_name: pulumi.Input[Optional[_builtins.str]] = None,
                 peak_traffic_within7_day: pulumi.Input[Optional[_builtins.int]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_name_for_nat_gate: pulumi.Input[Optional[_builtins.str]] = None,
                 vpc_cidr: pulumi.Input[Optional[_builtins.str]] = None,
                 vpc_id: pulumi.Input[Optional[_builtins.str]] = None,
                 vpc_name: pulumi.Input[Optional[_builtins.str]] = None,
                 zone_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering NatFireWall resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.
        :param pulumi.Input[_builtins.int] bandwidth: Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        :param pulumi.Input[_builtins.bool] can_create: Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.
        :param pulumi.Input[_builtins.str] cloud_firewall_id: Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        :param pulumi.Input[_builtins.str] err_message: Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.
        :param pulumi.Input[_builtins.str] firewall_cidr: Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        :param pulumi.Input[_builtins.str] firewall_status: Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.
        :param pulumi.Input[_builtins.str] nat_firewall_id: Unique identifier of the NAT boundary firewall instance.
        :param pulumi.Input[_builtins.str] nat_firewall_name: Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        :param pulumi.Input[_builtins.str] nat_firewall_subnet_cidr: Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.
        :param pulumi.Input[_builtins.str] nat_gateway_id: NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        :param pulumi.Input[_builtins.str] nat_gateway_name: Name of the NAT gateway, used to identify the associated NAT gateway.
        :param pulumi.Input[_builtins.int] peak_traffic_within7_day: Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.
        :param pulumi.Input[_builtins.str] project_name: Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        :param pulumi.Input[_builtins.str] project_name_for_nat_gate: Project name to which the associated NAT gateway belongs.
        :param pulumi.Input[_builtins.str] vpc_cidr: Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.
        :param pulumi.Input[_builtins.str] vpc_id: Unique identifier of the associated VPC.
        :param pulumi.Input[_builtins.str] vpc_name: Name of the associated VPC.
        :param pulumi.Input[_builtins.str] zone_id: Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if bandwidth is not None:
            pulumi.set(__self__, "bandwidth", bandwidth)
        if can_create is not None:
            pulumi.set(__self__, "can_create", can_create)
        if cloud_firewall_id is not None:
            pulumi.set(__self__, "cloud_firewall_id", cloud_firewall_id)
        if err_message is not None:
            pulumi.set(__self__, "err_message", err_message)
        if firewall_cidr is not None:
            pulumi.set(__self__, "firewall_cidr", firewall_cidr)
        if firewall_status is not None:
            pulumi.set(__self__, "firewall_status", firewall_status)
        if nat_firewall_id is not None:
            pulumi.set(__self__, "nat_firewall_id", nat_firewall_id)
        if nat_firewall_name is not None:
            pulumi.set(__self__, "nat_firewall_name", nat_firewall_name)
        if nat_firewall_subnet_cidr is not None:
            pulumi.set(__self__, "nat_firewall_subnet_cidr", nat_firewall_subnet_cidr)
        if nat_gateway_id is not None:
            pulumi.set(__self__, "nat_gateway_id", nat_gateway_id)
        if nat_gateway_name is not None:
            pulumi.set(__self__, "nat_gateway_name", nat_gateway_name)
        if peak_traffic_within7_day is not None:
            pulumi.set(__self__, "peak_traffic_within7_day", peak_traffic_within7_day)
        if project_name is not None:
            pulumi.set(__self__, "project_name", project_name)
        if project_name_for_nat_gate is not None:
            pulumi.set(__self__, "project_name_for_nat_gate", project_name_for_nat_gate)
        if vpc_cidr is not None:
            pulumi.set(__self__, "vpc_cidr", vpc_cidr)
        if vpc_id is not None:
            pulumi.set(__self__, "vpc_id", vpc_id)
        if vpc_name is not None:
            pulumi.set(__self__, "vpc_name", vpc_name)
        if zone_id is not None:
            pulumi.set(__self__, "zone_id", zone_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter
    def bandwidth(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        """
        return pulumi.get(self, "bandwidth")

    @bandwidth.setter
    def bandwidth(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "bandwidth", value)

    @_builtins.property
    @pulumi.getter(name="canCreate")
    def can_create(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.
        """
        return pulumi.get(self, "can_create")

    @can_create.setter
    def can_create(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "can_create", value)

    @_builtins.property
    @pulumi.getter(name="cloudFirewallId")
    def cloud_firewall_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        """
        return pulumi.get(self, "cloud_firewall_id")

    @cloud_firewall_id.setter
    def cloud_firewall_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cloud_firewall_id", value)

    @_builtins.property
    @pulumi.getter(name="errMessage")
    def err_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.
        """
        return pulumi.get(self, "err_message")

    @err_message.setter
    def err_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "err_message", value)

    @_builtins.property
    @pulumi.getter(name="firewallCidr")
    def firewall_cidr(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        """
        return pulumi.get(self, "firewall_cidr")

    @firewall_cidr.setter
    def firewall_cidr(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "firewall_cidr", value)

    @_builtins.property
    @pulumi.getter(name="firewallStatus")
    def firewall_status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.
        """
        return pulumi.get(self, "firewall_status")

    @firewall_status.setter
    def firewall_status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "firewall_status", value)

    @_builtins.property
    @pulumi.getter(name="natFirewallId")
    def nat_firewall_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique identifier of the NAT boundary firewall instance.
        """
        return pulumi.get(self, "nat_firewall_id")

    @nat_firewall_id.setter
    def nat_firewall_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "nat_firewall_id", value)

    @_builtins.property
    @pulumi.getter(name="natFirewallName")
    def nat_firewall_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        """
        return pulumi.get(self, "nat_firewall_name")

    @nat_firewall_name.setter
    def nat_firewall_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "nat_firewall_name", value)

    @_builtins.property
    @pulumi.getter(name="natFirewallSubnetCidr")
    def nat_firewall_subnet_cidr(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.
        """
        return pulumi.get(self, "nat_firewall_subnet_cidr")

    @nat_firewall_subnet_cidr.setter
    def nat_firewall_subnet_cidr(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "nat_firewall_subnet_cidr", value)

    @_builtins.property
    @pulumi.getter(name="natGatewayId")
    def nat_gateway_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        """
        return pulumi.get(self, "nat_gateway_id")

    @nat_gateway_id.setter
    def nat_gateway_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "nat_gateway_id", value)

    @_builtins.property
    @pulumi.getter(name="natGatewayName")
    def nat_gateway_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the NAT gateway, used to identify the associated NAT gateway.
        """
        return pulumi.get(self, "nat_gateway_name")

    @nat_gateway_name.setter
    def nat_gateway_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "nat_gateway_name", value)

    @_builtins.property
    @pulumi.getter(name="peakTrafficWithin7Day")
    def peak_traffic_within7_day(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.
        """
        return pulumi.get(self, "peak_traffic_within7_day")

    @peak_traffic_within7_day.setter
    def peak_traffic_within7_day(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "peak_traffic_within7_day", value)

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        """
        return pulumi.get(self, "project_name")

    @project_name.setter
    def project_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_name", value)

    @_builtins.property
    @pulumi.getter(name="projectNameForNatGate")
    def project_name_for_nat_gate(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Project name to which the associated NAT gateway belongs.
        """
        return pulumi.get(self, "project_name_for_nat_gate")

    @project_name_for_nat_gate.setter
    def project_name_for_nat_gate(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_name_for_nat_gate", value)

    @_builtins.property
    @pulumi.getter(name="vpcCidr")
    def vpc_cidr(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.
        """
        return pulumi.get(self, "vpc_cidr")

    @vpc_cidr.setter
    def vpc_cidr(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "vpc_cidr", value)

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique identifier of the associated VPC.
        """
        return pulumi.get(self, "vpc_id")

    @vpc_id.setter
    def vpc_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "vpc_id", value)

    @_builtins.property
    @pulumi.getter(name="vpcName")
    def vpc_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the associated VPC.
        """
        return pulumi.get(self, "vpc_name")

    @vpc_name.setter
    def vpc_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "vpc_name", value)

    @_builtins.property
    @pulumi.getter(name="zoneId")
    def zone_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.
        """
        return pulumi.get(self, "zone_id")

    @zone_id.setter
    def zone_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "zone_id", value)


@pulumi.type_token("bytepluscc:fwcenter/natFireWall:NatFireWall")
class NatFireWall(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bandwidth: pulumi.Input[Optional[_builtins.int]] = None,
                 cloud_firewall_id: pulumi.Input[Optional[_builtins.str]] = None,
                 firewall_cidr: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_firewall_name: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_gateway_id: pulumi.Input[Optional[_builtins.str]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        NAT boundary firewall instance. Provides security protection and access control for north-south traffic passing through the NAT gateway.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_bytepluscc as bytepluscc

        example = bytepluscc.fwcenter.NatFireWall("example",
            nat_gateway_id="ngw-xxxxxx",
            nat_firewall_name="example",
            firewall_cidr="192.168.208.0/28",
            bandwidth=100,
            project_name="default",
            cloud_firewall_id="CloudFirewallxxxxxxxx")
        ```

        ## Import

        ```sh
        $ pulumi import bytepluscc:fwcenter/natFireWall:NatFireWall example "nat_firewall_id"
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] bandwidth: Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        :param pulumi.Input[_builtins.str] cloud_firewall_id: Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        :param pulumi.Input[_builtins.str] firewall_cidr: Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        :param pulumi.Input[_builtins.str] nat_firewall_name: Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        :param pulumi.Input[_builtins.str] nat_gateway_id: NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        :param pulumi.Input[_builtins.str] project_name: Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: NatFireWallArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        NAT boundary firewall instance. Provides security protection and access control for north-south traffic passing through the NAT gateway.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_bytepluscc as bytepluscc

        example = bytepluscc.fwcenter.NatFireWall("example",
            nat_gateway_id="ngw-xxxxxx",
            nat_firewall_name="example",
            firewall_cidr="192.168.208.0/28",
            bandwidth=100,
            project_name="default",
            cloud_firewall_id="CloudFirewallxxxxxxxx")
        ```

        ## Import

        ```sh
        $ pulumi import bytepluscc:fwcenter/natFireWall:NatFireWall example "nat_firewall_id"
        ```


        :param str resource_name: The name of the resource.
        :param NatFireWallArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(NatFireWallArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bandwidth: pulumi.Input[Optional[_builtins.int]] = None,
                 cloud_firewall_id: pulumi.Input[Optional[_builtins.str]] = None,
                 firewall_cidr: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_firewall_name: pulumi.Input[Optional[_builtins.str]] = None,
                 nat_gateway_id: pulumi.Input[Optional[_builtins.str]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = NatFireWallArgs.__new__(NatFireWallArgs)

            if bandwidth is None and not opts.urn:
                raise TypeError("Missing required property 'bandwidth'")
            __props__.__dict__["bandwidth"] = bandwidth
            __props__.__dict__["cloud_firewall_id"] = cloud_firewall_id
            if firewall_cidr is None and not opts.urn:
                raise TypeError("Missing required property 'firewall_cidr'")
            __props__.__dict__["firewall_cidr"] = firewall_cidr
            if nat_firewall_name is None and not opts.urn:
                raise TypeError("Missing required property 'nat_firewall_name'")
            __props__.__dict__["nat_firewall_name"] = nat_firewall_name
            if nat_gateway_id is None and not opts.urn:
                raise TypeError("Missing required property 'nat_gateway_id'")
            __props__.__dict__["nat_gateway_id"] = nat_gateway_id
            __props__.__dict__["project_name"] = project_name
            __props__.__dict__["account_id"] = None
            __props__.__dict__["can_create"] = None
            __props__.__dict__["err_message"] = None
            __props__.__dict__["firewall_status"] = None
            __props__.__dict__["nat_firewall_id"] = None
            __props__.__dict__["nat_firewall_subnet_cidr"] = None
            __props__.__dict__["nat_gateway_name"] = None
            __props__.__dict__["peak_traffic_within7_day"] = None
            __props__.__dict__["project_name_for_nat_gate"] = None
            __props__.__dict__["vpc_cidr"] = None
            __props__.__dict__["vpc_id"] = None
            __props__.__dict__["vpc_name"] = None
            __props__.__dict__["zone_id"] = None
        super(NatFireWall, __self__).__init__(
            'bytepluscc:fwcenter/natFireWall:NatFireWall',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: pulumi.Input[Optional[_builtins.str]] = None,
            bandwidth: pulumi.Input[Optional[_builtins.int]] = None,
            can_create: pulumi.Input[Optional[_builtins.bool]] = None,
            cloud_firewall_id: pulumi.Input[Optional[_builtins.str]] = None,
            err_message: pulumi.Input[Optional[_builtins.str]] = None,
            firewall_cidr: pulumi.Input[Optional[_builtins.str]] = None,
            firewall_status: pulumi.Input[Optional[_builtins.str]] = None,
            nat_firewall_id: pulumi.Input[Optional[_builtins.str]] = None,
            nat_firewall_name: pulumi.Input[Optional[_builtins.str]] = None,
            nat_firewall_subnet_cidr: pulumi.Input[Optional[_builtins.str]] = None,
            nat_gateway_id: pulumi.Input[Optional[_builtins.str]] = None,
            nat_gateway_name: pulumi.Input[Optional[_builtins.str]] = None,
            peak_traffic_within7_day: pulumi.Input[Optional[_builtins.int]] = None,
            project_name: pulumi.Input[Optional[_builtins.str]] = None,
            project_name_for_nat_gate: pulumi.Input[Optional[_builtins.str]] = None,
            vpc_cidr: pulumi.Input[Optional[_builtins.str]] = None,
            vpc_id: pulumi.Input[Optional[_builtins.str]] = None,
            vpc_name: pulumi.Input[Optional[_builtins.str]] = None,
            zone_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'NatFireWall':
        """
        Get an existing NatFireWall resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.
        :param pulumi.Input[_builtins.int] bandwidth: Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        :param pulumi.Input[_builtins.bool] can_create: Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.
        :param pulumi.Input[_builtins.str] cloud_firewall_id: Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        :param pulumi.Input[_builtins.str] err_message: Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.
        :param pulumi.Input[_builtins.str] firewall_cidr: Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        :param pulumi.Input[_builtins.str] firewall_status: Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.
        :param pulumi.Input[_builtins.str] nat_firewall_id: Unique identifier of the NAT boundary firewall instance.
        :param pulumi.Input[_builtins.str] nat_firewall_name: Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        :param pulumi.Input[_builtins.str] nat_firewall_subnet_cidr: Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.
        :param pulumi.Input[_builtins.str] nat_gateway_id: NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        :param pulumi.Input[_builtins.str] nat_gateway_name: Name of the NAT gateway, used to identify the associated NAT gateway.
        :param pulumi.Input[_builtins.int] peak_traffic_within7_day: Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.
        :param pulumi.Input[_builtins.str] project_name: Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        :param pulumi.Input[_builtins.str] project_name_for_nat_gate: Project name to which the associated NAT gateway belongs.
        :param pulumi.Input[_builtins.str] vpc_cidr: Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.
        :param pulumi.Input[_builtins.str] vpc_id: Unique identifier of the associated VPC.
        :param pulumi.Input[_builtins.str] vpc_name: Name of the associated VPC.
        :param pulumi.Input[_builtins.str] zone_id: Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _NatFireWallState.__new__(_NatFireWallState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["bandwidth"] = bandwidth
        __props__.__dict__["can_create"] = can_create
        __props__.__dict__["cloud_firewall_id"] = cloud_firewall_id
        __props__.__dict__["err_message"] = err_message
        __props__.__dict__["firewall_cidr"] = firewall_cidr
        __props__.__dict__["firewall_status"] = firewall_status
        __props__.__dict__["nat_firewall_id"] = nat_firewall_id
        __props__.__dict__["nat_firewall_name"] = nat_firewall_name
        __props__.__dict__["nat_firewall_subnet_cidr"] = nat_firewall_subnet_cidr
        __props__.__dict__["nat_gateway_id"] = nat_gateway_id
        __props__.__dict__["nat_gateway_name"] = nat_gateway_name
        __props__.__dict__["peak_traffic_within7_day"] = peak_traffic_within7_day
        __props__.__dict__["project_name"] = project_name
        __props__.__dict__["project_name_for_nat_gate"] = project_name_for_nat_gate
        __props__.__dict__["vpc_cidr"] = vpc_cidr
        __props__.__dict__["vpc_id"] = vpc_id
        __props__.__dict__["vpc_name"] = vpc_name
        __props__.__dict__["zone_id"] = zone_id
        return NatFireWall(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[_builtins.str]:
        """
        Account ID for creating the NAT firewall, used to identify the account to which the NAT boundary firewall instance belongs.
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter
    def bandwidth(self) -> pulumi.Output[_builtins.int]:
        """
        Authorized traffic bandwidth of the NAT boundary firewall instance, measured in Mbps, indicating the maximum network bandwidth allowed for the firewall instance. The minimum value is 10.
        """
        return pulumi.get(self, "bandwidth")

    @_builtins.property
    @pulumi.getter(name="canCreate")
    def can_create(self) -> pulumi.Output[_builtins.bool]:
        """
        Indicates whether creating a NAT boundary firewall is currently supported. true means supported, false means not supported.
        """
        return pulumi.get(self, "can_create")

    @_builtins.property
    @pulumi.getter(name="cloudFirewallId")
    def cloud_firewall_id(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud firewall instance ID, used to identify and manage the cloud firewall instance.
        """
        return pulumi.get(self, "cloud_firewall_id")

    @_builtins.property
    @pulumi.getter(name="errMessage")
    def err_message(self) -> pulumi.Output[_builtins.str]:
        """
        Error message returned when an error occurs during the creation or query of a NAT boundary firewall instance, used to describe the specific cause of the error.
        """
        return pulumi.get(self, "err_message")

    @_builtins.property
    @pulumi.getter(name="firewallCidr")
    def firewall_cidr(self) -> pulumi.Output[_builtins.str]:
        """
        Subnet CIDR of the NAT boundary firewall, used to specify the network range protected by the firewall, expressed in CIDR format.
        """
        return pulumi.get(self, "firewall_cidr")

    @_builtins.property
    @pulumi.getter(name="firewallStatus")
    def firewall_status(self) -> pulumi.Output[_builtins.str]:
        """
        Status of the NAT boundary firewall instance. creating: being created; deleting: being deleted; opened: created; closed: not created; error: error; updating: being upgraded.
        """
        return pulumi.get(self, "firewall_status")

    @_builtins.property
    @pulumi.getter(name="natFirewallId")
    def nat_firewall_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier of the NAT boundary firewall instance.
        """
        return pulumi.get(self, "nat_firewall_id")

    @_builtins.property
    @pulumi.getter(name="natFirewallName")
    def nat_firewall_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the NAT boundary firewall instance, used to identify and manage the firewall instance.
        """
        return pulumi.get(self, "nat_firewall_name")

    @_builtins.property
    @pulumi.getter(name="natFirewallSubnetCidr")
    def nat_firewall_subnet_cidr(self) -> pulumi.Output[_builtins.str]:
        """
        Subnet CIDR of the NAT boundary firewall instance, used to identify the subnet IP address range protected by the firewall instance.
        """
        return pulumi.get(self, "nat_firewall_subnet_cidr")

    @_builtins.property
    @pulumi.getter(name="natGatewayId")
    def nat_gateway_id(self) -> pulumi.Output[_builtins.str]:
        """
        NAT gateway instance ID, used to identify and manage the NAT gateway instance. You must specify the associated NAT gateway when creating a NAT firewall.
        """
        return pulumi.get(self, "nat_gateway_id")

    @_builtins.property
    @pulumi.getter(name="natGatewayName")
    def nat_gateway_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the NAT gateway, used to identify the associated NAT gateway.
        """
        return pulumi.get(self, "nat_gateway_name")

    @_builtins.property
    @pulumi.getter(name="peakTrafficWithin7Day")
    def peak_traffic_within7_day(self) -> pulumi.Output[_builtins.int]:
        """
        Peak traffic of the NAT boundary firewall instance in the past 7 days, measured in bps, used to monitor the highest network traffic usage.
        """
        return pulumi.get(self, "peak_traffic_within7_day")

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Output[_builtins.str]:
        """
        Project name, used to identify and manage the project to which the resource belongs. The default value is default.
        """
        return pulumi.get(self, "project_name")

    @_builtins.property
    @pulumi.getter(name="projectNameForNatGate")
    def project_name_for_nat_gate(self) -> pulumi.Output[_builtins.str]:
        """
        Project name to which the associated NAT gateway belongs.
        """
        return pulumi.get(self, "project_name_for_nat_gate")

    @_builtins.property
    @pulumi.getter(name="vpcCidr")
    def vpc_cidr(self) -> pulumi.Output[_builtins.str]:
        """
        Subnet CIDR of the associated VPC, used to identify the IP address range of the VPC.
        """
        return pulumi.get(self, "vpc_cidr")

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier of the associated VPC.
        """
        return pulumi.get(self, "vpc_id")

    @_builtins.property
    @pulumi.getter(name="vpcName")
    def vpc_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the associated VPC.
        """
        return pulumi.get(self, "vpc_name")

    @_builtins.property
    @pulumi.getter(name="zoneId")
    def zone_id(self) -> pulumi.Output[_builtins.str]:
        """
        Availability zone where the NAT boundary firewall instance is located, used to identify the specific physical area where the instance is deployed.
        """
        return pulumi.get(self, "zone_id")

