// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as alb from "./alb";
import * as autoscaling from "./autoscaling";
import * as clb from "./clb";
import * as config from "./config";
import * as cr from "./cr";
import * as ecs from "./ecs";
import * as storageebs from "./storageebs";
import * as types from "./types";
import * as vpc from "./vpc";

export {
    alb,
    autoscaling,
    clb,
    config,
    cr,
    ecs,
    storageebs,
    types,
    vpc,
};
pulumi.runtime.registerResourcePackage("bytepluscc", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:bytepluscc") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
