// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.transitrouter.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTransitRouterAttachmentToRouteTableResult {
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    private String id;
    /**
     * @return Status of the associated forwarding. Possible values: Available (可用), Creating (创建中), Pending (配置中), Deleting (删除中).
     * 
     */
    private String status;
    /**
     * @return ID of the network instance connection. You can call APIs such as DescribeTransitRouterVpcAttachments, DescribeTransitRouterVpnAttachments, DescribeTransitRouterDirectConnectGatewayAttachments, and DescribeTransitRouterPeerAttachments to obtain the ID of the corresponding type of network instance connection.
     * 
     */
    private String transitRouterAttachmentId;
    /**
     * @return ID of the route table associated with the Transit Router instance. You can call the DescribeTransitRouterRouteTables API to obtain the TR route table ID.
     * 
     */
    private String transitRouterRouteTableId;

    private GetTransitRouterAttachmentToRouteTableResult() {}
    /**
     * @return Uniquely identifies the resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Status of the associated forwarding. Possible values: Available (可用), Creating (创建中), Pending (配置中), Deleting (删除中).
     * 
     */
    public String status() {
        return this.status;
    }
    /**
     * @return ID of the network instance connection. You can call APIs such as DescribeTransitRouterVpcAttachments, DescribeTransitRouterVpnAttachments, DescribeTransitRouterDirectConnectGatewayAttachments, and DescribeTransitRouterPeerAttachments to obtain the ID of the corresponding type of network instance connection.
     * 
     */
    public String transitRouterAttachmentId() {
        return this.transitRouterAttachmentId;
    }
    /**
     * @return ID of the route table associated with the Transit Router instance. You can call the DescribeTransitRouterRouteTables API to obtain the TR route table ID.
     * 
     */
    public String transitRouterRouteTableId() {
        return this.transitRouterRouteTableId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTransitRouterAttachmentToRouteTableResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String status;
        private String transitRouterAttachmentId;
        private String transitRouterRouteTableId;
        public Builder() {}
        public Builder(GetTransitRouterAttachmentToRouteTableResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.status = defaults.status;
    	      this.transitRouterAttachmentId = defaults.transitRouterAttachmentId;
    	      this.transitRouterRouteTableId = defaults.transitRouterRouteTableId;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTransitRouterAttachmentToRouteTableResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetTransitRouterAttachmentToRouteTableResult", "status");
            }
            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder transitRouterAttachmentId(String transitRouterAttachmentId) {
            if (transitRouterAttachmentId == null) {
              throw new MissingRequiredPropertyException("GetTransitRouterAttachmentToRouteTableResult", "transitRouterAttachmentId");
            }
            this.transitRouterAttachmentId = transitRouterAttachmentId;
            return this;
        }
        @CustomType.Setter
        public Builder transitRouterRouteTableId(String transitRouterRouteTableId) {
            if (transitRouterRouteTableId == null) {
              throw new MissingRequiredPropertyException("GetTransitRouterAttachmentToRouteTableResult", "transitRouterRouteTableId");
            }
            this.transitRouterRouteTableId = transitRouterRouteTableId;
            return this;
        }
        public GetTransitRouterAttachmentToRouteTableResult build() {
            final var _resultValue = new GetTransitRouterAttachmentToRouteTableResult();
            _resultValue.id = id;
            _resultValue.status = status;
            _resultValue.transitRouterAttachmentId = transitRouterAttachmentId;
            _resultValue.transitRouterRouteTableId = transitRouterRouteTableId;
            return _resultValue;
        }
    }
}
