// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.byteplus.bytepluscc.ecs;

import com.byteplus.bytepluscc.Utilities;
import com.byteplus.bytepluscc.ecs.inputs.GetCommandArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetCommandPlainArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetImageArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetImagePlainArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetInstanceArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetInstancePlainArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetInvocationArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetInvocationPlainArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetKeypairArgs;
import com.byteplus.bytepluscc.ecs.inputs.GetKeypairPlainArgs;
import com.byteplus.bytepluscc.ecs.outputs.GetCommandResult;
import com.byteplus.bytepluscc.ecs.outputs.GetCommandsResult;
import com.byteplus.bytepluscc.ecs.outputs.GetImageResult;
import com.byteplus.bytepluscc.ecs.outputs.GetImagesResult;
import com.byteplus.bytepluscc.ecs.outputs.GetInstanceResult;
import com.byteplus.bytepluscc.ecs.outputs.GetInstancesResult;
import com.byteplus.bytepluscc.ecs.outputs.GetInvocationResult;
import com.byteplus.bytepluscc.ecs.outputs.GetInvocationsResult;
import com.byteplus.bytepluscc.ecs.outputs.GetKeypairResult;
import com.byteplus.bytepluscc.ecs.outputs.GetKeypairsResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.resources.InvokeArgs;
import java.util.concurrent.CompletableFuture;

public final class EcsFunctions {
    /**
     * Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static Output<GetCommandResult> getCommand(GetCommandArgs args) {
        return getCommand(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static CompletableFuture<GetCommandResult> getCommandPlain(GetCommandPlainArgs args) {
        return getCommandPlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static Output<GetCommandResult> getCommand(GetCommandArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getCommand:getCommand", TypeShape.of(GetCommandResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static Output<GetCommandResult> getCommand(GetCommandArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getCommand:getCommand", TypeShape.of(GetCommandResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static CompletableFuture<GetCommandResult> getCommandPlain(GetCommandPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getCommand:getCommand", TypeShape.of(GetCommandResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static Output<GetCommandsResult> getCommands() {
        return getCommands(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static CompletableFuture<GetCommandsResult> getCommandsPlain() {
        return getCommandsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static Output<GetCommandsResult> getCommands(InvokeArgs args) {
        return getCommands(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static CompletableFuture<GetCommandsResult> getCommandsPlain(InvokeArgs args) {
        return getCommandsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static Output<GetCommandsResult> getCommands(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getCommands:getCommands", TypeShape.of(GetCommandsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static Output<GetCommandsResult> getCommands(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getCommands:getCommands", TypeShape.of(GetCommandsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Command
     * 
     */
    public static CompletableFuture<GetCommandsResult> getCommandsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getCommands:getCommands", TypeShape.of(GetCommandsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static Output<GetImageResult> getImage(GetImageArgs args) {
        return getImage(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static CompletableFuture<GetImageResult> getImagePlain(GetImagePlainArgs args) {
        return getImagePlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static Output<GetImageResult> getImage(GetImageArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getImage:getImage", TypeShape.of(GetImageResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static Output<GetImageResult> getImage(GetImageArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getImage:getImage", TypeShape.of(GetImageResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static CompletableFuture<GetImageResult> getImagePlain(GetImagePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getImage:getImage", TypeShape.of(GetImageResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static Output<GetImagesResult> getImages() {
        return getImages(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static CompletableFuture<GetImagesResult> getImagesPlain() {
        return getImagesPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static Output<GetImagesResult> getImages(InvokeArgs args) {
        return getImages(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static CompletableFuture<GetImagesResult> getImagesPlain(InvokeArgs args) {
        return getImagesPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static Output<GetImagesResult> getImages(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getImages:getImages", TypeShape.of(GetImagesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static Output<GetImagesResult> getImages(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getImages:getImages", TypeShape.of(GetImagesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Image
     * 
     */
    public static CompletableFuture<GetImagesResult> getImagesPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getImages:getImages", TypeShape.of(GetImagesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static Output<GetInstanceResult> getInstance(GetInstanceArgs args) {
        return getInstance(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static CompletableFuture<GetInstanceResult> getInstancePlain(GetInstancePlainArgs args) {
        return getInstancePlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static Output<GetInstanceResult> getInstance(GetInstanceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInstance:getInstance", TypeShape.of(GetInstanceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static Output<GetInstanceResult> getInstance(GetInstanceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInstance:getInstance", TypeShape.of(GetInstanceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static CompletableFuture<GetInstanceResult> getInstancePlain(GetInstancePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getInstance:getInstance", TypeShape.of(GetInstanceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static Output<GetInstancesResult> getInstances() {
        return getInstances(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static CompletableFuture<GetInstancesResult> getInstancesPlain() {
        return getInstancesPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static Output<GetInstancesResult> getInstances(InvokeArgs args) {
        return getInstances(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static CompletableFuture<GetInstancesResult> getInstancesPlain(InvokeArgs args) {
        return getInstancesPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static Output<GetInstancesResult> getInstances(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInstances:getInstances", TypeShape.of(GetInstancesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static Output<GetInstancesResult> getInstances(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInstances:getInstances", TypeShape.of(GetInstancesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Instance
     * 
     */
    public static CompletableFuture<GetInstancesResult> getInstancesPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getInstances:getInstances", TypeShape.of(GetInstancesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static Output<GetInvocationResult> getInvocation(GetInvocationArgs args) {
        return getInvocation(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static CompletableFuture<GetInvocationResult> getInvocationPlain(GetInvocationPlainArgs args) {
        return getInvocationPlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static Output<GetInvocationResult> getInvocation(GetInvocationArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInvocation:getInvocation", TypeShape.of(GetInvocationResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static Output<GetInvocationResult> getInvocation(GetInvocationArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInvocation:getInvocation", TypeShape.of(GetInvocationResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static CompletableFuture<GetInvocationResult> getInvocationPlain(GetInvocationPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getInvocation:getInvocation", TypeShape.of(GetInvocationResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static Output<GetInvocationsResult> getInvocations() {
        return getInvocations(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static CompletableFuture<GetInvocationsResult> getInvocationsPlain() {
        return getInvocationsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static Output<GetInvocationsResult> getInvocations(InvokeArgs args) {
        return getInvocations(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static CompletableFuture<GetInvocationsResult> getInvocationsPlain(InvokeArgs args) {
        return getInvocationsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static Output<GetInvocationsResult> getInvocations(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInvocations:getInvocations", TypeShape.of(GetInvocationsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static Output<GetInvocationsResult> getInvocations(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getInvocations:getInvocations", TypeShape.of(GetInvocationsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Invocation
     * 
     */
    public static CompletableFuture<GetInvocationsResult> getInvocationsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getInvocations:getInvocations", TypeShape.of(GetInvocationsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static Output<GetKeypairResult> getKeypair(GetKeypairArgs args) {
        return getKeypair(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static CompletableFuture<GetKeypairResult> getKeypairPlain(GetKeypairPlainArgs args) {
        return getKeypairPlain(args, InvokeOptions.Empty);
    }
    /**
     * Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static Output<GetKeypairResult> getKeypair(GetKeypairArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getKeypair:getKeypair", TypeShape.of(GetKeypairResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static Output<GetKeypairResult> getKeypair(GetKeypairArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getKeypair:getKeypair", TypeShape.of(GetKeypairResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static CompletableFuture<GetKeypairResult> getKeypairPlain(GetKeypairPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getKeypair:getKeypair", TypeShape.of(GetKeypairResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static Output<GetKeypairsResult> getKeypairs() {
        return getKeypairs(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static CompletableFuture<GetKeypairsResult> getKeypairsPlain() {
        return getKeypairsPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static Output<GetKeypairsResult> getKeypairs(InvokeArgs args) {
        return getKeypairs(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static CompletableFuture<GetKeypairsResult> getKeypairsPlain(InvokeArgs args) {
        return getKeypairsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static Output<GetKeypairsResult> getKeypairs(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getKeypairs:getKeypairs", TypeShape.of(GetKeypairsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static Output<GetKeypairsResult> getKeypairs(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("bytepluscc:ecs/getKeypairs:getKeypairs", TypeShape.of(GetKeypairsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Plural Data Source schema for Byteplus::ECS::Keypair
     * 
     */
    public static CompletableFuture<GetKeypairsResult> getKeypairsPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("bytepluscc:ecs/getKeypairs:getKeypairs", TypeShape.of(GetKeypairsResult.class), args, Utilities.withVersion(options));
    }
}
